.gitignore
src/app/components/technical-record/technical-record.component.html
src/app/components/technical-record/technical-record.component.ts
src/environments/environment.ts

All these bugs can now be tested on the branch devops (9511, 9512, 9513, 9524).

Feature/cvsb 9213 - solved bug tickets - 9511, 9512, 9513, 9524 

---

package-lock.json
src/app/components/header/header.component.html
src/app/components/header/header.component.scss
src/app/components/technical-record/technical-record.component.html
src/app/components/technical-record/technical-record.component.scss

Please find in here: header working & the fixed css for add goods + guidance notes

header working & css for add goods + guidance notes

---

src/app/technical-record/technical-record.component.html
src/app/technical-record/technical-record.component.scss
src/app/technical-record/technical-record.component.ts
src/assets/config/config.dev.json

CVSB-10645 - We should display either "Statement reference number" or "Product list reference number"
CVSB-10620 - Some details like "UN number" and "Additional product list details" are displayed even if "productList" field is not set in dynamo
CVSB-10621 - "Statement reference number" is not displayed even if "statement" field is set in dynamo
CVSB-10623 - "Product list reference number" is not displayed even if "productListRefNo" field is set in dynamo
CVSB-10645 - We should display either "Statement reference number" or "Product list reference number"

Bug fixing on ADR functionality 

---

src/app/technical-record-search/auth-token-interceptor.ts

Make app login you again on token expire instead of throwing error.
[https://jira.dvsacloud.uk/browse/CVSB-10977](url)

CVSB-10977

---

.gitignore
package.json
src/app/technical-record/technical-record.component.html
src/app/technical-record/technical-record.component.spec.ts
src/app/technical-record/technical-record.component.ts

https://jira.dvsacloud.uk/browse/CVSB-11463

CVSB-11463  Added whatespace validation into techinical record component

---

src/app/technical-record/technical-record.component.html

https://jira.dvsacloud.uk/browse/CVSB-11845

CVSB-11845  Fixed sensing value field show

---

src/app/app.enums.ts
src/app/shared/delayed-retry/delayed-retry.spec.ts
src/app/shared/delayed-retry/delayed-retry.ts
src/app/shell/header/header.component.spec.ts
src/app/store/actions/Error.actions.spec.ts
src/app/store/actions/VehicleTechRecordModel.actions.spec.ts
src/app/store/actions/router.spec.ts
src/app/store/effects/VehicleTechRecordModel.effects.spec.ts
src/app/store/effects/VehicleTechRecordModel.effects.ts
src/app/store/effects/VehicleTestResultModel.effects.ts
src/app/store/reducers/Error.reducers.spec.ts
src/app/store/reducers/Error.reducers.ts
src/app/store/reducers/Loader.reducers.ts
src/app/technical-record-search/technical-record.service.spec.ts
src/app/technical-record/technical-record.component.spec.ts

https://jira.dvsacloud.uk/browse/CVSB-12578

Fxied test result showing error when not found

---

src/app/models/vehicle-tech-record.model.ts
src/app/pipes/SortByDatePipe.ts
src/app/shared/shared.module.ts
src/app/store/actions/VehicleTechRecordModel.actions.spec.ts
src/app/store/effects/VehicleTechRecordModel.effects.spec.ts
src/app/store/effects/VehicleTechRecordModel.effects.ts
src/app/store/effects/VehicleTestResultModel.effects.ts
src/app/store/reducers/VehicleTechRecordModel.reducers.spec.ts
src/app/technical-record/tech-rec-history/tech-rec-history.component.html
src/app/technical-record/tech-record-helpers.service.spec.ts
src/app/technical-record/tech-record-helpers.service.ts
src/app/technical-record/technical-record.component.html
src/app/technical-record/test-history/test-history.component.html

As the DVSA, we want VTM to accurately show the tests for the queried vehicle, so that we can navigate to the correct test (system number join)
https://jira.dvsacloud.uk/browse/CVSB-12661

feature/CVSB-12661 

---

src/app/pipes/SortByDatePipe.spec.ts
src/app/pipes/SortByDatePipe.ts

Fixed bug & also added test spec file and tests for SortByDate pipe

feature/CVSB-12904 - Bug : The test history is displayed in order of oldest to newest

---

src/app/app.enums.ts
src/app/landing-page/landing-page.component.html
src/app/pipes/DefaultNullOrEmptyPipe.spec.ts
src/app/pipes/DefaultNullOrEmptyPipe.ts
src/app/pipes/FilterRecordPipe.spec.ts
src/app/store/effects/VehicleTechRecordModel.effects.ts
src/app/store/effects/VehicleTestResultModel.effects.spec.ts
src/app/store/selectors/route.selectors.spec.ts
src/app/store/selectors/searchPage.selectors.spec.ts
src/app/technical-record-search/technical-record-search.component.html
src/app/technical-record-search/technical-record-search.component.scss
src/app/technical-record-search/technical-record-search.component.spec.ts
src/app/technical-record-search/technical-record-search.component.ts
src/app/technical-record-search/technical-record.service.spec.ts
src/app/technical-record-search/technical-record.service.ts
src/app/technical-record/adr-details/adr-details-form/store/adrDetails.reducer.spec.ts
src/app/technical-record/adr-details/adr-details-form/store/adrDetails.reducer.ts
src/app/technical-record/store/adr-details-submit-effects.ts
src/app/technical-record/technical-record.component.html
src/app/technical-record/technical-record.component.spec.ts

https://jira.dvsacloud.uk/browse/CVSB-11329

feature/CVSB-11329 - [FE] As the DVSA, we want to be able to search for vehicles when the full VIN is less than 9 characters in VTM

---

src/app/app.module.ts
src/app/shell/footer/footer.component.html
src/app/shell/header/header.component.spec.ts
src/app/shell/header/header.component.ts
src/app/shell/header/logout-modal/logout-modal.component.html
src/app/shell/header/logout-modal/logout-modal.component.scss
src/app/shell/header/logout-modal/logout-modal.component.spec.ts
src/app/shell/header/logout-modal/logout-modal.component.ts

[Jira tichet](https://jira.dvsacloud.uk/browse/CVSB-7409)

Footer fix and logout modal (CVSB-7409)

---

src/app/technical-record/technical-record.component.html
src/app/technical-record/test-history/test-history.component.html
src/app/technical-record/test-history/test-history.component.ts

https://jira.dvsacloud.uk/browse/CVSB-13093

feature/CVSB-13093 - Issues on tech record view page

---

src/app/app-routing.module.ts
src/app/app.component.scss
src/app/app.module.ts
src/app/technical-record/test-history/test-history.component.html
src/app/test-record/test-record.component.html
src/app/test-record/test-record.component.spec.ts
src/app/test-record/test-record.component.ts

**Needs to be updated for systemNumber changes** 
https://jira.dvsacloud.uk/browse/CVSB-11570

feature/CVSB-11570 - [FE] As a VTM user,  I want to be able to navigate to the Test Details screen

---

src/app/multiple-records/multiple-records.component.html
src/app/multiple-records/multiple-records.component.scss
src/app/pipes/FilterMultipleRecordsPipe.ts
src/app/pipes/__snapshots__/FilterMultipleRecordsPipe.spec.ts.snap

Bugs for 10597 (solved both in here):
https://jira.dvsacloud.uk/browse/CVSB-13720
https://jira.dvsacloud.uk/browse/CVSB-13659
note: I branched out from 10597 & we should merge the fix after test

solved bugs CVSB-13720 & CVSB-13659 for 10597

---

src/app/multiple-records/multiple-records.component.html
src/app/pipes/FilterMultipleRecordsPipe.spec.ts
src/app/pipes/FilterMultipleRecordsPipe.ts
src/app/pipes/OrderByStatusPipe.ts
src/app/pipes/__snapshots__/FilterMultipleRecordsPipe.spec.ts.snap

Ticket:
https://jira.dvsacloud.uk/browse/CVSB-14215

feature/CVSB-14215 - Tech record history bug fix

---

src/app/app.module.ts
src/app/store/effects/VehicleTechRecordModel.effects.ts
src/app/technical-record-search/technical-record.service.ts
src/app/technical-record/technical-record.mapper.ts

https://jira.dvsacloud.uk/browse/CVSB-14682

bug CVSB-14682 to fix saving of techRecord using system number

---

src/app/technical-record/tech-rec-history/tech-rec-history.component.spec.ts
src/app/technical-record/technical-record.component.html

CVSB-10163: PR changes for merge to common. rebased after merge to common.

CVSB-10163: components with unit tests with rebase with common

---

src/app/technical-record/adr/applicant-details/__snapshots__/applicant-details.component.spec.ts.snap
src/app/technical-record/adr/applicant-details/applicant-details.component.html
src/app/technical-record/dimensions/dimensions.component.html
src/app/technical-record/letters-of-authorisation/letters-of-authorisation.component.html
src/app/technical-record/plates/__snapshots__/plates.component.spec.ts.snap
src/app/technical-record/plates/plates.component.html
src/app/technical-record/technical-record.component.html
src/app/technical-record/test-history/test-history.component.html
src/app/technical-record/weights/__snapshots__/weights.component.spec.ts.snap
src/app/technical-record/weights/weights.component.html
src/app/utils/testing.utils.ts

Point 18  and 19 fixed from 
https://jira.dvsacloud.uk/browse/CVSB-15248

feat(cvsb-10163): trl view with unit tests with rebase with common

---

src/app/test-record/defects/defects.component.html
src/app/test-record/test-section/test-section.component.html

Ticket: https://jira.dvsacloud.uk/browse/CVSB-15376

Feature/CVSB-15376 - [BUG] Remaining issues to be fixed on CVSB-10283

---

src/app/technical-record/brakes/brakes.component.html
src/app/technical-record/technical-record.component.html
src/app/technical-record/weights/__snapshots__/weights.component.spec.ts.snap
src/app/technical-record/weights/weights-psv/__snapshots__/weights-psv.component.spec.ts.snap
src/app/technical-record/weights/weights-psv/weights-psv.component.html
src/app/technical-record/weights/weights.component.html

fix(feature/CVSB-15378): Fix to remove Brakes section for vehicle type HGV
https://jira.dvsacloud.uk/browse/CVSB-15378

Bug CVSB-15378 - Fix to hide Brake section for HGV type of vehicles

---

src/app/technical-record/technical-record.component.html

fix(feature/CVSB-15378): Fix to remove duplicate test-record-completeness html id
https://jira.dvsacloud.uk/browse/CVSB-15378

Bug fix CVSB-15378

---

src/app/technical-record/test-history/test-history.component.html

PR: https://jira.dvsacloud.uk/browse/CVSB-15403

Feature/CVSB-15403 - Expiry date is incorrectly displayed on tech record -> test hisory

---

src/app/models/tech-record.model.ts
src/app/technical-record/brakes/brakes-psv/__snapshots__/brakes-psv.component.spec.ts.snap
src/app/technical-record/brakes/brakes-psv/brakes-psv.component.html
src/app/technical-record/dda/__snapshots__/dda.component.spec.ts.snap
src/app/technical-record/dda/dda.component.html
src/app/technical-record/notes/__snapshots__/notes.component.spec.ts.snap
src/app/technical-record/notes/notes.component.html
src/app/technical-record/notes/notes.component.spec.ts
src/app/technical-record/vehicle-summary/vehicle-summary-psv/__snapshots__/vehicle-summary-psv.component.spec.ts.snap
src/app/technical-record/vehicle-summary/vehicle-summary-psv/vehicle-summary-psv.component.html
src/app/technical-record/vehicle-summary/vehicle-summary.component.html
src/app/technical-record/weights/weights-psv/__snapshots__/weights-psv.component.spec.ts.snap
src/app/technical-record/weights/weights-psv/weights-psv.component.html

a few fixes in weights-psv and id updates. Also added missing unit tests for notes component.

fix: dimension min max column only for hgv and trl

---

src/app/app.enums.ts
src/app/technical-record/notes/__snapshots__/notes.component.spec.ts.snap
src/app/technical-record/notes/notes.component.html
src/app/technical-record/notes/notes.component.spec.ts
src/app/technical-record/tech-record-helpers.service.spec.ts
src/app/technical-record/tech-record-helpers.service.ts
src/app/technical-record/technical-record.component.html
src/app/technical-record/technical-record.module.ts
src/app/technical-record/vehicle-summary/__snapshots__/vehicle-summary.component.spec.ts.snap
src/app/technical-record/vehicle-summary/vehicle-summary-hgv/__snapshots__/vehicle-summary-hgv.component.spec.ts.snap
src/app/technical-record/vehicle-summary/vehicle-summary-hgv/vehicle-summary-hgv.component.html
src/app/technical-record/vehicle-summary/vehicle-summary-hgv/vehicle-summary-hgv.component.spec.ts
src/app/technical-record/vehicle-summary/vehicle-summary-hgv/vehicle-summary-hgv.component.ts
src/app/technical-record/vehicle-summary/vehicle-summary-psv/vehicle-summary-psv.component.spec.ts
src/app/technical-record/vehicle-summary/vehicle-summary-trl/__snapshots__/vehicle-summary-trl.component.spec.ts.snap
src/app/technical-record/vehicle-summary/vehicle-summary-trl/vehicle-summary-trl.component.html
src/app/technical-record/vehicle-summary/vehicle-summary-trl/vehicle-summary-trl.component.spec.ts
src/app/technical-record/vehicle-summary/vehicle-summary-trl/vehicle-summary-trl.component.ts
src/app/technical-record/vehicle-summary/vehicle-summary.component.html
src/app/technical-record/vehicle-summary/vehicle-summary.component.spec.ts
src/app/technical-record/vehicle-summary/vehicle-summary.component.ts

recreated PR for re-approvals.

feat(CVSB-11815): Specialist vehicle view

---

src/app/shared/libraries/accordion-item/__snapshots__/accordion-item.component.spec.ts.snap
src/app/shared/libraries/accordion-item/accordion-item.component.html
src/app/store/effects/VehicleTestResultModel.effects.ts
src/app/test-record/emission-details/edit/__snapshots__/emission-details-edit.component.spec.ts.snap
src/app/test-record/emission-details/edit/emission-details-edit.component.ts
src/app/test-record/guards/test-result.guard.ts
src/app/test-record/test-record.component.ts
src/app/test-record/test-record.enums.ts
src/app/test-record/test-record.mapper.ts
src/app/test-record/vehicle/__snapshots__/vehicle.component.spec.ts.snap
src/app/test-record/vehicle/edit/__snapshots__/vehicle-edit.component.spec.ts.snap
src/app/test-record/vehicle/edit/vehicle-edit.component.ts
src/app/test-record/vehicle/vehicle.component.ts
src/app/test-record/visit/edit/__snapshots__/visit-edit.component.spec.ts.snap
src/app/test-record/visit/edit/visit-edit.component.ts

Bugs fixed: 
https://jira.dvsacloud.uk/browse/CVSB-15760
https://jira.dvsacloud.uk/browse/CVSB-14917
https://jira.dvsacloud.uk/browse/CVSB-14877
https://jira.dvsacloud.uk/browse/CVSB-14823
https://jira.dvsacloud.uk/browse/CVSB-14920

Feature/CVSB-10278 - BUG FIXING rework

---

src/app/test-record/test-record.mapper.ts

Add code and description for test types mapper
https://jira.dvsacloud.uk/browse/CVSB-16444

Feature/CVSB-16444 - Issue when updating test record

---

src/app/technical-record/adr/additional-adr-details/__snapshots__/additional-adr-details.component.spec.ts.snap
src/app/technical-record/adr/additional-adr-details/additional-adr-details.component.html
src/app/technical-record/adr/additional-adr-details/additional-adr-details.component.spec.ts
src/app/technical-record/adr/additional-adr-details/edit/__snapshots__/additional-adr-detail-edit.component.spec.ts.snap
src/app/technical-record/adr/additional-adr-details/edit/additional-adr-detail-edit.component.html
src/app/technical-record/adr/adr-details/edit/__snapshots__/adr-details-edit.component.spec.ts.snap
src/app/technical-record/adr/adr-details/edit/adr-details-edit.component.html
src/app/technical-record/adr/applicant-details/edit/__snapshots__/applicant-details-edit.component.spec.ts.snap
src/app/technical-record/adr/applicant-details/edit/applicant-details-edit.component.html
src/app/technical-record/adr/battery-list-applicable/edit/__snapshots__/battery-list-applicable-edit.component.spec.ts.snap
src/app/technical-record/adr/battery-list-applicable/edit/battery-list-applicable-edit.component.html
src/app/technical-record/adr/certificate/edit/__snapshots__/certificate-edit.component.spec.ts.snap
src/app/technical-record/adr/certificate/edit/certificate-edit.component.html
src/app/technical-record/adr/declaration-seen/edit/__snapshots__/declaration-seen-edit.component.spec.ts.snap
src/app/technical-record/adr/declaration-seen/edit/declaration-seen-edit.component.html
src/app/technical-record/adr/memo/edit/__snapshots__/memo-edit.component.spec.ts.snap
src/app/technical-record/adr/memo/edit/memo-edit.component.html
src/app/technical-record/adr/tank-details/edit/__snapshots__/tank-details-edit.component.spec.ts.snap
src/app/technical-record/adr/tank-details/edit/tank-details-edit.component.html
src/app/technical-record/adr/tank-inpections/edit/__snapshots__/tank-inspection-edit.component.spec.ts.snap
src/app/technical-record/adr/tank-inpections/edit/tank-inspections-edit.component.html

PR for: https://jira.dvsacloud.uk/browse/CVSB-14891

chore(CVSB-14891): renamed some adr fields

---

src/app/technical-record/adr/tank-inpections/edit/__snapshots__/tank-inspection-edit.component.spec.ts.snap
src/app/technical-record/adr/tank-inpections/edit/tank-inspection-edit.component.spec.ts
src/app/technical-record/adr/tank-inpections/edit/tank-inspections-edit.component.html

Ticket link https://jira.dvsacloud.uk/browse/CVSB-14893

Feature/cvsb 14893: removing subsequent tank inspection

---

src/app/test-record/test-record.component.html

fix(CVSB-12375)- line of code missing from 00000

---

src/app/technical-record/technical-record.component.html

Fixed duplicated id
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-16707)

fix(16707): fix duplicated id within tech-rec.component

---

package.json
src/app/technical-record/technical-record.component.ts

[https://jira.dvsacloud.uk/browse/CVSB-16657]()

CVSB-16657 - ADR section keep closing in view/edit mode

---

src/app/technical-record-create/technical-record-create.component.ts

Fixed bug on 10760
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-16536)

fix(10760): fixed special character search on vehicle create

---

setupJest.ts
src/app/app.enums.ts
src/app/technical-record/record-status/__snapshots__/record-status.component.spec.ts.snap
src/app/technical-record/record-status/record-status.component.html
src/app/technical-record/record-status/record-status.component.spec.ts
src/app/technical-record/record-status/record-status.component.ts
src/app/technical-record/tech-rec-history/__snapshots__/tech-rec-history.component.spec.ts.snap
src/app/technical-record/tech-rec-history/tech-rec-history.component.html
src/app/technical-record/tech-rec-history/tech-rec-history.component.spec.ts
src/app/technical-record/tech-rec-history/tech-rec-history.component.ts
src/app/technical-record/technical-record.component.html
src/app/technical-record/technical-record.component.spec.ts
src/app/technical-record/technical-record.component.ts
src/app/utils/index.ts
src/app/utils/utils.functions.spec.ts
src/app/utils/utils.functions.ts

It implements all ACs on 8650 in a renewed way_
[https://jira.dvsacloud.uk/browse/CVSB-16683](https://jira.dvsacloud.uk/browse/CVSB-16683)
screenshots:

Feature/cvsb 16683 new - Improve & renew upon #8650

---

src/app/models/test.type.ts
src/app/test-record/defects/__snapshots__/defects.component.spec.ts.snap
src/app/test-record/defects/defects.component.html
src/app/test-record/defects/defects.component.spec.ts
src/app/test-record/defects/defects.component.ts
src/app/test-record/test-record.component.html
src/app/test-record/test-record.container.ts
src/app/test-record/test-record.enums.ts
src/app/test-record/test-record.mapper.ts
src/app/test-record/test-section/__snapshots__/test-section.component.spec.ts.snap
src/app/test-record/test-section/test-section.component.html
src/app/test-record/test-section/test-section.component.ts
src/app/test-record/test-types-applicable.enum.ts
src/app/utils/test-type-applicable-models.utils.ts

Ticket:
https://jira.dvsacloud.uk/browse/CVSB-10362
Bugs solved in here:
- https://jira.dvsacloud.uk/browse/CVSB-17104

Feature/CVSB-10362 - view a specialist test record

---

src/app/technical-record/applicant/__snapshots__/applicant.component.spec.ts.snap
src/app/technical-record/applicant/applicant.component.spec.ts
src/app/technical-record/applicant/applicant.component.ts
src/app/technical-record/authorisation-into-service/authorisation-into-service.component.ts
src/app/technical-record/brakes/brakes.component.ts
src/app/technical-record/manufacturer/__snapshots__/manufacturer.component.spec.ts.snap
src/app/technical-record/manufacturer/manufacturer.component.spec.ts
src/app/technical-record/manufacturer/manufacturer.component.ts
src/app/technical-record/notes/__snapshots__/notes.component.spec.ts.snap
src/app/technical-record/notes/notes.component.html
src/app/technical-record/notes/notes.component.spec.ts
src/app/technical-record/notes/notes.component.ts
src/app/technical-record/purchaser/__snapshots__/purchaser.component.spec.ts.snap
src/app/technical-record/purchaser/purchaser.component.spec.ts
src/app/technical-record/purchaser/purchaser.component.ts
src/app/technical-record/record-status/record-status.component.spec.ts
src/app/technical-record/record-status/record-status.component.ts
src/app/technical-record/tech-rec-history/tech-rec-history.component.spec.ts
src/app/technical-record/tech-rec-history/tech-rec-history.component.ts
src/app/technical-record/technical-record.component.html
src/app/technical-record/vehicle-summary/__snapshots__/vehicle-summary.component.spec.ts.snap
src/app/technical-record/vehicle-summary/edit/__snapshots__/vehicle-summary-edit.component.spec.ts.snap
src/app/technical-record/vehicle-summary/edit/vehicle-summary-edit.component.html
src/app/technical-record/vehicle-summary/edit/vehicle-summary-edit.component.spec.ts
src/app/technical-record/vehicle-summary/edit/vehicle-summary-edit.component.ts
src/app/technical-record/vehicle-summary/vehicle-summary.component.html
src/app/technical-record/vehicle-summary/vehicle-summary.component.spec.ts
src/app/technical-record/vehicle-summary/vehicle-summary.component.ts

[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-17197)

fix(cvsb-17197): render edited values in viewonly mode

---

src/app/models/tech-record.model.ts
src/app/technical-record/applicant/edit/__snapshots__/applicant-edit.component.spec.ts.snap
src/app/technical-record/applicant/edit/applicant-edit.component.html
src/app/technical-record/applicant/edit/applicant-edit.component.spec.ts
src/app/technical-record/manufacturer/edit/manufacturer-edit.component.ts
src/app/technical-record/purchaser/__snapshots__/purchaser.component.spec.ts.snap
src/app/technical-record/purchaser/edit/__snapshots__/purchaser-edit.component.spec.ts.snap
src/app/technical-record/purchaser/edit/purchaser-edit.component.html
src/app/technical-record/purchaser/edit/purchaser-edit.component.spec.ts
src/app/technical-record/purchaser/edit/purchaser-edit.component.ts
src/app/technical-record/purchaser/purchaser.component.html
src/app/technical-record/purchaser/purchaser.component.ts
src/app/technical-record/shared/address-form/__snapshots__/address-form.component.spec.ts.snap
src/app/technical-record/shared/address-form/address-form.component.html
src/app/technical-record/shared/address-form/address-form.component.spec.ts
src/app/technical-record/shared/address-form/address-form.component.ts
src/app/technical-record/technical-record.component.html
src/app/technical-record/technical-record.module.ts
src/app/utils/testing.utils.ts

_Refactor Applicant by extracting common Address Form away_
[https://jira.dvsacloud.uk/browse/CVSB-16941](https://jira.dvsacloud.uk/browse/CVSB-16941)

CVSB-16941-subtask: refactor Applicant + Address Form for reusability

---

src/index.html

Adds a `<meta />` element to `<head />` to prove the existing pipeline works as part of our investigations
[CB2-2945](https://jira.dvsacloud.uk/browse/CB2-2945)

chore(cb2-2945): spike - pipeline investigation and test

---

documentation.json
package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/layout/footer/footer.component.html
src/app/layout/header/header.component.html
src/app/layout/header/header.component.spec.ts
src/app/layout/header/header.component.ts
src/app/layout/header/header.stories.ts
src/app/user-service.ts
src/environments/environment.prod.ts
src/environments/environment.ts
src/global-styles.scss
src/index.html
src/styles.scss

feature/CB2-2879: Authentication

---

src/app/app.module.ts

Passes auth token to API endpoint

fix(cb2-2880): pass auth token to api endpoint

---

src/app/app.module.ts

Turns out the scope needs to be non-null

fix(cb2-2880): pass auth to api with empty scope

---

src/app/app.component.html
src/app/app.module.ts
src/app/features/global-error/global-error.component.html
src/app/features/global-error/global-error.component.spec.ts
src/app/features/global-error/global-error.component.ts
src/app/features/global-error/global-error.stories.ts
src/app/features/search/search.component.html
src/app/services/global-error/global-error.service.ts
src/app/store/app-store.module.ts
src/app/store/global-error/global-error-state.module.ts
src/app/store/global-error/reducers/global-error-service.reducer.spec.ts
src/app/store/global-error/reducers/global-error-service.reducer.ts
src/app/store/global-error/selectors/global-error.selectors.spec.ts
src/app/store/global-error/selectors/global-error.selectors.ts
src/app/store/index.ts
src/app/store/technical-records/technical-record-service.actions.ts
src/app/store/technical-records/technical-record-service.effects.ts
src/app/store/test-records/reducers/test-records.reducer.spec.ts

A new global error component for displaying errors on the services, this is an MVP and a second iteration will be done to map errors to fields to comply with GDS.

CB2-3314: Global Error Handling

---

setenv.ts
src/app/app.module.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Requests an Access Token using the ClientId of the API as configured in Azure AD
https://jira.dvsacloud.uk/browse/CB2-3527

fix(cb2-3527): requests correct access token for api calls

---

src/app/features/test-record-summary/test-record-summary.component.html
src/app/features/test-record-summary/test-record-summary.component.spec.ts
src/app/features/test-record-summary/test-record-summary.module.ts

Fixing the date to match the AC on the ticket
[[link to ticket number]()](https://jira.dvsacloud.uk/browse/CB2-3291)

cb2-3291: datetime fix

---

tsconfig.json

Fixes an issue running the unit tests in the Jenkins pipeline (thanks @aaron-downing)

fix(cb2-3498): fixes unit tests in jenkins pipeline

---

README.md
mock-api/mock-api-server.ts
package.json
src/app/app.component.html
src/app/app.module.ts
src/app/features/global-error/global-error.component.spec.ts
src/app/layout/spinner/spinner.component.html
src/app/layout/spinner/spinner.component.scss
src/app/layout/spinner/spinner.component.spec.ts
src/app/layout/spinner/spinner.component.ts
src/app/layout/spinner/spinner.service.spec.ts
src/app/layout/spinner/spinner.service.ts
src/app/store/app-store.module.ts
src/app/store/index.ts
src/app/store/spinner/reducers/spinner.reducer.spec.ts
src/app/store/spinner/reducers/spinner.reducer.ts
src/app/store/spinner/selectors/spinner.selectors.spec.ts
src/app/store/spinner/selectors/spinner.selectors.ts
src/app/store/spinner/spinner-state.module.ts

feature/CB2-3618: Loading spinner

---

src/app/forms/templates/psv/psv-annual.template.ts

Defects resolved:
- Test Date showing DateTime not Date.
- Test Start Time showing DateTime not Time
- Test End Time showing DateTime not Time
Previous:
Now:
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3777)

fix(cb2-3777): amend date time formating for test record

---

src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts

Remove the duplicate titles displaying.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3775?atlOrigin=eyJpIjoiNmFhMjk0ODQ4MGY5NDkzYzg4YmZlZTY3MTkzM2I4YzciLCJwIjoiaiJ9)

fix(cb2-3775): Remove the label to stop duplicate titles showing

---

src/app/forms/templates/psv/psv-annual.template.ts

Defect:
- Test Result not being shown and wrong description being used 
Before:
After:
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3781)

fix(cb2-3781): show test result in test record

---

src/app/forms/templates/psv/psv-annual.template.ts
src/app/models/test-type.model.ts
src/mocks/mock-test-result.ts

Move model and template to a string, instead of array.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3776?atlOrigin=eyJpIjoiYjNiYWVhZGJlNTZmNDgwYTk3MDNkZjZiODNmYTlkNGUiLCJwIjoiaiJ9)

fix(cb2-3776): Change to a string to match database return

---

src/app/features/tech-record-summary/tech-record-summary.component.html
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.spec.ts
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.ts
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts

**No squashing please**
Resolves defects:
- Date of first registration in YYY/MM/DD format
- Vehicle summary heading cosmetic change so that sections have more even spacing 
[CB2-3775](https://dvsa.atlassian.net/browse/CB2-3775)
[CB2-3791](https://dvsa.atlassian.net/browse/CB2-3791)
Before;
Now:

Bug Fixes: CB2-3775 & CB2-3791

---

src/app/forms/templates/psv/psv-annual.template.ts
src/app/models/test-type.model.ts
src/mocks/mock-test-result.ts

Added the seatbelt fields to the Test results Form. 
[CB2-3411](https://dvsa.atlassian.net/browse/CB2-3411)

feat(cb2-3411): added seatbelts to test form

---

src/app/forms/components/dynamic-form-group/dynamic-form-group.component.scss
src/app/forms/templates/psv/psv-annual.template.ts
src/app/models/test-result.model.ts
src/app/models/test-type.model.ts
src/mocks/mock-test-result.ts

Moved Visit section to test-results and styling cleanup

fix(cb2-3413): moved visit data into test-result model

---

src/app/features/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/psv/psv-brake-wheels-half-locked.template.ts
src/app/forms/templates/psv/psv-brake-wheels-not-locked.template.ts
src/app/forms/templates/psv/psv-brake.template.ts
src/app/models/vehicle-tech-record.model.ts
src/mocks/mock-vehicle-technical-record.mock.ts

Create the brake sections of the tech record and display them.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3387)

CB2-3387: Create brake sections of tech record

---

src/app/features/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record-summary/tech-record-summary.component.ts
src/app/forms/components/checkbox-group/checkbox-group.component.spec.ts
src/app/forms/templates/psv/psv-applicant-details.template.ts
src/app/models/vehicle-tech-record.model.ts
src/mocks/mock-vehicle-technical-record.mock.ts

Create the last applicant section from the tech record and display
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3389)

feat(cb2-3390): create applicant details section

---

src/app/forms/templates/psv/psv-brake-wheels-half-locked.template.ts
src/app/forms/templates/psv/psv-brake-wheels-not-locked.template.ts

The values were the wrong way, now they are not.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3991)

fix(cb2-3991): change form template values to be correct

---

src/app/features/tech-record/tech-record.component.ts

[## Ticket title](https://dvsa.atlassian.net/browse/CB2-3355)
Add in a check to stop the search being erroneously called with no params.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3355)

fix(cb2-3355): add in defensive code for vin search

---

src/app/app-routing.module.ts

_Change the msal activation bahviour back to original behaviour_

fix: msal guard activation

---

src/app/app.component.ts
src/app/core/components/footer/footer.component.ts
src/app/core/components/global-error/global-error.component.ts
src/app/features/home/home.component.ts
src/app/features/search/search.component.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
src/app/features/test-records/test-records.component.ts
src/app/forms/components/checkbox-group/checkbox-group.component.ts
src/app/forms/components/checkbox-group/checkbox-group.stories.ts
src/app/forms/components/defect/defect.component.ts
src/app/forms/components/defects/defects.component.ts
src/app/forms/components/radio-group/radio-group.component.ts
src/app/forms/components/radio-group/radio-group.stories.ts
src/app/forms/components/text-input/text-input.component.ts
src/app/forms/components/view-combination/view-combination.component.ts
src/app/forms/components/view-list-item/view-list-item.component.ts
src/app/forms/services/dynamic-form.service.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

[CB2-4032](https://dvsa.atlassian.net/browse/CB2-4032)

feat(cb2-4032): Code smells resolved

---

src/app/features/test-records/components/base-test-record/base-test-record.component.spec.ts
src/app/features/test-records/components/base-test-record/base-test-record.component.ts
src/app/features/test-records/test-records-routing.module.ts
src/app/features/test-records/test-records.module.ts
src/app/features/test-records/views/amended-test-record/amended-test-record.component.html
src/app/features/test-records/views/amended-test-record/amended-test-record.component.ts
src/app/features/test-records/views/test-record/test-record.component.html
src/app/features/test-records/views/test-record/test-record.component.spec.ts
src/app/features/test-records/views/test-record/test-record.component.ts
src/app/forms/components/defect/defect.component.html
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.spec.ts
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.ts
src/app/guards/no-edit.guard.spec.ts
src/app/guards/no-edit.guard.ts
src/app/services/router/router.service.spec.ts
src/app/services/router/router.service.ts
src/app/shared/components/button-group/button-group.component.html
src/app/shared/components/button-group/button-group.component.spec.ts
src/app/shared/components/button-group/button-group.component.ts
src/app/shared/components/button/button.component.html
src/app/shared/components/button/button.component.spec.ts
src/app/shared/components/button/button.component.ts
src/app/shared/shared.module.ts
src/app/store/router/selectors/router.selectors.ts
tsconfig.json

- Create buttons/links navigate in and out of edit mode
- Get the edit flag from the router state
- Modify the dynamic form engine to handle different nodes
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4028)

feat(cb2-3994): add functionality required to make view editable

---

src/app/features/search/search.component.html
src/app/features/search/search.component.spec.ts
src/app/features/search/search.component.ts

[CB2-4184](https://dvsa.atlassian.net/browse/CB2-4184)

feature/CB2-4184: Create a UI Selector for Search Criteria

---

src/app/features/search/search.component.html
src/app/features/search/search.module.ts
src/app/features/search/single-search-result/single-search-result.component.html
src/app/features/search/single-search-result/single-search-result.component.spec.ts
src/app/features/search/single-search-result/single-search-result.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.scss
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/search/single-search-result.template.ts
src/app/services/technical-record/technical-record.service.ts

Create a search result component for displaying tech records on the search page.
[CB2-4187](https://dvsa.atlassian.net/browse/CB2-4187)

feature/CB2-4187: Search Result Component

---

src/app/forms/components/select/select.component.html
src/app/forms/components/select/select.component.spec.ts
src/app/forms/components/select/select.component.ts
src/app/forms/components/select/select.stories.ts
src/app/forms/dynamic-forms.module.ts

_Create a dynamic form select component_
[CB2-4033](https://dvsa.atlassian.net/browse/CB2-4033)

feat(cb2-4033): created select element

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/hgv/hgv-brakes.template.ts

Create a template for the brakes section and add it to the summary page for HGV and TRL.
[CB2-4269](https://dvsa.atlassian.net/browse/CB2-4269)

feature(cb2-4269): Add the Brakes Section for HGV and TRL Tech Records

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/hgv/hgv-tyres.template.ts

Add a template for tyres and use it on the tech record summary for HGVs.
[CB2-4268](https://dvsa.atlassian.net/browse/CB2-4268)

feature(CB2-4268): Add a Tyres Section to the Tech Record Summary

---

src/app/models/vehicle-tech-record.model.ts

Adds 'long semi-trailer' to vehicleConfiguration enum to reflect changes in VT.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-396)

feat(cb2-396): add long semi trailer to vehicle configuration enum

---

src/app/forms/templates/hgv/hgv-brakes.template.ts

Fix a column name in the brake template
[4431](https://dvsa.atlassian.net/browse/CB2-4431)

fix(cb2-4431): Fix column name for brake template

---

src/app/services/technical-record/technical-record.service.ts

The the way the `params` object's property is accessed.
[CB2-2891](https://dvsa.atlassian.net/browse/CB2-2891)

bugfix(CB2-2891): Fix the New Search Bug

---

src/app/features/search/search.component.spec.ts
src/app/services/technical-record/technical-record.service.spec.ts
src/app/services/technical-record/technical-record.service.ts
src/app/store/global-error/reducers/global-error-service.reducer.ts
src/app/store/technical-records/actions/technical-record-service.actions.spec.ts
src/app/store/technical-records/actions/technical-record-service.actions.ts
src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts
src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
src/app/store/technical-records/reducers/technical-record-service.reducer.ts
src/app/store/technical-records/selectors/technical-record-service.selectors.ts

[CB2-2893](https://dvsa.atlassian.net/browse/CB2-2893)

feature(CB2-2893): Add the Ability to Search for Tech Records using the Trailer ID

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/components/view-list-item/view-list-item.component.html
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/general/notes.template.ts

Add a new view type (`FULLWIDTH`) to dynamic forms.
Use that new type to add a notes section to HGV and TRL tech records.
[CB2-4275](https://dvsa.atlassian.net/browse/CB2-4275)

feature(CB2-4275): Add a Notes Section for HGV and TRL Tech Records

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/trl/trl-axle-weights.template.ts
src/app/forms/templates/trl/trl-gross-vehicle-weights.template.ts
src/app/forms/templates/trl/trl-manufacturer.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts

[CB2-4169](https://dvsa.atlassian.net/browse/CB2-4169)

feature(CB2-4169): Add a Manufacturer Section to TRL Summary

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/trl/trl-auth-into-service.template.ts

[CB2-4170](https://dvsa.atlassian.net/browse/CB2-4170)

feature(CB2-4170): Add the Auth into Service Section to TRL Summary

---

src/app/forms/templates/general/body.template.ts

[CB2-4590](https://dvsa.atlassian.net/browse/CB2-4590)

bugfix(CB2-4590): Correct the Typos on the Body Template

---

src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
src/app/services/test-records/test-records.service.ts
src/app/store/test-records/effects/test-records.effects.spec.ts
src/app/store/test-records/effects/test-records.effects.ts

_Fix the put api call_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3994)

fix(cb2-3994): fix put test result method to use system number

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/psv/psv-dda.template.ts
src/app/models/vehicle-tech-record.model.ts
src/mocks/psv-record.mock.ts

Create the DDA section template for the PSV records.
[CB2-3388](https://dvsa.atlassian.net/browse/CB2-3388)

CB2-3388: Create DDA template for PSV

---

.prettierrc
src/app/features/test-records/components/base-test-record/base-test-record.component.html
src/app/features/test-records/components/base-test-record/base-test-record.component.ts
src/app/features/test-records/views/amended-test-record/amended-test-record.component.html
src/app/features/test-records/views/amended-test-record/amended-test-record.component.spec.ts
src/app/features/test-records/views/amended-test-record/amended-test-record.component.ts
src/app/features/test-records/views/test-record/test-record.component.html
src/app/features/test-records/views/test-record/test-record.component.spec.ts
src/app/features/test-records/views/test-record/test-record.component.ts
src/app/forms/components/defect/defect.component.html
src/app/forms/components/defect/defect.component.spec.ts
src/app/forms/components/defect/defect.component.ts
src/app/forms/components/defects/defects.component.html
src/app/forms/components/defects/defects.component.spec.ts
src/app/forms/components/defects/defects.component.ts
src/app/forms/dynamic-forms.module.ts
src/app/services/test-records/test-records.service.spec.ts
src/app/services/test-records/test-records.service.ts
tslint.json

Include the defects form data when pressing submit on the test record editing form.
Simplify and normalize the defects HTML template.
[CB2-4692](https://dvsa.atlassian.net/browse/CB2-4692)

feature(CB2-4692): Extract Defects Data on Submission

---

src/app/features/test-records/views/test-record/test-record.component.ts
src/app/forms/components/base-control/base-control.component.ts
src/app/forms/components/field-error-message/field-error-message.component.ts
src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.service.spec.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/test-records/section-templates/notes/notes-section.template.ts
src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-vehicle-section.template.ts
src/app/forms/utils/error-message-map.spec.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-validators.spec.ts
src/app/forms/validators/custom-validators.ts

- Fix the static functions that validate forms and return errors.
- Cleanup code using enums and strong typing.
_When submitting test result changes, not all validation messages are being displayed in error summary._
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4803)

fix(cb2-4803): incomplete error summary

---

.github/workflows/pr-checks.yml
.husky/pre-commit
.husky/pre-push

Adds a GitHub Action quality gate on Push and Pull Requests to:
- Build
- Run the unit tests
- Run the linter
This also removes the same steps from the husky pre-commit and pre-push hooks, leaving only the `git secrets` check running locally.
The benefit of this PR is reduced friction for the VTM development team, without a loss of quality for code merged into the `develop` branch.

chore(*): adds pull-request checks

---

.github/workflows/pr-checks.yml

fix(*): pr-checks

---

src/app/features/test-records/components/base-test-record/base-test-record.component.html
src/app/features/test-records/components/base-test-record/base-test-record.component.ts
src/app/forms/components/defect/defect.component.html
src/app/forms/components/defect/defect.component.spec.ts
src/app/forms/components/defect/defect.component.ts
src/app/forms/components/defects/defects.component.html
src/app/forms/components/defects/defects.component.spec.ts
src/app/forms/components/defects/defects.component.ts
src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/general/defect.template.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-validators.ts
src/app/forms/validators/defects/defect.validators.spec.ts
src/app/forms/validators/defects/defect.validators.ts
src/mocks/mock-defects.ts

_This story covers functionality that will allow the user to change a defect for a test record and test type that uses defects taxonomy and changes needed in following Defects section fields only: Location/ Prohibition Issued/ Additional Defects Details_
[CB2-4222](https://dvsa.atlassian.net/browse/CB2-4222)

feat(cb2-4224): amend defects

---

src/app/guards/roles.guard.spec.ts
src/app/guards/roles.guard.ts
src/app/services/user-service/user-service.ts

Repair the role guard to fix bug when token refreshes.

Role Guard Fix

---

src/app/forms/templates/test-records/master.template.ts

add custome defect templates to group 1 and 2.
needed because they are required in api call.

fix(cb2-3949): templates

---

src/app/forms/components/defect/defect.component.html

_PRS and prohibition issued fields are bound together because they have the same id_
[CB2-4611](https://dvsa.atlassian.net/browse/CB2-4611)

fix(cb2-4611): amend result of the test

---

src/app/forms/components/base-control/base-control.component.ts
src/app/forms/components/defect/defect.component.html
src/app/forms/models/async-validators.enum.ts
src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.service.spec.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/services/dynamic-form.types.spec.ts
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/general/defect.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-async-validators.spec.ts
src/app/forms/validators/custom-async-validators.ts
src/app/forms/validators/custom-validators.ts

- Update the dynamic forms service to support async validators.
- Validate the result of specialist tests against their custom defects.
Big thanks to @mcadenas-bjss for cracking the problem of handling async validators.
[CB2-4202](https://dvsa.atlassian.net/browse/CB2-4202)

feat(cb2-4202): amend test result for specialist tests

---

src/app/store/defects/reducers/defects.reducer.spec.ts
src/app/store/defects/reducers/defects.reducer.ts

[CB2-4229](https://dvsa.atlassian.net/browse/CB2-4229)

fix(CB2-4229): Bugfix for when 2 Defects Share the Same IM Number

---

src/app/forms/models/async-validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/services/dynamic-form.types.ts
src/app/forms/services/multi-options.service.ts
src/app/forms/templates/test-records/section-templates/visit/visit-section.template.ts
src/app/forms/validators/custom-async-validators.spec.ts
src/app/forms/validators/custom-async-validators.ts
src/app/services/test-stations/test-stations.service.ts
src/app/store/test-records/reducers/test-records.reducer.spec.ts
src/app/store/test-records/reducers/test-records.reducer.ts
src/app/store/test-stations/actions/test-stations.actions.spec.ts
src/app/store/test-stations/actions/test-stations.actions.ts
src/app/store/test-stations/selectors/test-stations.selectors.spec.ts
src/app/store/test-stations/selectors/test-stations.selectors.ts

_Test station type does not update on selection_
[CB2-5499](https://dvsa.atlassian.net/browse/CB2-5499)

fix(cb2-5499): update test station details

---

src/app/forms/components/autocomplete/autocomplete.component.ts

Fix dropdown issue for Country of Registration
[https://dvsa.atlassian.net/browse/CB2-5506]

fix(CB2-5506)-Fix-dropdown-issue

---

src/app/forms/templates/test-records/master.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/groups11and13-trl-vehicle-section.template.ts

[CB2-4380](https://dvsa.atlassian.net/browse/CB2-4380)

feature(CB2-4380): Update the Test Results Fields for TRL Groups 11 and 13

---

src/app/features/search/single-search-result/single-search-result.component.html
src/app/features/search/single-search-result/single-search-result.component.ts
src/app/forms/templates/search/single-search-result.template.ts

[CB2-5310](https://dvsa.atlassian.net/browse/CB2-5310)

fix(cb2-5310): Add the Trailer ID to the Search Results

---

src/app/forms/components/date/date.component.ts
src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts

Remove time fields from seat belt installation date
[https://dvsa.atlassian.net/browse/CB2-5728]()

Fix(cb2 5728) fix seat belt installation date

---

src/app/forms/templates/test-records/create-master.template.ts

[CB2-5732](https://dvsa.atlassian.net/browse/CB2-5732)

feature(cb2-5732): add the creation template for group 2

---

src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts

Remove PRS option on test result selector for LEC (test type groups 15 and 16)
[https://dvsa.atlassian.net/browse/CB2-4379]

fix(cb2-4379): remove PRS for LEC tests

---

src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts

_seatbelt installation check date must be in past_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5728)

fix(cb2-5728): seatbelt installation check must be in past

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
src/app/models/roles.enum.ts

Add in the new tech-record amend role and hide the edit button
[https://dvsa.atlassian.net/browse/CB2-5898](5898)

feat(cb2-5898): add new tech role

---

src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts

PR to fix breaking change on submit button logic. [https://github.com/dvsa/cvs-app-vtm/commit/ee6de1a0d9d36c4c55200a551028fd8387f34ac9](url)

fix(cb2-4536): re-add submit logic

---

src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

test(cb2-5882): add in effect tests

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/required/contingency-required-hidden-section-hgv-trl.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group10.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group9And10.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
src/app/resolvers/contingency-test/contingency-test.resolver.ts

Trailer Group 10 Contingency Tests
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5808)

feat(cb2-5808): allowing creation of contingency tests for trailers

---

src/app/app.component.html
src/app/app.component.scss
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/core/components/spinner/spinner.component.html
src/app/core/components/spinner/spinner.component.spec.ts
src/app/core/components/spinner/spinner.component.ts
src/app/features/tech-record/tech-record.component.html
src/app/features/tech-record/tech-record.component.spec.ts
src/app/features/tech-record/tech-record.component.ts
src/app/services/loading/loading.service.spec.ts
src/app/services/loading/loading.service.ts

_When loading screen is shown, the background content is scrollable and visible. Fix by prevent scrolling while loading._

fix(*): loading overlay

---

src/app/app-routing.module.ts
src/app/core/components/page-not-found/page-not-found.component.html
src/app/core/components/page-not-found/page-not-found.component.spec.ts
src/app/core/components/page-not-found/page-not-found.component.ts
src/app/core/core.module.ts
src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
src/app/features/tech-record/tech-record-routing.module.ts
src/app/features/tech-record/tech-record.module.ts
src/app/features/test-records/create/create-test-records-routing.module.ts

_Handle unknown routes with redirects and "Page not found" view._

fix(*): handle unknown routes

---

src/app/app.component.spec.ts
src/app/core/components/breadcrumbs/breadcrumbs.component.spec.ts
src/app/core/components/global-error/global-error.service.spec.ts
src/app/directives/app-role-required.directive.spec.ts
src/app/directives/app-role-required.directive.ts
src/app/features/search/search.component.html
src/app/features/search/search.component.spec.ts
src/app/features/search/search.component.ts
src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
src/app/features/tech-record/tech-record.component.html
src/app/features/tech-record/tech-record.component.spec.ts
src/app/features/tech-record/tech-record.component.ts
src/app/features/tech-record/tech-record.module.ts
src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
src/app/forms/components/date/date.component.spec.ts
src/app/forms/components/defects/defects.component.spec.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts
src/mocks/trl-record.mock.ts

Attain 100% test coverage (statements, branches, functions & lines) for the following files:
1. app.component.ts
2. breadcrumbs.components.ts
3. global-error.service.ts
4. app-role-required.directive.ts
5. search.component.ts
6. tech-record.component.ts
7. edit-tech-record-button.component.ts
8. tech-record-summary.component.ts
9. vehicle-technical-record.component.ts
[CB2-6125](https://dvsa.atlassian.net/browse/CB2-6125)

test(CB2-6125): improve VTM test coverage

---

src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group9And10.template.ts

Contingency tests in group 10
Removed anniversary date from contingency test group 10 as it cannot be sent
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5808)

feat(cb2-5808): removed anniversary date from contingency

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/psv/psv-notes.template.ts

Amend notes for HGV & TRL
Reverted generic notes section changes so we can keep to Json driven templates, this would help if we served these over an API some day.

CB2-5709: Amend notes for HGV & TRL

---

src/app/accessible-autocomplete.d.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/forms/components/autocomplete/autocomplete.component.html
src/app/forms/components/autocomplete/autocomplete.component.scss
src/app/forms/components/autocomplete/autocomplete.component.ts
src/app/forms/templates/general/document-types.ts
src/app/forms/templates/general/documents.template.ts
src/styles.scss

Amend documents for all technical records.
Added the service design for dropdown to have the minimal arrow, this will be reflected on test teams also.
I do wonder about the interface FormNodeOptions takes, since the 2 examples ive found for it just duplicate the string twice, would it be better to just be a string array ?

CB2-5686: Amend documents section for technical records

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-vehicle-section.template.ts
src/app/store/test-records/effects/test-records.effects.spec.ts

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5811)

feat/cb2-5811: contingency-group-9

---

src/app/forms/components/dimensions/dimensions.component.ts
src/app/forms/templates/general/dimensions.template.ts
src/app/forms/utils/error-message-map.ts

[CB2-6237](https://dvsa.atlassian.net/browse/CB2-6237)

fix(cb2-6237): add validation to tech summary dimensions

---

src/app/features/tech-record/components/tech-record-history/tech-record-history.component.spec.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
src/app/forms/components/autocomplete/autocomplete.component.html
src/app/forms/components/base-control/base-control.component.ts
src/app/forms/components/brakes/brakes.component.html
src/app/forms/components/brakes/brakes.component.scss
src/app/forms/components/brakes/brakes.component.spec.ts
src/app/forms/components/brakes/brakes.component.ts
src/app/forms/components/number-input-with-suffix/number-input-with-suffix.component.ts
src/app/forms/components/number-input/number-input.component.html
src/app/forms/components/number-input/number-input.component.ts
src/app/forms/components/radio-group/radio-group.component.html
src/app/forms/components/radio-group/radio-group.component.ts
src/app/forms/components/text-input/text-input.component.html
src/app/forms/components/text-input/text-input.component.ts
src/app/forms/dynamic-forms.module.ts
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/psv/psv-brake.template.ts
src/app/forms/templates/trl/trl-brakes.template.ts
src/app/forms/templates/trl/trl-manufacturer.template.ts
src/app/models/vehicle-tech-record.model.ts
src/app/shared/components/pagination/pagination.component.ts

[CB2-5701](https://dvsa.atlassian.net/browse/CB2-5701)

feature(CB2-5701): Create the TRL Brakes Component

---

src/app/shared/components/pagination/pagination.component.ts

_Nicer way of calculating the list of visible pages on the pagination component. Credit to @tom-bjss and @leifkemp-bjss_

Simplify calculation of pagination visible pages

---

src/app/forms/components/defect/defect.component.html
src/app/forms/components/defect/defect.component.ts

_Apply service design changes to the screens which feature in the amend test record flow_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5725)

fix(cb2-5725): fixed removing defect

---

src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group3And4And8.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts

_As per comment on PR, PRS has been removed_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3798)

fix(cb2-3798): removed PRS from template

---

src/app/features/test-records/components/base-test-record/base-test-record.component.html
src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts

_By default caption for collapsable option should be Hide all sections instead of Show all section_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6250)

fix(cb2-6250): fixed collapsible sections

---

src/app/forms/models/testTypeId.enum.ts

This was missing from group 10, this PR is to put it back in for contingency tests which doesn't require any backend validation changes as far as I can see.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6203)

feat(cb2-6203): added contingency support for free loaded trl test

---

src/app/forms/components/defect/defect.component.html

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6267)

fix(cb2-6267): changed prohibition issued to radio buttons

---

src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group5.template.ts

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5779)

fix(cb2-5779): removed unused validators

---

src/app/forms/components/defect-select/defect-select.component.ts
src/app/forms/components/defects/defects.component.spec.ts
src/app/forms/components/defects/defects.component.ts
src/app/store/defects/selectors/defects.selectors.ts

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6266)

fix(cb2-6266): removed redundant code and fixed advisory defects

---

src/app/forms/templates/trl/trl-purchaser.template.ts

Added character length validation to trl - purchase
[https://dvsa.atlassian.net/browse/CB2-5707](  cb2-5707)

feat(cb2-5707): added trl purchase validation

---

src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
src/app/features/tech-record/components/test-record-summary/test-record-summary.stories.ts

Change to the technical record view to sort tests chronologically
[CB2-5880](https://dvsa.atlassian.net/browse/CB2-5880)

feat(cb2-5880): sorting tests chronologically

---

src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group2.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group4.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group5.template.ts

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6208)

feat(cb2-6208): amend start and end time

---

src/app/forms/components/date/date.component.html
src/app/forms/components/date/date.component.spec.ts
src/app/forms/components/date/date.component.ts
src/app/forms/components/date/focus-next.directive.spec.ts
src/app/forms/components/date/focus-next.directive.ts
src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/trl/trl-auth-into-service.template.ts
src/app/forms/validators/date/date.validators.spec.ts
src/app/forms/validators/date/date.validators.ts
src/app/models/vehicle-tech-record.model.ts
src/app/services/technical-record/technical-record.service.ts

Add the edit view type of dates. Add processing to pass back end validation
[https://dvsa.atlassian.net/browse/CB2-5706](5706)

feat(cb2-5706): add date type to edit and process format

---

src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts

Test records now display differing headers based on vehicle type.
[CB2-5881](https://dvsa.atlassian.net/browse/CB2-5881)

feat(cb2-5881): modify vehicle details header

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group5.template.ts

Added contingency testing for specialist group 5 (test type IDs 153 and 184)
[CB2-6215](https://dvsa.atlassian.net/browse/CB2-6215)

feat(cb2-6215): added contingency test for spec group 5

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts

Added contingency tests for specialist group 1
[CB2-4817](https://dvsa.atlassian.net/browse/CB2-4817)

feat(cb2-4817): added contingency tests for specialist group 1

---

src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
src/app/forms/components/select/select.component.html
src/app/forms/components/select/select.component.scss
src/app/forms/components/select/select.component.ts
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/general/approval-type.template.ts
src/app/forms/utils/enum-map.ts

Added select to dynamic form, reusable enum map to utils, added validators to type approval and removed gov style override. 
https://dvsa.atlassian.net/browse/CB2-5703

feat(CB2-5703): Amend HGV & TRL Type Approval section

---

src/app/features/test-records/components/base-test-record/base-test-record.component.html
src/app/features/test-records/components/base-test-record/base-test-record.component.ts
src/app/forms/models/async-validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-async-validators.spec.ts
src/app/forms/validators/custom-async-validators.ts

Hide Emissions fields / certificate fields based on test result
[CB2-6092](https://dvsa.atlassian.net/browse/CB2-6092)

feat(cb2-6092): hide emissions section

---

src/app/forms/templates/general/manufacturer.template.ts

Currently unable to amend telephone number of manufacturer details section due to typo in field mapping.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6342)

fix(cb2-6342): change manufacturer telephone typo

---

src/app/forms/components/defect-select/defect-select.component.html
src/app/forms/custom-sections/defect/defect.component.html
src/app/forms/custom-sections/defect/defect.component.ts
src/app/forms/custom-sections/defects/defects.component.html

_Modify the defect taxonomy to include an Asterix next to each dangerous defect which does not require the VSA to issue a prohibition_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6303)

feat(cb2-6303): update dangerous defect taxonomy

---

src/app/forms/validators/custom-validators.ts

_Record a TRL contingency test - HGV/TRL test for Paid TIR, ADR, Roadworthiness, Voluntary & Not Alts_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5814)

fix(cb2-5814): fixed validation issue

---

src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group12and14.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group15and16.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group3And4And8.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group5And13.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group6And11.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group7.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group9And10.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group5.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group2.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group3.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group4.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group5.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
src/app/forms/utils/error-message-map.spec.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-validators.spec.ts
src/app/forms/validators/custom-validators.ts

Test start and end dates are now compared to ensure end date is not behind start date
[CB2-6390](https://dvsa.atlassian.net/browse/CB2-6390)

feat(cb2-6390): start/end date validation

---

src/app/forms/templates/test-records/section-templates/customDefects/custom-defects-section.template.ts

_adding validation_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4228)

fix(cb2-4228): added validation

---

src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts

Update to contingency test group to add certificate number and have it check if it's alphanumeric
[CB2-4817](https://dvsa.atlassian.net/browse/CB2-4817)

feat(cb2-4817): added certificate number field to test record

---

src/app/forms/utils/error-message-map.spec.ts
src/app/forms/utils/error-message-map.ts

And also removed displayArray() as it is unused

test(*): add tests for error messages

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group2.template.ts

_Added support for creation of test types 142, 146, 175, 177_
[CB2-6212](https://dvsa.atlassian.net/browse/CB2-6212)

feat(CB2-6212): Contingency Test Specialist Group 2

---

src/app/resolvers/contingency-test/contingency-test.resolver.ts

fix(cb2-6200): initialize additional comment for abandonning to null

---

src/app/shared/components/pagination/pagination.component.spec.ts
src/app/shared/components/pagination/pagination.component.ts

Fix visible page calculation

---

src/app/forms/templates/trl/trl-purchaser.template.ts

Email address allowed characters length is 255 character not 225 characters - Purchaser section tech record
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6448)](6448)

fix(cb2-6448): fix char length on validation of email

---

src/app/forms/custom-sections/dimensions/dimensions.component.html
src/app/forms/custom-sections/dimensions/dimensions.component.scss
src/app/forms/templates/general/dimensions.template.ts

- Update the dimensions component to display the min and max fields for HGVs and TRLs.
[CB2-5702](https://dvsa.atlassian.net/browse/CB2-5702)

feat(cb2-5702): extend dimensions to cater for hgvs and trls

---

src/app/forms/templates/test-records/master.template.ts

_This ticket is to increase this scope to supporting to all test types for amending HGV/TRL Specialist Test Types within Group 1 (Test Type IDs 186, 188, 130, 192, 194, 163)_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5817)

feat(cb2-5817): added group 1 amend

---

src/app/app.module.ts

An attempted fix, ive tested this out overnight and it seemed to refresh my auth token alright and the jwt has the correct audience now

fix(cb2-1111): fix on auth refresh token expiring

---

src/app/features/tech-record/components/tech-amend-reason/tech-amend-reason.component.ts
src/app/features/tech-record/tech-record-routing.module.ts
src/app/models/vehicle-tech-record.model.ts

added default value to radio group to reflect new enum as this was based on magic numbers before, this will stop users from being able to press continue without a valid reason selected

fix(cb2-6062): added default selection to radio group

---

src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts

Amend HGV & TRL Vehicle Summary section
Updating hgv and trl template 
[Jira ticket](https://dvsa.atlassian.net/browse/CB2-6248)

feat(cb2-6248): amend hgv & trl vehicle summary section

---

src/app/forms/templates/general/dimensions.template.ts

- Correct one of the group names within the dimensions template.
- Add the missing `required` validators to necessary fields.
[CB2-5702](https://dvsa.atlassian.net/browse/CB2-5702)

fix(cb2-5702): add the missing validators to the dimensions section

---

src/app/forms/services/dynamic-form.types.ts

fixed patch value attempting to read null/undefined values

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group15and16.template.ts

Adds support for a contingency version of an LEC test to be written for a PSV. This is group 15. It does not add the correct test code currently as that will be done in a future ticket.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5510)

feat/cb2-5510: contingency group 15

---

src/app/features/test-records/amend/views/test-record/test-record.component.html
src/app/features/test-records/amend/views/test-record/test-record.component.ts
src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.html
src/app/forms/custom-sections/defect/defect.component.html
src/app/forms/custom-sections/defects/defects.component.html
src/app/shared/components/button/button.component.scss

_This ticket is to add a Cancel button to the test record amendment screen and ensure that it is clear to the user that their changes will be lost when they use this option._
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5857)

feat(cb2-5857): added back button

---

src/app/forms/templates/test-records/section-templates/visit/visit-section.template.ts

[https://dvsa.atlassian.net/browse/CB2-5114]

feat(CB2-5114)-Amend-visit-section

---

src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
src/app/shared/pipes/digit-group-separator/digit-group-separator.pipe.spec.ts
src/app/shared/pipes/digit-group-separator/digit-group-separator.pipe.ts
src/app/shared/shared.module.ts

_Odometer reading should have “ , “ for big number such as 350,000 Km_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3782)

feat(cb2-3782): comma delimited formatting

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/core/components/server-error/server-error.component.html
src/app/core/components/server-error/server-error.component.spec.ts
src/app/core/components/server-error/server-error.component.ts
src/app/core/core.module.ts
src/app/interceptors/error-handling/error-handling.interceptor.spec.ts
src/app/interceptors/error-handling/error-handling.interceptor.ts
src/app/interceptors/error-handling/error-handling.module.ts
src/app/interceptors/interceptor.module.ts
src/app/store/test-records/effects/test-records.effects.ts

This is a ticket to display an error message for a 502 error on an amend/contingency rather than a blank page. The work has also been done to account for 500 errors taking you to an error page to inform the user to contact support.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5614)

feat(cb2-5614): handle 500 failures

---

src/app/forms/components/read-only/read-only.component.html
src/app/forms/components/read-only/read-only.component.ts
src/app/forms/components/switchable-input/switchable-input.component.html

Non edit doesn't have the suffix and it should

chore(*): add suffix to non edit modes

---

src/app/forms/custom-sections/body/body.component.html

fix(): typo in body component html

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/custom-sections/tyres/tyres.component.ts

fix(*): fix the add and remove axles

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts

Notes section isn't shown on Current & Provisional
[https://dvsa.atlassian.net/browse/CB2-6613](6613)

fix(cb2-6613): fix the notes section not displaying

---

src/app/features/test-records/amend/views/test-record/test-record.component.html
src/app/forms/custom-sections/custom-defect/custom-defect.component.html
src/app/forms/custom-sections/custom-defects/custom-defects.component.html

fix custom defects

---

src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
src/app/features/tech-record/tech-record-routing.module.ts
src/app/features/test-records/components/base-test-record/base-test-record.component.spec.ts
src/app/features/test-records/create/create-test-records-routing.module.ts
src/app/models/roles.enum.ts

Adds granular permission for creating contingency test results: `TestResult.CreateContingency`
https://dvsa.atlassian.net/browse/CB2-6625

feat(cb2-6625): adds TestResult.CreateContingency permission

---

package-lock.json
package.json

Bumps the app/package version number ahead of release

bumps VTM version number to 1.2.0 for release

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
src/app/forms/templates/psv/psv-brakes.template.ts
src/app/models/vehicle-tech-record.model.ts

Fix brake code not being updated correctly
[https://dvsa.atlassian.net/browse/CB2-6652](6652)

fix(cb2-6652): Fix brake code not being updated correctly

---

src/app/forms/models/testTypeId.enum.ts

Add testTypeId 201 to group 15 for PSV LEC tests
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6502)

feat(cb2-6502): psv lec contingency test without linked

---

src/app/forms/components/select/select.component.scss
src/app/forms/templates/general/plates.template.ts

- Correct the applying of custom width on the select component.
- Update the plates template for TRLs and HGVs.
[CB2-5710](https://dvsa.atlassian.net/browse/CB2-5710)

feat(cb2-5710): update the plates section to the clients standard

---

src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
src/app/forms/components/dynamic-form-group/dynamic-form-group.component.scss
src/app/forms/components/view-combination/view-combination.component.html
src/app/forms/components/view-combination/view-combination.component.ts

_Each detail list section should consist of one `<dl/>` with multiple rows. This fix does that and fixes line styles between rows._

task(*): fix html sematic meaning for detail lists

---

src/app/features/test-records/amend/views/test-record/test-record.component.html
src/app/features/test-records/create/views/create-test-record/create-test-record.component.html

Remove 'Review and' from the Submit Test Result button
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6753)

feat(cb2-6753): removed review and from submission buttons

---

.github/workflows/ci.yml

_Add Snyk to VTM_
[CB2-6718]()

feat(cb2-6718): added snyk

---

src/app/features/tech-record/components/tech-promote/tech-promote.component.html
src/app/features/tech-record/components/tech-promote/tech-promote.component.ts

- Turns out that the reason for promotion is mandatory on the back end. This makes it required on the UI too.
[CB2-6669](https://dvsa.atlassian.net/browse/CB2-6669)

fix(cb2-6669): make the reason for promotion required

---

.husky/pre-commit

- Pass local prettier config file to command so it always formats with the same rules.
- Ignore src/app/api files in the format so it doesn't fomat generated code.

chore(cb2-0000): update pre-commit hook

---

src/app/forms/templates/test-records/create-master.template.ts

Remove seatbelt section to match AC
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6502)

feat(cb2-6502): contingency test lec psv

---

src/app/features/test-records/amend/views/test-record/test-record.component.html
src/app/features/test-records/create/views/create-test-record/create-test-record.component.html

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6757)

feat(cb2-6757): changed name of button to be in line with gds guidance

---

src/app/features/tech-record/components/tech-promote/tech-promote.component.spec.ts
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
src/app/features/tech-record/tech-record-routing.module.ts
src/app/models/roles.enum.ts

Add new role guards and permissions for archiving to the front end.
[https://dvsa.atlassian.net/browse/CB2-6764](6764)

feat(cb2-6764): add role guards to new permission

---

src/app/forms/templates/trl/trl-tech-record.template.ts

- Update the suspension type field for TRLs to be a dropdown.
[CB2-6684](https://dvsa.atlassian.net/browse/CB2-6684)

feature(cb2-6684): update the trl suspension type to a dropdown

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
src/app/features/tech-record/tech-record-routing.module.ts

 Fix provisional archive

---

src/app/forms/custom-sections/tyres/tyres.component.ts
src/app/forms/custom-sections/weights/weights.component.ts

Add in trailer logic and fix error messages
[https://dvsa.atlassian.net/browse/CB2-6829](6829)

fix(cb2-6829): fix error messages and logic for trailer axles

---

src/app/forms/models/testTypeId.enum.ts
src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.types.ts
src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
src/app/forms/validators/custom-validators.ts

Implements the template for the desk based testing for a PSV Group 1
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6731)

feat(cb2-6731): desk based testing template 1

---

src/app/forms/models/testTypeId.enum.ts
src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group4.template.ts
src/app/forms/templates/test-records/section-templates/visit/contingency-visit-section.template.ts

[https://dvsa.atlassian.net/browse/CB2-6547](6547)

Feat(cb2-6547): create a psv desk based Test Group 4

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/custom-sections/dimensions/dimensions.component.html
src/app/forms/custom-sections/dimensions/dimensions.component.ts
src/app/models/vehicle-tech-record.model.ts
src/mocks/hgv-record.mock.ts

The axle spacing now updates dynamically when you add and remove axles
[https://dvsa.atlassian.net/browse/CB2-6770](6770)

Feat(cb2-6770): vary axle spacing dynamically

---

src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group2-PSV.template.ts

Create a PSV desk based Test Group 2 - fix
"Desk based tests can only pass"
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6545)

Create a PSV desk based Test Group 2 -fix

---

src/app/directives/app-role-required.directive.spec.ts
src/app/directives/app-role-required.directive.ts
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
src/app/models/roles.enum.ts
src/app/store/test-types/effects/test-types.effects.ts

Small refactor to allow multiple roles access to components. This is in conjunction with the authoriser PR:  
https://github.com/dvsa/cvs-svc-authoriser/pull/60

refactor(cb2-6727): refactored role directive to take array or single

---

src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group4.template.ts

fix(cb2-6547): set test result to pass

---

.vscode/launch.json
.vscode/tasks.json
README.md

Add vscode debug configuration for local debugging.

Local debugging

---

src/app/forms/templates/test-records/master.template.ts

Amend PSV desk based test group 2
Can amend tests 403 and 404
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6532)

feat(CB2-6532): Amend PSV desk based test group 2

---

src/app/forms/models/testTypeId.enum.ts
src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/reasonForCreation/reasonForCreation.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group4Hgv.template.ts

_Ability to record a HGV/TRL desk based tests - Groups 4_
[CB2-6550](https://dvsa.atlassian.net/browse/CB2-6550)

feat(cb2-6550): new template yay

---

src/app/forms/templates/test-records/master.template.ts

Amend PSV Desk Based Tests Group 2
used alt visit and req template
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6532)

feat(CB2-6532): Amend PSV Desk Based Tests Group 2

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1And3-HGV-TRL.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts

_Ability to record a HGV/TRL desk based tests - Groups 3_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6549)

feat(cb2-6549): desk based group 3 hgv trl

---

src/app/features/test-records/create/views/create-test-record/create-test-record.component.html
src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1-PSV.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1And3-HGV-TRL.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3-PSV.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-HGV-TRL.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-PSV.template.ts
src/app/store/test-types/selectors/test-types.selectors.ts

fix(cb2-6545): fix validation errors

---

src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3-PSV.template.ts

[https://dvsa.atlassian.net/browse/CB2-6931](6931)

fix(cb2-6546): add required validator to field

---

src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts

[CB2-6918](https://dvsa.atlassian.net/browse/CB2-6918)

fix(cb2-6918): clear errors on review page

---

src/app/forms/templates/test-records/master.template.ts
src/app/forms/templates/test-records/section-templates/reasonForCreation/reasonForCreation.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-PSV.template.ts

_This ticket is to increase this scope to support all test types for amending PSV Desk Based Test Types within Group 4_
[CB2-6534](https://dvsa.atlassian.net/browse/CB2-6534)

feat(cb2-6534): amend dba psv group 4

---

src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3-HGV-TRL.template.ts

_Make certificate number mandatory for desk based group 3 HGV & TRL_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6550)

feat(cb2-6550): make certificate number mandatory for desk based group 3 HGV & TRL

---

src/app/forms/models/testTypeId.enum.ts

Move into different test types to enable filtering on the front end
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6550)
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6955)

fix(cb2-6955): add different test type

---

src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
src/app/forms/models/testTypeId.enum.ts
src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/master.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1And4-HGV-TRL.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3-HGV-TRL.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-PSV.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
src/app/store/test-records/effects/test-records.effects.spec.ts
src/app/store/test-records/effects/test-records.effects.ts

merge develop into VTMDEV-1

---

src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
src/app/forms/templates/test-records/master.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1-PSV.template.ts
src/app/forms/utils/error-message-map.spec.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-validators.spec.ts
src/app/forms/validators/custom-validators.ts

To enable the amendment of PSV Desk Based Test Types within Group 1
[CB2-6531](https://dvsa.atlassian.net/browse/CB2-6531)
Original test:
Amended test:

CB2-6531: Amend PSV Desk Based Tests Group 1

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/master.template.ts
src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-section-hgv-trl.template.ts
src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-section-psv.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts

- Amend Group 2 DBA for HGV and TRL
- Adds new required section template for DBA amends (where secondaryCertificateNumber isn't always required). 
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6536)

feat(cb2-6536): amend hgv/trl dba group 2

---

src/app/forms/templates/test-records/master.template.ts

Amend PSV Desk Based Tests Group 2
Validated submits. (This was the first amend, I submitted it before we scrapped seatbelts in dba's)
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6532)

feat(cb2-5301): Amend PSV Desk Based Tests Group 2

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/components/switchable-input/switchable-input.component.html
src/app/forms/components/switchable-input/switchable-input.component.ts
src/app/forms/custom-sections/body/body.component.html
src/app/forms/custom-sections/body/body.component.spec.ts
src/app/forms/custom-sections/body/body.component.ts
src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
src/app/forms/templates/general/hgv-trl-body.template.ts
src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/psv/psv-body.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts
src/app/services/reference-data/reference-data.service.ts
src/app/services/test-stations/test-stations.service.ts
src/app/store/reference-data/selectors/reference-data.selectors.ts

PSV body functionality not working as intended
refactor and debug tech record component
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6976)

fix(cb2-6976): PSV body functionality not working as intended

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.html
src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.scss
src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.spec.ts
src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.scss
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
src/app/features/tech-record/components/tyres-search/tyres-search.component.spec.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
src/app/features/tech-record/tech-record-routing.module.ts
src/app/features/tech-record/tech-record.module.ts
src/app/features/test-records/create/views/create-test-type/create-test-type.component.spec.ts
src/app/features/test-records/create/views/create-test-type/create-test-type.component.ts
src/app/models/vehicle-tech-record.model.ts
src/mocks/psv-record.mock.ts

- Add a new flag called `hiddenInVta`
- Display this flag in the tech record title bar
- Implement a workflow to toggle this new flag
- Fix bugs related to disabling test creation on skeleton records
- Fix unit test files for
- `edit-tech-record-button`
- `tyres-search`
These new changes are a result of discussions with the design team, Dan, Andrew & Bruce.
[CB2-6869](https://dvsa.atlassian.net/browse/CB2-6869)
[CB2-6886](https://dvsa.atlassian.net/browse/CB2-6886)
[CB2-7101](https://dvsa.atlassian.net/browse/CB2-7101)

refactor(cb2-7101): do not display the record completeness flag for archived tech records

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts

Verify and address issues raised on https://dvsa.atlassian.net/browse/CB2-6640
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7112)

fix(cb2-7112): Verify and address issues raised on https://dvsa.atlassian.net/browse/CB2-6640

---

src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
src/app/features/tech-record/components/tech-router-outlet/tech-router-outlet.component.html
src/app/features/tech-record/components/tech-router-outlet/tech-router-outlet.component.ts
src/app/features/tech-record/tech-record-routing.module.ts
src/app/features/tech-record/tech-record.module.ts

[CB2-7151](https://dvsa.atlassian.net/browse/CB2-7151)

refactor(cb2-7151): simplify tech routing

---

src/app/forms/templates/psv/psv-dimensions.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/psv/psv-tyres.template.ts
src/app/forms/templates/psv/psv-weight.template.ts

Updated record must submit to database passing all validation checks
UI validations to ask for user input on vehicle type change
[Link](https://dvsa.atlassian.net/browse/CB2-7158)

fix(cb2-7158): Update validations to align with api expectations

---

package-lock.json
package.json

Bumps the version in `package*.json` to v1.3 ahead of the next planned release

chore(cb2-0000): bump vtm version to 1.3 ahead of release

---

package.json

A change was made to the test command, it seems that change may have affected the pipeline, as it is timing out on the tests. Reverting the change.

fix(cb2-5718): revert change to test script

---

src/app/forms/templates/car/car-tech-record.template.ts
src/app/forms/templates/general/approval-type.template.ts
src/app/forms/templates/general/audit.template.ts
src/app/forms/templates/general/hgv-trl-body.template.ts
src/app/forms/templates/general/manufacturer.template.ts
src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/hgv/hgv-tyres.template.ts
src/app/forms/templates/hgv/hgv-weight.template.ts
src/app/forms/templates/lgv/lgv-tech-record.template.ts
src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
src/app/forms/templates/psv/psv-approval-type.template.ts
src/app/forms/templates/psv/psv-body.template.ts
src/app/forms/templates/psv/psv-brakes.template.ts
src/app/forms/templates/psv/psv-dda.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/psv/psv-tyres.template.ts
src/app/forms/templates/psv/psv-weight.template.ts
src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
src/app/forms/templates/trl/trl-brakes.template.ts
src/app/forms/templates/trl/trl-dimensions.template.ts
src/app/forms/templates/trl/trl-purchaser.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts
src/app/forms/templates/trl/trl-tyres.template.ts
src/app/forms/templates/trl/trl-weight.template.ts

feat(cb2-7248): remove all required validation

---

src/app/forms/custom-sections/body/body.component.html

- Update PSV Body section's template to show the text field.
[CB2-6631](https://dvsa.atlassian.net/browse/CB2-6631)

feat(cb2-6631): show the model literal field on the psv body section

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.scss

_Rather than having the action buttons appear as set columns, make them align right._
[CB2-7354](https://dvsa.atlassian.net/browse/CB2-7354)

fix(cb2-7354): tech record header actions

---

src/app/features/create/create.component.ts

Fixed labels not showing for form validators

fix(cb2-7396): added labels for form values

---

src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.html
src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.spec.ts
src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/psv/psv-body.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts

Click on submit new record doesn't show any validation on new record details page
[Link](https://dvsa.atlassian.net/browse/CB2-7398)

fix(cb2-7398): submit new record doesn't show any validation

---

src/app/forms/custom-sections/dimensions/dimensions.component.html
src/app/forms/templates/trl/trl-dimensions.template.ts

Unable to create a Trailer Tech Record due to missing field
[Link](https://dvsa.atlassian.net/browse/CB2-7406)

fix(cb2-7406): Unable to create a Trailer Tech Record due to missing field

---

src/app/features/create/create.component.html
src/app/features/create/create.component.spec.ts
src/app/features/create/create.component.ts

fix(cb2-7407): allow duplicate vins

---

src/app/forms/custom-sections/body/body.component.html
src/app/forms/custom-sections/body/body.component.ts

[CB2-7439](https://dvsa.atlassian.net/browse/CB2-7439)

fix(cb2-7439): filter body types by vehicle type

---

src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.spec.ts
src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
src/app/features/test-records/create/views/create-test-type/create-test-type.component.spec.ts
src/app/forms/custom-sections/body/body.component.ts
src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
src/app/services/reference-data/reference-data.service.spec.ts
src/app/services/reference-data/reference-data.service.ts
src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
src/app/store/reference-data/selectors/reference-data.selectors.ts

test(*): increase unit test coverage

---

src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
src/app/forms/components/switchable-input/switchable-input.component.html

_Revert the use of this new input before release cut as more testing is required._
[CB2-7247](https://dvsa.atlassian.net/browse/CB2-7247)

feat(cb2-7247): revert use of new input for further testing

---

src/app/api/test-types/model/testType.ts
src/app/api/test-types/model/testTypeCategory.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/master.template.ts
src/app/forms/utils/tech-record-constants.ts
src/app/models/vehicle-tech-record.model.ts

[CB2-7397](https://dvsa.atlassian.net/browse/CB2-7397)

feat(cb2-7397): add the small trailer vehicle type

---

src/app/models/body-type-enum.ts

[CB2-397](https://dvsa.atlassian.net/browse/CB2-397)

fix(cb2-9999): correct body type code letter

---

src/app/forms/models/testTypeId.enum.ts
src/app/models/body-type-enum.ts

[CB2-7027](https://dvsa.atlassian.net/browse/CB2-7027)

fix(cb2-7027): add the new test type and correct body type codes

---

src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts

_Amending a current record with correcting an error option got an archived record in tech record history table_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7512)

fix(cb2-7512): fix view tech record history

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/test-records/components/vehicle-header/vehicle-header.component.html

fix(cb2-9876): correct the ngswitch

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts

CB2-7503:
fixes the Tech record title to just show the most recent previous VRM, used Taha's changes for his branch

Fix/cb2 7503 - show only most recent secondary VRM

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts

CB2-7503:
fixes issue with indexing after some changes on another branch

fix(cb2-7503) 

---

package-lock.json
package.json

chore(cb2-0001): bumps vtm version to 1.5.0

---

src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
src/app/store/technical-records/actions/technical-record-service.actions.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts
src/app/store/technical-records/reducers/technical-record-service.reducer.ts

[CB2-7587](https://dvsa.atlassian.net/browse/CB2-7587)

fix(cb2-7587): refresh the tech record after generating new plates

---

src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.html
src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
src/app/services/technical-record/technical-record.service.ts

Changing a Provisional record to Current doesn't update Tech Record properly
clear editing tech record when archive and promote action is success
[Link](https://dvsa.atlassian.net/browse/CB2-7600)

fix(cb2-7600): Changing a Provisional record to Current doesn't update Tech Record properly

---

src/app/forms/models/testTypeId.enum.ts
src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/master.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts

Create a HGV Type Approved Tractor Unit DBA
hgv type approved adriiia
[link](https://dvsa.atlassian.net/browse/CB2-7541)

feat(cb2-7541): Create a HGV Type Approved Tractor Unit DBA

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7614)

fix(cb2-7614): remove validation before submitting

---

src/app/services/technical-record/technical-record.service.ts
src/app/store/technical-records/actions/technical-record-service.actions.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

CB2-7603
Created a service method for amendVin, also created associated action and effect

feat(cb2-7603): amend vin

---

src/app/services/technical-record/technical-record.service.spec.ts
src/app/services/technical-record/technical-record.service.ts
src/app/store/technical-records/actions/technical-record-service.actions.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

CB2-7603:
Added test and removed references to old vin

feat(cb2-7603): removed references to old vin and created test

---

src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7638)

fix(cb2-7638): fix routing when provisional

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
src/app/forms/custom-sections/letters/letters.component.html
src/app/forms/custom-sections/letters/letters.component.ts

CB2-7579: 
small trailers only show the trailer ID (a small trailer is defined by vehicle type trl and an eu vehicle category of o1)

feat(cb2-7579): remove small trailer VRM

---

src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts

CB2-7603:
connects up the UI to the technical record service for amend vin

feat(cb2-7603): Amend VIN 

---

src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.html
src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
src/app/forms/custom-sections/letters/letters.component.html
src/app/forms/custom-sections/plates/plates.component.html
src/app/forms/templates/general/letters.template.ts
src/app/services/technical-record/technical-record.service.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

_PR to allow sending of plates and letters, and adds email addresses to the payloads when generating_
[CB2-6749](https://dvsa.atlassian.net/browse/CB2-6749)

feat(CB2-6749): Sending plates & letters

---

src/app/forms/templates/test-records/section-templates/required/specialist-required-hidden-section-motorcycle.template.ts

_PR to add vehicle configuration to the payload for motorcycle tests when amending_
[CB2-7641](https://dvsa.atlassian.net/browse/CB2-7641)

fix(cb2-7641): add vehicle configuration to motorcycle required template

---

src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.html
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
src/app/services/technical-record/technical-record.service.ts

_PR to fix plate and letter payload not defaulting to user email when amending the applicant email address to be empty_
[CB2-7683](https://dvsa.atlassian.net/browse/CB2-7683)

fix(cb2-7683): fix email not defaulting to user email

---

src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.html
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
src/app/services/technical-record/technical-record.service.ts

The default email check was broken, this fixes it

fix(cb2-7683): fix email issue

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
src/app/features/tech-record/components/tech-record-amend-reason/tech-record-amend-reason.component.spec.ts
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/features/tech-record/create/create-tech-record.component.html
src/app/features/tech-record/create/create-tech-record.component.spec.ts
src/app/features/tech-record/create/create-tech-record.component.ts
src/app/services/technical-record/technical-record.service.spec.ts
src/app/services/technical-record/technical-record.service.ts
src/app/shared/components/test-certificate/test-certificate.component.spec.ts

[CB2-7684](https://dvsa.atlassian.net/browse/CB2-7684)

test(cb2-7684): fix broken unit tests and increase coverage

---

src/app/forms/templates/car/car-tech-record.template.ts
src/app/forms/templates/lgv/lgv-tech-record.template.ts
src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts

[CB2-6641](https://dvsa.atlassian.net/browse/CB2-6641)

fix(cb2-6641): make the no of axles editable and required on small vehicles

---

src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts

[CB2-7731](https://dvsa.atlassian.net/browse/CB2-7731)

fix(cb2-7731): accept only number inputs for no of wheels driven

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/components/checkbox-group/checkbox-group.component.html
src/app/forms/components/checkbox-group/checkbox-group.component.ts

- Use a custom function to handle merging arrays.
- Simplify the `onChanges` method of check box group.
[CB2-7729](https://dvsa.atlassian.net/browse/CB2-7729)

fix(cb2-7729): handle array when merging tech record changes

---

src/app/forms/templates/test-records/section-templates/visit/contingency-visit-section.template.ts

_PR to add test station facility name and P number to the review screen when creating a test_
[CB2-6960](https://dvsa.atlassian.net/browse/CB2-6960)

fix(cb2-6960): add test station details to review test screen

---

src/app/store/test-records/effects/test-records.effects.ts

Wasn't getting tests before 2 years, the API just needs to be told to do it, this does that.
[https://dvsa.atlassian.net/browse/CB2-7653](7653)

feat(cb2-7653): add in from date to payload

---

src/app/forms/validators/defects/defect.validators.ts

Some defects need to be optional in their notes, adjust the validator to let that happen.
[https://dvsa.atlassian.net/browse/CB2-7118](7118)

fix(cb2-7118): make certain defect notes optional

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts

[CB2-7727](https://dvsa.atlassian.net/browse/CB2-7727)

fix(cb2-7727): correct errors on the small trailers template

---

src/app/features/tech-record/create/create-tech-record.component.html
src/app/features/tech-record/create/create-tech-record.component.ts

[CB2-7057](https://dvsa.atlassian.net/browse/CB2-7057)

feat(cb2-7057): add the t numbers text to record creation

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/master.template.ts
src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group4-lgv.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts

_LGV group 5 stuff_
[CB2-7532](https://dvsa.atlassian.net/browse/CB2-7532)

feat(cb2-7532): create  DBA test

---

package-lock.json
package.json
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/forms/custom-sections/body/body.component.html
src/app/forms/custom-sections/body/body.component.spec.ts
src/app/forms/custom-sections/body/body.component.ts
src/app/models/reference-data.model.ts
src/app/store/reference-data/effects/reference-data.effects.spec.ts
src/app/store/reference-data/reducers/reference-data.reducer.ts
src/app/store/reference-data/selectors/reference-data.selectors.spec.ts

[CB2-7795](https://dvsa.atlassian.net/browse/CB2-7795)

feat(cb2-7795): break down bodymake into hgvmake and trlmake

---

src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
src/app/forms/utils/error-message-map.ts
src/app/services/technical-record/technical-record.service.ts

CB2-7162:
Amend a VIN where a duplicate exists,
this is to correct an issue where the validation was triggering the wrong message.

fix(cb2-7162): amend vin validation message

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
src/app/forms/custom-sections/body/body.component.html

[CB2-7795](https://dvsa.atlassian.net/browse/CB2-7795)

feat(cb2-7795): hide null body models and extend the width of body fields

---

src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts

[CB2-7829](https://dvsa.atlassian.net/browse/CB2-7829)

fix(cb2-2001): enable editing test number for adr tests

---

src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
src/app/features/test-records/amend/views/test-record/test-record.component.ts

[CB2-7829](https://dvsa.atlassian.net/browse/CB2-7829)

fix(cb2-7829): navigate to tech record after updating test result

---

src/app/features/test-records/amend/views/test-record/test-record.component.ts
src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
src/app/shared/components/test-certificate/test-certificate.component.html
src/app/shared/components/test-certificate/test-certificate.component.scss
src/app/shared/components/test-certificate/test-certificate.component.ts

- Make the certificate number editable.
- Revert the change to the test number.
- Revert the navigation change to the tech record.
[CB2-7829](https://dvsa.atlassian.net/browse/CB2-7829)

feat(cb2-7829): enable changing certificate number

---

src/app/services/technical-record/technical-record.service.ts

feat(cb2-7842): Cannot Amend a Cherished Transfer

---

src/app/services/technical-record/technical-record.service.spec.ts
src/app/services/technical-record/technical-record.service.ts

I broke it and it regressed. So I did some tests and fixed it.

feat(cb2-7842): update logic and add tests

---

src/app/features/tech-record/create-batch-trl/components/batch-trl-results/batch-trl-results.component.ts

_Information from the previous batch is being retained. this is confusing and can lead to some errors, such as vehicles being created twice_
[CB2-7896](https://dvsa.atlassian.net/browse/CB2-7896)

fix(cb2-7896): previous batch information is retained

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/services/axles/axles.service.ts
src/app/services/technical-record/technical-record.service.ts

This makes it so the display is always now in order, and any changes will work too. When we generate a plate, we fix it for the backend service.
[https://dvsa.atlassian.net/browse/CB2-7891](7891)

feat(cb2-7891): repair axle ordering

---

src/app/forms/validators/custom-async-validators.ts

Update to email instead of resource key
[https://dvsa.atlassian.net/browse/CB2-7861](7861)

fix(cb2-7861): change value to display the email

---

src/app/features/tech-record/create-batch-trl/components/batch-trl-template/batch-trl-template.component.html

This adds unique ids to the tech record amend component fields.
https://dvsa.atlassian.net/browse/CB2-7845

fix(CB2-7845): added ids to create batch trailer page elements

---

src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.html

[CB2-7652](https://dvsa.atlassian.net/browse/CB2-7652)

fix(cb2-7652): amend the cancel button text

---

src/app/features/tech-record/create/create-tech-record.component.ts

[CB2-7946](https://dvsa.atlassian.net/browse/CB2-7946)

fix(cb2-7946): do not add the trailer id as primary vrm

---

src/app/forms/templates/test-records/create-master.template.ts
src/app/forms/templates/test-records/section-templates/required/contingency-required-hidden-section-hgv-trl.template.ts
src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group4-lgv.template.ts
src/app/services/technical-record/technical-record.service.ts

vehicle size was being sent on hgv tests, this is bad and breaks stuff, removed it
[https://dvsa.atlassian.net/browse/CB2-7952](7952)

fix(cb2-7952): vehicle size not allowed in test

---

src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.spec.ts
src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
src/app/models/vehicle-tech-record.model.ts
src/app/services/technical-record/technical-record.service.ts
src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

[CB2-7759](https://dvsa.atlassian.net/browse/CB2-7759)

feat(cb2-7759): navigate to the summary page after creating a tech record

---

src/app/app.component.html
src/app/core/components/phase-banner/phase-banner.component.html
src/app/core/components/phase-banner/phase-banner.component.scss
src/app/core/components/phase-banner/phase-banner.component.spec.ts
src/app/core/components/phase-banner/phase-banner.component.ts
src/app/core/core.module.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Feature CB2-7886: add user survey to VTM
This adds a phase banner at underneath the header with a link that opens a new tab to the user survey. (the link will be in the secret)

feat(cb2-7886): add user survey to VTM 

---

src/app/app.component.ts
src/app/services/google-analytics/google-analytics.service.spec.ts
src/app/services/google-analytics/google-analytics.service.ts
src/index.html

Added Google Tag Manager to VTM to enable sending of page view telemetry to Google Analytics
[CB2-7887](https://dvsa.atlassian.net/browse/CB2-7887)

feat(cb2-7887): implement google analytics

---

src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
src/app/forms/templates/test-records/section-templates/test/test-section.template.ts

Allow some dates to be empty on failed tests
[CB2-8109](https://dvsa.atlassian.net/browse/CB2-8109)

fix(cb2-8109): allow failed tests to send without dates

---

src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.html
src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
src/app/models/reference-data.model.ts
src/app/shared/pipes/tyre-axle-load/tyre-axle-load.pipe.spec.ts
src/app/shared/pipes/tyre-axle-load/tyre-axle-load.pipe.ts
src/app/shared/shared.module.ts

_Calculate the axle load from other fields_
[CB2-7899](https://dvsa.atlassian.net/browse/CB2-7899)

feat(cb2-7899): axle load from index

---

src/app/features/reference-data/reference-data-routing.module.ts

#999 and #1010 changed distinct parts of the code, however because they were merge separately without rebasing to the latest develop, this caused the build to fail.

fix(cb2-0000): fix build failing between merges

---

src/app/features/reference-data/reference-data-add/reference-data-add.component.html
src/app/features/reference-data/reference-data-add/reference-data-add.component.spec.ts
src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
src/app/features/reference-data/reference-data-list/reference-data-list.component.html
src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
src/app/features/reference-data/reference-data-routing.module.ts
src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.html
src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.ts
src/app/features/reference-data/reference-data.module.ts
src/app/forms/templates/reference-data/brakes.ts
src/app/forms/templates/reference-data/country-of-registration.ts
src/app/forms/templates/reference-data/hgv-make.ts
src/app/forms/templates/reference-data/psv-make.ts
src/app/forms/templates/reference-data/reasons-for-abandoning-TIR.ts
src/app/forms/templates/reference-data/reasons-for-abandoning-TRL.ts
src/app/forms/templates/reference-data/reasons-for-abandoning-hgv.ts
src/app/forms/templates/reference-data/reasons-for-abandoning-psv.ts
src/app/forms/templates/reference-data/specialist-reasons-for-abandoning.ts
src/app/forms/templates/reference-data/trl-make.ts
src/app/forms/templates/reference-data/tyres.ts

There is no validation for blank resource key when adding Country of registration
[CB2-8192](https://dvsa.atlassian.net/browse/CB2-8192)

fix(cb2-8192): ref-data admin - adds validation for required field 'resourceKey'

---

src/app/services/batch-technical-record/batch-technical-record.service.spec.ts
src/app/services/batch-technical-record/batch-technical-record.service.ts
src/app/services/technical-record/technical-record.service.ts

refactor(cb2-0000): remove duplicate method

---

src/app/models/body-type-enum.ts

Adding Other tanker type for hgv and trailer
(note: the code mapping is just for display purposes, and is changed in the tech records before saving)
[CB2-7847](https://dvsa.atlassian.net/browse/CB2-7847)

feat(cb2-7847): adds body type Other tanker

---

src/app/forms/templates/reference-data/brakes.ts
src/app/forms/templates/reference-data/psv-make.ts
src/app/forms/templates/reference-data/tyres.ts

CB2-8242: removes unnecessary fields that were stopping the creation of 3 types of reference data

fix(cb2-8242): Adding reference data - template errors

---

src/app/features/reference-data/reference-data-add/reference-data-add.component.ts

CB2-8194: No validation for existing CoR being added again
No validation for existing CoR being added again
[CB2-8194](https://dvsa.atlassian.net/browse/CB2-8194)

feat(cb2-8194): error handling for existing reference data resource keys

---

src/app/features/tech-record/create/create-tech-record.component.html
src/app/features/tech-record/create/create-tech-record.component.ts

[CB2-8274](https://dvsa.atlassian.net/browse/CB2-8274)

fix(cb2-8274): added logging for test

---

src/app/features/tech-record/create/create-tech-record.component.html
src/app/features/tech-record/create/create-tech-record.component.ts

fix(cb2-0000): minor content change

---

src/app/features/tech-record/create/create-tech-record.component.ts

CB2-8228 - adds current to the options for the dropdown in create

feature/cb2-8228: Should be able to create a new Tech Record as Current

---

src/app/forms/custom-sections/tyres/tyres.component.html
src/app/forms/custom-sections/tyres/tyres.component.scss
src/app/forms/services/dynamic-form.types.ts

Improvements made to the horizontal space allocated to the tyre code column for technical record creation.
[CB2-8110](https://dvsa.atlassian.net/browse/CB2-8110)

Fix(cb2 8110): spacing issue tyre code

---

src/app/features/search/search.component.html
src/app/features/search/search.component.spec.ts
src/app/services/technical-record-http/technical-record-http.service.ts
src/app/services/technical-record/technical-record.service.spec.ts
src/app/store/global-error/reducers/global-error-service.reducer.spec.ts
src/app/store/global-error/reducers/global-error-service.reducer.ts
src/app/store/tech-record-search/effects/tech-record-search.effect.spec.ts
src/app/store/tech-record-search/effects/tech-record-search.effect.ts
src/app/store/tech-record-search/reducer/tech-record-search.reducer.spec.ts
src/app/store/tech-record-search/reducer/tech-record-search.reducer.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

Error messages (e.g. Not found) don't appear on tech record search 
[CB2-8084](https://dvsa.atlassian.net/browse/CB2-8084)

fix(cb2-8084): error message not appearing on search

---

src/app/features/tech-record/create-batch/components/batch-vehicle-details/batch-vehicle-details.component.spec.ts
src/app/features/tech-record/create-batch/components/batch-vehicle-details/batch-vehicle-details.component.ts

[CB2-7898](https://dvsa.atlassian.net/browse/CB2-7898)

fix(cb2-7898): shows error for duplicate vins

---

src/app/features/tech-record/create-batch/components/batch-vehicle-details/batch-vehicle-details.component.html

[CB2-8509](https://dvsa.atlassian.net/browse/CB2-8509)

fix(cb2-8509): minor content change

---

src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group2.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group3And4.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group5.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group2.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3And4.template.ts
src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group5.template.ts

[CB2-8361](https://dvsa.atlassian.net/browse/CB2-8361)
Specialist tests use custom defects and there is no option currently to PRS them, as per the bug ticket this is something we are supposed to be able to do on contingency tests and as a result amending specialist tests.

fix/cb2-8361: Add ability to PRS specialist tests

---

src/app/features/reference-data/reference-data-add/reference-data-add.component.html
src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
src/app/features/reference-data/reference-data-list/reference-data-list.component.ts

fix CB2-8143:
fixes an issue in develop where you couldn't create a new reference data item

fix(cb2-8143): Fix for adding a reference data item

---

src/app/forms/custom-sections/plates/plates.component.html
src/app/forms/custom-sections/plates/plates.component.ts

[CB2-8214](https://dvsa.atlassian.net/browse/CB2-8214)

feat(cb2-8214): add plate audit history

---

src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
src/app/features/tech-record/tech-record-routing.module.ts

Also removes old logic that shouldn't be required since last refactor
[CB2-8596](https://dvsa.atlassian.net/browse/CB2-8596)

fix(cb2-8596): archive details in current record

---

src/app/api/test-types/model/testType.ts
src/app/api/test-types/model/testTypeCategory.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
src/app/models/test-results/test-result.model.ts
src/app/resolvers/contingency-test/contingency-test.resolver.ts
src/app/store/technical-records/selectors/technical-record-service.selectors.ts
src/app/store/test-types/selectors/test-types.selectors.ts

[CB2-8424](https://dvsa.atlassian.net/browse/CB2-8424)

feat(cb2-8424): Limit what contingency tests can be created for a Provisional Tech Record

---

src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.ts
src/app/features/reference-data/reference-data-list/reference-data-list.component.html
src/app/features/reference-data/reference-data-list/reference-data-list.component.scss
src/app/features/reference-data/reference-data-list/reference-data-list.component.ts

CB2-8145: Pagination of Reference Data:
Adds the pagination component to the reference data list component. limits results to 25 per page.

feat(cb2-8145): Pagination of Reference Data

---

src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.ts
src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.spec.ts
src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.ts
src/app/store/reference-data/selectors/reference-data.selectors.ts

Tech Records and Test results with deleted Reference Data
[CB2-8217](https://dvsa.atlassian.net/browse/CB2-8217)
- Ability to manage Tech and Test Records with deleted reference data so these record can still be updated

Feature/cb2 8217 - Tech Records and Test results with deleted Reference Data

---

src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts

Motorcycle number of wheels driven
Removed the word driven from number of wheels driven
[CB2-8091](https://dvsa.atlassian.net/browse/CB2-8091)

feat(cb2-8091): removed the word driven

---

src/app/api/reference-data/model/referenceDataItem.ts
src/app/features/reference-data/reference-data-add/reference-data-add.component.spec.ts
src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.ts
src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.html
src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.spec.ts
src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.ts
src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-listcomponent.ts
src/app/features/reference-data/reference-data-list/reference-data-list.component.html
src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
src/app/features/reference-data/reference-data-routing.module.ts
src/app/features/reference-data/reference-data.module.ts
src/app/models/reference-data.model.ts
src/app/services/reference-data/reference-data.service.ts
src/app/store/reference-data/actions/reference-data.actions.spec.ts
src/app/store/reference-data/actions/reference-data.actions.ts
src/app/store/reference-data/effects/reference-data.effects.spec.ts
src/app/store/reference-data/effects/reference-data.effects.ts
src/app/store/reference-data/reducers/reference-data.reducer.spec.ts
src/app/store/reference-data/reducers/reference-data.reducer.ts

Ability to view all Reference Data that has been deleted
[CB2-8218](https://dvsa.atlassian.net/browse/CB2-8218)

feat(cb2-8218): list of deleted reference data

---

src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.ts
src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
src/app/store/technical-records/selectors/technical-record-service.selectors.ts

fixes an issue in the decode pipe that wasn't correctly getting the vehicle type

fix(cb2-8677): 404 received for some Reasons For Abandoning on saved abandoned test records

---

.github/workflows/tag-merge-conflicts.yml

Implement the retry logic for null status on PRs.

chore(*): implement null values in merge conflict action

---

src/app/forms/custom-sections/tyres/tyres.component.ts

Tyre code lookup intermittently not working
Tyre code lookup intermittently not working
[CB2-8718](https://dvsa.atlassian.net/browse/CB2-8718)

fix(cb2-8718): tyre code lookup intermittently not working

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts

Remove a non-null assertion as it results in some errors in the console when changing vehicle type
[CB2-8751](https://dvsa.atlassian.net/browse/CB2-8751)

fix(cb2-8751): remove non-null assertion

---

src/app/features/reference-data/reference-data-add/reference-data-add.component.html
src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.ts
src/app/features/reference-data/reference-data-amend/reference-data-amend.component.html
src/app/features/reference-data/reference-data-amend/reference-data-amend.component.ts
src/app/features/reference-data/reference-data-delete/reference-data-delete.component.html
src/app/features/reference-data/reference-data-delete/reference-data-delete.component.spec.ts
src/app/features/reference-data/reference-data-delete/reference-data-delete.component.ts
src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.html
src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.spec.ts
src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.ts
src/app/features/reference-data/reference-data-list/reference-data-list.component.html
src/app/features/reference-data/reference-data-list/reference-data-list.component.spec.ts
src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
src/app/features/reference-data/reference-data-routing.module.ts
src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.html
src/app/features/reference-data/reference-data.module.ts

Ref Data: Breadcrumb navigation isn't correct
Ref Data: Breadcrumb navigation isn't correct
[CB2-8764](https://dvsa.atlassian.net/browse/CB2-8764)

fix(cb2-8764): implements use of breadcrumbs within reference data administration

---

src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.spec.ts
src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
src/app/features/tech-record/tech-record-routing.module.ts

Found a small bug where a refactor had not updated these components.

fix(cb2-*): repair plate and letter sections

---

src/app/forms/components/date/date.component.html
src/app/forms/components/date/date.component.ts

[CB2-8776](https://dvsa.atlassian.net/browse/CB2-8776)
Parent ticket: https://dvsa.atlassian.net/browse/CB2-8712

feat(cb2-8776): Fix error message not showing above field

---

src/app/services/technical-record-http/technical-record-http.service.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

Remove old way of selecting tech record as it is redundant

fix(cb2-*): plate and letter gen fix

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html

add edit tech record button to bottom of tech record
[CB2-8711](https://dvsa.atlassian.net/browse/CB2-8711)

feat(cb2-8711): add edit tech record button to bottom of tech record

---

src/app/features/reference-data/reference-data-list/reference-data-list.component.html
src/app/features/reference-data/reference-data-list/reference-data-list.component.scss
src/app/features/reference-data/reference-data-list/reference-data-list.component.ts

CB2-8144: what this changes from the initial PR:
change of layout for the buttons from guidance from design team, 
enter submits the form
slight tweek to how failed searches behave

Feature/cb2 8144: ability to search reference data

---

src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.scss

move amend/ submit/ cancel buttons to right of screen
[CB2-8711](https://dvsa.atlassian.net/browse/CB2-8711)

feat(cb2-8711): move amend, submit, cancel buttons to right of screen

---

src/app/features/reference-data/reference-data-list/reference-data-list.component.ts

CB2-8144: Changes error message to match the field name

feat(cb2-8144): ability to search reference data

---

src/app/forms/components/date/date.component.html
src/app/forms/components/date/date.component.spec.ts
src/app/forms/components/date/date.component.ts

Dates don't show error messages until a user has touched all boxes. If they miss a box totally, errors will now show locally on submission.

feat(cb2-8712): dates don't error till user is done typing

---

src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/general/applicant-details.template.ts
src/app/forms/templates/general/manufacturer.template.ts
src/app/forms/templates/trl/trl-purchaser.template.ts
src/app/forms/validators/custom-validators.ts

- Applicant Email Address 
- Purchasers Email Address 
- Manufacturers Email Address 
**A valid email must contain:**
An “@”
A “.” after the “@”
[CB2-8226](https://dvsa.atlassian.net/browse/CB2-8226)

feat(cb2-8226): email validation

---

src/app/forms/validators/custom-validators.ts

- Applicant Email Address 
- Purchasers Email Address 
- Manufacturers Email Address 
**A valid email must contain:**
An “@”
A “.” after the “@”
[CB2-8226](https://dvsa.atlassian.net/browse/CB2-8226)

feat(cb2-8226): change in error message

---

src/app/forms/validators/custom-validators.ts

- Applicant Email Address 
- Purchasers Email Address 
- Manufacturers Email Address 
Message:
‘Enter an email address in the correct format, like name@example.com’.
taken from: [Email addresses](https://design-system.service.gov.uk/patterns/email-addresses/)
[CB2-8226](https://dvsa.atlassian.net/browse/CB2-8226)

feat(cb2-8226): change in error message to align with gds

---

src/app/forms/components/text-area/text-area.component.html
src/app/forms/components/text-area/text-area.component.ts

Add character count to text areas. Shown on all text areas if they have the `maxLength` validator.
[CB2-8723](https://dvsa.atlassian.net/browse/CB2-8723)

feat(cb2-8723): add character limits to text areas

---

src/app/forms/components/text-area/text-area.component.html
src/app/forms/templates/general/notes.template.ts

- Correcting an off by one error on the showing of the error message
- The notes section has had a limit of 800 for 10 months, when it's supposed to be 1024! 😱 
[CB2-8723](https://dvsa.atlassian.net/browse/CB2-8723)

fix(cb2-8723): fix notes limit, fix 0 characters remaining

---

src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
src/app/forms/components/date/date.component.html
src/app/forms/components/date/date.component.ts
src/app/forms/components/number-input/number-input.component.ts
src/app/forms/components/radio-group/radio-group.component.html
src/app/forms/components/radio-group/radio-group.component.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group12and14.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group15and16.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group3And4And8.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group5And13.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group6And11.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group9And10.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group2.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group3And4.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group5.template.ts
src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group5-LGV.ts

Acceptance Criteria:
- The summary of errors box displays a link for each error detected on submission of a Technical Record
- When a user selects a link it should take them to the specific field that has the validation error
[CB2-8784](https://dvsa.atlassian.net/browse/CB2-8784)

feat(cb2- 8784): navigate from error message box to specific field

---

src/app/api/test-types/model/testType.ts
src/app/api/test-types/model/testTypeCategory.ts
src/app/store/test-types/selectors/test-types.selectors.ts

[CB2-7849](https://dvsa.atlassian.net/browse/CB2-7849)

fix(cb2-7849): filter tests only for provisional

---

src/app/store/test-types/selectors/test-types.selectors.ts

[CB2-7849](https://dvsa.atlassian.net/browse/CB2-7849)

fix(cb2-7849): filter test type updated

---

src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts

feat(cb2-8665): amend vrm sends boolean

---

src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.ts
src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts
src/app/store/technical-records/selectors/batch-create.selectors.ts

fix batch update of vehicles
[CB2-8665](https://dvsa.atlassian.net/browse/CB2-8665)

fix(cb2-8665): fix batch update of vehicles

---

src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts

Swapped around the error message shown to the user when the user attempts to create a test on a skeleton record.
[CB2-8777(https://dvsa.atlassian.net/browse/cb2-8777)

feat(cb2-8777): Create test record validation message

---

package-lock.json
package.json
src/app/forms/custom-sections/weights/weights.component.ts

add techRecord_ prefix and bump types
[CB2-8666](https://dvsa.atlassian.net/browse/CB2-8666)

fix(cb2-8666): add techRecord_ prefix and bump types

---

package-lock.json
package.json

[CB2-8666](https://dvsa.atlassian.net/browse/CB2-8666)

chore(cb2-8666): bump types package

---

src/app/forms/validators/custom-validators.ts

CB2-8230: Reduce duplication of data entry for PSVs
marks control as pristine after calculation, if we don't and the form has any other errors the calculation is re-run and size and class recalculated.
[CB2-8230](https://dvsa.atlassian.net/browse/CB2-8230)

feat(cb2-8230): reduce duplication of data entry for psvs

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts

[CB2-9038](https://dvsa.atlassian.net/browse/CB2-9038): Moves the dispatch for clearSectionStates so that it only clears when the form is valid and is being submitted.

fix(cb2-9038): moved clear section states action to correct location

---

package-lock.json
package.json

chore(cb2-0000): update type definition

---

package-lock.json
package.json
src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts

update types
change default for techRecord_numberOfWheelsDriven in motorcycle

chore(cb2-0000): update types and change default for techRecord_numberOfWheelsDriven

---

src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts

The value of motorcycle up to 200cc has been replaced with the value of motorcycle over 200cc 
[CB2-9083](https://dvsa.atlassian.net/browse/CB2-9083)

fix(cb2-9083): correct vehicle class description

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts

Added a hint which was missed off original ACs
[CB2-8709](https://dvsa.atlassian.net/browse/CB2-8709)

feat(cb2-8709): Add missing hint for required fields

---

src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.html
src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.ts

Adds a back button next to the cancel button on cancel test page
[CB2-8557](https://dvsa.atlassian.net/browse/CB2-8557)

feat(cb2-8557): Add back button to test cancel page

---

src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.html
src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.scss
src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.spec.ts
src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.ts
src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
src/app/features/tech-record/tech-record-routing.module.ts
src/app/features/tech-record/tech-record.module.ts
src/app/forms/models/async-validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-async-validators.ts
src/app/forms/validators/custom-validators.ts
src/app/services/technical-record-http/technical-record-http.service.ts
src/app/services/technical-record/technical-record.service.ts
src/app/store/technical-records/actions/technical-record-service.actions.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts

CB2-8710
Front end changes to allow cherished transfer on single record and 2 records. 
[CB2-8710](https://dvsa.atlassian.net/browse/CB2-8710)

feat(cb2-8710): improve the efficiency of performing a cherished transfer

---

src/app/forms/components/defect-select/defect-select.component.html

Handle the edge case where we do not have defect taxonomy.
[CB2-9086](https://dvsa.atlassian.net/browse/CB2-9086)

feat(cb2-9086): handle no defect taxonomy

---

src/app/features/test-records/components/test-type-select/test-type-select.component.html

Handle the case where no test types are found of applicable to the technical record.
[CB2-9087](https://dvsa.atlassian.net/browse/CB2-9087)

feat(cb2-9087): handle no test types

---

src/app/forms/templates/car/car-tech-record.template.ts
src/app/forms/templates/lgv/lgv-tech-record.template.ts
src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts

Adds some additional required tags and remove tags from others to resolve discrepancies between application and document provided
[CB2-8709](https://dvsa.atlassian.net/browse/CB2-8709)

fix(cb2-8709): Add additional required tags and remove invalid ones

---

src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html

CB2-8710
allows you to do a cherished transfer on a provisional record. This is consistent with previous behaviour. 
[CB2-8710](https://dvsa.atlassian.net/browse/CB2-8710)

fix(cb2-8710): improve the efficiency of performing a cherished transfer

---

package-lock.json
package.json
src/app/forms/custom-sections/plates/plates.component.spec.ts

[CB2-9166](https://dvsa.atlassian.net/browse/CB2-9166)

chore(cb2-9166): bump type-def package

---

src/app/features/search/multiple-search-results/multiple-search-results.component.html
src/app/features/search/multiple-search-results/multiple-search-results.component.spec.ts

Handle the case where no results return when doing a search
[CB2-7045](https://dvsa.atlassian.net/browse/CB2-7045)

feat(cb2-7045): create from search

---

src/app/core/components/breadcrumbs/breadcrumbs.component.html
src/app/core/components/breadcrumbs/breadcrumbs.component.spec.ts
src/app/core/components/breadcrumbs/breadcrumbs.component.ts
src/app/features/tech-record/tech-record-routing.module.ts
src/app/features/test-records/amend/amend-test-records-routing.module.ts
src/app/features/test-records/create/create-test-records-routing.module.ts

Add breadcrumb to return to test creation screen from defect selection on contingency test.
[CB2-9086](https://dvsa.atlassian.net/browse/CB2-9086)

fix(cb2-9086): include breadcrumb to navigate to test creation screen

---

src/app/forms/custom-sections/letters/letters.component.html
src/app/forms/custom-sections/letters/letters.component.ts

CB2-9124
adds the method to store scroll position to the letters component
[CB2-9124](https://dvsa.atlassian.net/browse/CB2-9124)

feat(cb2-9124): when returning to tech record maintain scroll position

---

.eslintignore
src/app/guards/cancel-edit-tech/cancel-edit-tech.guard.spec.ts
src/app/guards/cancel-edit-tech/cancel-edit-tech.guard.ts
src/app/guards/cancel-edit-test/cancel-edit-test.guard.spec.ts
src/app/guards/cancel-edit-test/cancel-edit-test.guard.ts
src/app/guards/no-edit/no-edit.guard.spec.ts
src/app/guards/no-edit/no-edit.guard.ts
src/app/guards/no-query-params/no-query-params.guard.spec.ts
src/app/guards/no-query-params/no-query-params.guard.ts
src/app/guards/role-guard/roles.guard.spec.ts
src/app/guards/role-guard/roles.guard.ts
src/app/interceptors/delayed-retry/delayed-retry.interceptor.spec.ts
src/app/interceptors/delayed-retry/delayed-retry.interceptor.ts
src/app/interceptors/delayed-retry/delayed-retry.module.ts
src/app/interceptors/error-handling/error-handling.interceptor.spec.ts
src/app/interceptors/error-handling/error-handling.interceptor.ts
src/app/interceptors/error-handling/error-handling.module.ts
src/app/interceptors/interceptor.module.ts

[CB2-8121](https://dvsa.atlassian.net/browse/CB2-8121)

feat(cb2-8121): lint for guards and interceptor folders

---

.eslintignore
src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
src/app/resolvers/contingency-test/contingency-test.resolver.ts
src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.spec.ts
src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.ts
src/app/resolvers/tech-record-view/tech-record-view.resolver.spec.ts
src/app/resolvers/tech-record-view/tech-record-view.resolver.ts
src/app/resolvers/test-result/test-result.resolver.spec.ts
src/app/resolvers/test-result/test-result.resolver.ts
src/app/resolvers/test-stations/test-stations.resolver.spec.ts
src/app/resolvers/test-stations/test-stations.resolver.ts
src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.spec.ts
src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.ts
src/app/resolvers/title/title.resolver.spec.ts
src/app/resolvers/title/title.resolver.ts

CVS: Replace TSLint with ESLint for all CVS Typescript Repos
One line description
[CB2-8121](https://dvsa.atlassian.net/browse/CB2-8121)

feat(cb2-8121): eslint errors fixed in resolvers

---

src/app/forms/custom-sections/tyres/tyres.component.html
src/app/forms/custom-sections/weights/weights.component.ts

fix the Axle Weights not incrementing
Many thanks for help from Dan and Nathan
[CB2-9200](https://dvsa.atlassian.net/browse/CB2-9200)

fix(cb2-9200): fix the Axle Weights not incrementing

---

src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
src/app/services/technical-record-http/technical-record-http.service.ts
src/app/store/technical-records/actions/technical-record-service.actions.ts
src/app/store/technical-records/effects/technical-record-service.effects.ts
src/app/store/technical-records/reducers/technical-record-service.reducer.ts

Update front end to call new update VIN end point
[CB2-9190](https://dvsa.atlassian.net/browse/CB2-9190)

feat(CB2-9190): Implementation of new update VIN endpoint

---

src/app/forms/custom-sections/weights/weights.component.ts

The weights need to still change even after an edit and also need to be ceiling after calculation

fix(cb2-8714): repair override function and ceil value for weights

---

src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
src/app/forms/custom-sections/modified-weights/modified-weights.component.html
src/app/forms/custom-sections/modified-weights/modified-weights.component.ts

fixes for issues raised during testing, treats axles correctly and makes the vehicle summary section work correctly

feat(cb2-8971): summary screen for tech record amendments

---

.prettierrc
src/app/features/reference-data/reference-data-add/reference-data-add.component.spec.ts
src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.spec.ts
src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.spec.ts
src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive-component.ts
src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive.component.spec.ts
src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.spec.ts
src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.spec.ts
src/app/features/test-records/amend/views/test-amend-reason/test-amend-reason.component.spec.ts
src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
src/app/forms/custom-sections/dimensions/dimensions.component.spec.ts
src/app/forms/custom-sections/dimensions/dimensions.component.ts
src/app/forms/validators/custom-validators.ts
src/app/guards/no-query-params/no-query-params.guard.spec.ts
src/app/resolvers/contingency-test/contingency-test.resolver.ts

feat(cb2-8121): remove all unused imports to reduce linting warnings

---

src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.spec.ts
src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts

CB2-8971 
Updates the submit button to say review, also fixes issues we were having with the accordion and clears section state and scroll position on submit. 

feat(cb2-8971): rech record changes summary

---

src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts

Add m-1 to label and check view and amend 
[
](url)

feat(cb2-9680): edit emissions label

---

src/app/forms/components/field-warning-message/field-warning-message.component.html
src/app/forms/components/field-warning-message/field-warning-message.component.spec.ts
src/app/forms/components/field-warning-message/field-warning-message.component.ts
src/app/forms/components/number-input/number-input.component.html
src/app/forms/components/number-input/number-input.component.ts
src/app/forms/components/switchable-input/switchable-input.component.html
src/app/forms/components/switchable-input/switchable-input.component.ts
src/app/forms/custom-sections/dimensions/dimensions.component.html
src/app/forms/dynamic-forms.module.ts

Added Dimension warning component for meeting the AC of ticket.
[CB2-9604](https://dvsa.atlassian.net/browse/CB2-9604)

feature(cb2-9604): Added Dimension warnings

---

setenv.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/directives/feature-toggle.directive.spec.ts
src/app/directives/feature-toggle.directive.ts
src/app/features/feature-toggle/feature-toggle-routing.module.ts
src/app/features/feature-toggle/feature-toggle.module.ts
src/app/features/feature-toggle/feature-toggle/feature-toggle.component.html
src/app/features/feature-toggle/feature-toggle/feature-toggle.component.ts
src/app/features/home/home.component.html
src/app/guards/feature-toggle-guard/feature-toggle.guard.spec.ts
src/app/guards/feature-toggle-guard/feature-toggle.guard.ts
src/app/services/feature-toggle-service/featuer-toggle-service.spec.ts
src/app/services/feature-toggle-service/feature-toggle-service.ts
src/app/shared/shared.module.ts
src/assets/featureToggle.json
src/assets/featureToggle.prod.json
src/environments/environment.prod.ts
src/environments/environment.ts

Create a feature toggle service, with directives and guards to implement it too.
[CB2-9669](https://dvsa.atlassian.net/browse/CB2-9669)

feat(cb2-9669): create VTM feature toggle tools

---

package-lock.json
package.json

_Bumped types package for Tyre Use Code changes_
[CB2-9596](https://dvsa.atlassian.net/browse/CB2-9596)

chore(cb2-9596): bumped types package

---

src/app/forms/custom-sections/body/body.component.spec.ts
src/app/forms/custom-sections/body/body.component.ts
src/app/models/body-type-enum.ts

fix(cb2-0000): Small fix for hgvs

---

src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
src/app/services/technical-record/technical-record.service.ts

The old call relied on text which is unsafe, this uses a boolean to confirm the tech record has been updated.
[CB2-9870](https://dvsa.atlassian.net/browse/CB2-9870)

fix(cb2-9870): repair check on hidden in VTA call

---

src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/car/car-tech-record.template.ts
src/app/forms/templates/hgv/hgv-tech-record.template.ts
src/app/forms/templates/lgv/lgv-tech-record.template.ts
src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
src/app/forms/templates/psv/psv-approval-type.template.ts
src/app/forms/templates/psv/psv-tech-record.template.ts
src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
src/app/forms/templates/trl/trl-auth-into-service.template.ts
src/app/forms/templates/trl/trl-tech-record.template.ts
src/app/forms/utils/error-message-map.spec.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-validators.spec.ts
src/app/forms/validators/custom-validators.ts

_Adds validation to most date fields on technical records_
[CB2-9598](https://dvsa.atlassian.net/browse/CB2-9598)

feat(cb2-9598): validation for dates

---

src/app/features/test-records/amend/views/test-type-select-wrapper/test-type-select-wrapper.component.spec.ts
src/app/features/test-records/components/test-type-select/test-type-select.component.spec.ts
src/app/features/test-records/components/test-type-select/test-type-select.component.ts
src/app/services/technical-record/technical-record.service.ts
src/app/store/test-types/selectors/test-types.selectors.spec.ts
src/app/store/test-types/selectors/test-types.selectors.ts

add a filter to filterTestType to meet the AC. Fixed all of failed test .
[CB2-9056](https://dvsa.atlassian.net/browse/CB2-9056)

feat(cb2-9056): filter first test / first test retest 

---

src/app/features/tech-record/create/create-tech-records-routing.module.ts
src/app/features/tech-record/tech-record-routing.module.ts
src/app/forms/components/field-warning-message/field-warning-message.component.html
src/app/forms/custom-sections/tyres/tyres.component.html
src/app/forms/custom-sections/tyres/tyres.component.scss
src/app/forms/custom-sections/tyres/tyres.component.spec.ts
src/app/forms/custom-sections/tyres/tyres.component.ts
src/app/resolvers/tech-record-data/tech-record-data.resolver.spec.ts
src/app/resolvers/tech-record-data/tech-record-data.resolver.ts

Introduces validation surrounding the GB Weights and loadIndex for axles.
[CB2-9123](https://dvsa.atlassian.net/browse/CB2-9123)

feat(cb2-9123): tyre and weight validation for hgv/trl/psv

---

package-lock.json
package.json
src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts

update develop to match release hotfix

---

src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html

[CB2-9937](https://dvsa.atlassian.net/browse/CB2-9937)
lets lgv's use the adr component on the review screen to fix it not showing

fix(cb2-9937): review screen broken

---

src/app/forms/components/select/select.component.html
src/app/forms/components/select/select.component.ts
src/app/forms/custom-sections/adr-guidance-notes/adr-guidance-notes.component.html

Add inline error message for custom form control.
[CB2-9729](https://dvsa.atlassian.net/browse/CB2-9729)

feat(cb2-9729): add inline error message

---

src/app/forms/templates/general/adr.template.ts
src/app/forms/validators/custom-validators.ts

Small change to conditionally apply the IsArray custom validator when a sibling equals true
[CB2-9729](https://dvsa.atlassian.net/browse/CB2-9729)

feat(cb2-9729): make guidance notes only required when dangerous goods is selected

---

jest.config.js
package.json

Improves unit testing performance by somewhere between 30-50%, results vary machine to machine as is dependant on available cpu threads which differs between machines.
[CB2-10057](https://dvsa.atlassian.net/browse/CB2-10057)

feat(cb2-10057): Improve unit testing performance

---

package.json

Reverts CI command back, hopefully will stop the Jenkins pipeline from failing.

fix(cb2-10057): revert CI command change

---

src/app/forms/custom-sections/tyres/tyres.component.html

[CB2-9123](https://dvsa.atlassian.net/browse/CB2-9123)

fix(cb2-9123): Show axle number instead of array index for GB Axle warning

---

sonar-project.properties

[CB2-9069](https://dvsa.atlassian.net/browse/CB2-9069)

Changing hosted Sonarqube URL

---

src/app/forms/services/dynamic-form.service.ts

[CB2-10146](https://dvsa.atlassian.net/browse/CB2-10146)

fix(cb2-10146): fix global error when fields hidden

---

src/app/forms/components/view-list-item/view-list-item.component.html
src/app/forms/templates/general/adr.template.ts

CB2-9864: allows you to create a vehicle with no subsequent inspections 

feat(cb2-9864): adr tank details part 3

---

src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
src/app/forms/components/view-list-item/view-list-item.component.html

cb2-9746
only shows the additional note added to the adr component and removes line under last item in subsequent inspection history

feat(cb2-9746): additional examiner notes

---

src/app/forms/custom-sections/adr-tank-details-subsequent-inspections/adr-tank-details-subsequent-inspections.component.ts

CB2 9864
change of validator length 

feat(cb2-9864): tank details part 3

---

.github/workflows/deploy-VTMDev-1.yml
.github/workflows/deploy-VTMDev-2.yml
.github/workflows/deploy-develop.yml
.github/workflows/deploy-devops.yml
.github/workflows/deploy-integration.yml
.github/workflows/deploy.yml

- Fixing AWS role for S3 Upload in Non-prod
- Fixing naming for Integration

Fixing AWS role for S3 Upload in Non-prod

---

src/app/forms/components/view-list-item/view-list-item.component.html
src/app/forms/templates/general/adr.template.ts

CB2-10211: fix for issue in create where tank body type not creating

fix(cb2-10211): fix for for bug tank body type not creating

---

src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
src/app/forms/custom-sections/adr/adr.component.ts
src/app/forms/templates/general/adr-summary.template.ts

feat(cb2-10226): Resolve adding subsequent additional examiner notes

---

src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
src/app/forms/components/view-list-item/view-list-item.component.html
src/app/forms/custom-sections/adr-examiner-notes-history/adr-examiner-notes-history.component.html

cb2-10226: fix for date format and issues with template mutation

fix(cb2-10266): additional examiner notes date format

---

src/app/forms/components/view-list-item/view-list-item.component.html
src/app/forms/templates/general/adr.template.ts
src/app/store/technical-records/reducers/technical-record-service.reducer.ts

Fixes the array order, shows only the last 3 notes added, and introduces a missing hint above the note when amending/creating.

fix(cb2-10235): Additional examiner notes bug fixes

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/forms/components/date/date.component.html
src/app/forms/components/text-input/text-input.component.html

[CB2-10240](https://dvsa.atlassian.net/browse/CB2-10240)

fix(cb2-10240): multiple warnings for same fields

---

.env.example
setenv.ts
src/app/services/feature-toggle-service/feature-toggle-service.spec.ts
src/app/services/feature-toggle-service/feature-toggle-service.ts

Also, update the TARGET_ENV to map to TARGET_ENV from secrets, not the environment in the start script
[CB2-10329](https://dvsa.atlassian.net/browse/CB2-10329)

chore(cb2-10329): refactor to use dev as default config for feature flags

---

src/app/forms/validators/custom-validators.spec.ts
src/app/forms/validators/custom-validators.ts

[CB2-10321](https://dvsa.atlassian.net/browse/CB2-10321)

fix(cb2-10321): fix adr warnings

---

src/app/core/components/global-error/global-error.service.ts
src/app/forms/custom-sections/adr/adr.component.spec.ts
src/app/forms/custom-sections/adr/adr.component.ts
src/app/forms/models/validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/general/adr-summary.template.ts
src/app/forms/templates/general/adr.template.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-validators.spec.ts
src/app/forms/validators/custom-validators.ts
src/app/services/adr/adr.service.spec.ts
src/app/services/adr/adr.service.ts

Tidying up some code.
[CB2-10328](https://dvsa.atlassian.net/browse/CB2-10328)

fix(cb2-10328): refactor adr component

---

setenv.ts
src/app/app.component.spec.ts
src/app/app.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts
src/index.html

Re-introduces GTM using a new container ID, set up to allow for the values to be stored in git secrets.
[CB2-10024](https://dvsa.atlassian.net/browse/CB2-10024)

feat/CB2-10024 - Re-introduce Google Tag Manager

---

src/app/features/tech-record/create-batch/create-batch-routing.module.ts

[CB2-10499](https://dvsa.atlassian.net/browse/CB2-10499)

fix(cb2-10499): add data resolver to create-batch route

---

src/app/forms/models/plateRequiredFields.model.ts
src/app/forms/templates/hgv/hgv-dimensions.template.ts

Remove 5th wheel coupling from HGV plates
[CB2-10586](https://dvsa.atlassian.net/browse/CB2-10586)

feat(cb2-10586): remove 5th wheel coupling from HGV plates

---

src/app/services/documents/documents.service.spec.ts
src/app/services/technical-record/technical-record.service.spec.ts
src/app/store/technical-records/effects/technical-record-service.effects.spec.ts

Adds additional test coverage to the:
- documents service
- technical record service
Replaces a provided in the technical record effects spec to use a mock to speed up tests.
[CB2-8121](https://dvsa.atlassian.net/browse/CB2-8121)

feat(cb2-8121): improve test coverage

---

src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
src/app/features/tech-record/tech-record-routing.module.ts

the adr cert gen needs to be added for desk based test role
[CB2-10457](https://dvsa.atlassian.net/browse/CB2-10457)

feat(cb2-10457): update the roles for desk based adr cert gen

---

src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
src/assets/featureToggle.int.json
src/assets/featureToggle.json
src/assets/featureToggle.preprod.json
src/assets/featureToggle.prod.json

[CB2-9990](https://dvsa.atlassian.net/browse/CB2-9990)

feat(cb2-9990): update feature flags for adr epics

---

src/app/forms/custom-sections/adr/adr.component.ts

[CB2-10824](https://dvsa.atlassian.net/browse/CB2-10824)

fix(cb2-10824): do not alter value of tankStatement select when on summary review screen

---

src/app/features/test-records/components/base-test-record/base-test-record.component.html
src/assets/featureToggle.int.json
src/assets/featureToggle.json
src/assets/featureToggle.preprod.json
src/assets/featureToggle.prod.json

[CB2-10971](https://dvsa.atlassian.net/browse/CB2-10971)

feat(cb2-10971): Add flag so required standards only show in dev

---

src/app/features/test-records/components/base-test-record/base-test-record.component.html
src/app/features/test-records/components/base-test-record/base-test-record.component.spec.ts
src/app/features/test-records/components/base-test-record/base-test-record.component.ts
src/app/features/test-records/create/create-test-records-routing.module.ts
src/app/forms/components/required-standard-select/required-standard-select.component.html
src/app/forms/components/required-standard-select/required-standard-select.component.ts
src/app/forms/custom-sections/required-standards/required-standards.component.html
src/app/forms/custom-sections/required-standards/required-standards.component.ts
src/app/forms/custom-sections/required-standards/required-standards.spec.ts
src/app/forms/dynamic-forms.module.ts
src/app/forms/services/dynamic-form.service.ts
src/app/resolvers/required-standards/required-standards.resolver.spec.ts
src/app/resolvers/required-standards/required-standards.resolver.ts
src/app/services/loading/loading.service.ts
src/app/services/required-standards/required-standards.service.ts
src/app/store/app-store.module.ts
src/app/store/index.ts
src/app/store/required-standards/actions/required-standards.actions.spec.ts
src/app/store/required-standards/actions/required-standards.actions.ts
src/app/store/required-standards/effects/required-standards.effects.spec.ts
src/app/store/required-standards/effects/required-standards.effects.ts
src/app/store/required-standards/reducers/required-standards.reducer.spec.ts
src/app/store/required-standards/reducers/required-standards.reducer.ts
src/app/store/required-standards/required-standards.module.ts
src/app/store/required-standards/selectors/required-standards.selector.spec.ts
src/app/store/required-standards/selectors/required-standards.selector.ts

This work will retrieve the IVA defects, store them, attaches it to some navigation to a page and adds a resolver.
[CB2-10741](https://dvsa.atlassian.net/browse/CB2-10741)

feat(cb2-10741): pull back and store Required Standards for a new IVA test

---

src/app/features/test-records/create/create-test-records-routing.module.ts
src/app/forms/components/required-standard-select/required-standard-select.component.html
src/app/forms/components/required-standard-select/required-standard-select.component.scss
src/app/forms/components/required-standard-select/required-standard-select.component.spec.ts
src/app/forms/components/required-standard-select/required-standard-select.component.ts
src/app/forms/custom-sections/required-standard/required-standard.component.html
src/app/forms/custom-sections/required-standard/required-standard.component.ts
src/app/forms/dynamic-forms.module.ts
src/app/store/required-standards/selectors/required-standards.selector.ts

Select a required standard with this all new page!
[CB2-10421](https://dvsa.atlassian.net/browse/CB2-10421)

feat(cb2-10421): create required standard select page

---

src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts

The wrong validator was used on the generate button so it was blocking test submissions. 

feat(cb2-10672): adr certificate generation is available when a pass result is selected for adr contingency tests

---

src/app/forms/components/select/select.component.html
src/app/forms/components/select/select.component.scss
src/app/forms/components/text-input/text-input.component.html
src/app/forms/components/text-input/text-input.component.scss

Makes use of flexbox and flex-wrap to ensure items wrap properly.
[CB2-11085](https://dvsa.atlassian.net/browse/CB2-11085)

fix(cb2-11085): fix styling bug with tags

---

src/app/forms/custom-sections/required-standard/required-standard.component.ts

Repair PRS toggle on RS amend
[CB2-10602](https://dvsa.atlassian.net/browse/CB2-10602)

fix(cb2-10602): repair PRS toggle on amend for RS

---

src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group5.template.ts

cert no. box also hidden on failing tests
[CB2-10198](https://dvsa.atlassian.net/browse/CB2-10198)

feat(cb2-10198): cert no. required on iva/msva pass/prs 

---

src/assets/featureToggle.preprod.json
src/assets/featureToggle.prod.json

Turns on ADR certificate generation in both pre-prod and prod environments
[CB2-11091](https://dvsa.atlassian.net/browse/CB2-11091)

feat(cb2-11091): show adr certificate generation in vtm

---

package.json
src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html

feat(cb2-*): update version and reintroduce role

---

src/app/forms/custom-sections/required-standard/required-standard.component.html

[CB2-11236](https://dvsa.atlassian.net/browse/CB2-11236)

fix(cb2-11236): fix wording on required standards prs

---

manifest.json
src/app/forms/custom-sections/required-standard/required-standard.component.html
src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group4-lgv.template.ts
src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
src/app/resolvers/contingency-test/contingency-test.resolver.ts

[CB2-10202](https://dvsa.atlassian.net/browse/CB2-10202)

feat(CB2-10202): Update VRM on test following a cherished transfer

---

src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
src/app/forms/dynamic-forms.module.ts

added cherished transfer warning message for psv and hgv
[CB2-9916](https://dvsa.atlassian.net/browse/CB2-9916)

feat(cb2-9916): added cherished transfer warning message for psv and hgv

---

package-lock.json
package.json
src/app/forms/components/required-standard-select/required-standard-select.component.spec.ts
src/app/forms/components/required-standard-select/required-standard-select.component.ts
src/app/forms/custom-sections/adr/adr.component.html
src/app/forms/custom-sections/adr/adr.component.scss
src/app/forms/custom-sections/adr/adr.component.spec.ts
src/app/forms/custom-sections/adr/adr.component.ts
src/app/models/test-results/test-result-required-standard.model.ts
src/app/services/documents/documents.service.spec.ts
src/app/services/documents/documents.service.ts
src/app/services/required-standards/required-standards.service.ts
src/app/shared/directives/retrieve-document/retrieve-document.directive.ts
src/app/store/required-standards/actions/required-standards.actions.ts
src/app/store/required-standards/effects/required-standards.effects.spec.ts
src/app/store/required-standards/reducers/required-standards.reducer.spec.ts
src/app/store/required-standards/reducers/required-standards.reducer.ts
src/app/store/required-standards/selectors/required-standards.selector.spec.ts

[CB2-11294](https://dvsa.atlassian.net/browse/CB2-11294)

feat(cb2-11294): allow signed url zip files to download

---

src/app/forms/custom-sections/adr/adr.component.ts

not meant to see me if I am in editing!

fix(cb2-11294): hide adr download button in edit mode

---

src/app/forms/components/view-list-item/view-list-item.component.html
src/app/forms/custom-sections/adr-examiner-notes-history-view/adr-examiner-notes-history-view.component.html
src/app/forms/templates/general/adr.template.ts

Update adr notes view to use custom component, to enable the notes to match the styling of other history sections of the tech record. 
[CB2-10241](https://dvsa.atlassian.net/browse/CB2-10241)

feat(cb2-10241): update adr notes to use custom component

---

package-lock.json
package.json
src/app/forms/custom-sections/adr-examiner-notes-history-edit/adr-examiner-notes-history-edit.component.html
src/app/forms/custom-sections/adr-examiner-notes-history-edit/adr-examiner-notes-history.component-edit.spec.ts
src/app/forms/custom-sections/adr-examiner-notes-history-view/adr-examiner-notes-history-view.component.html
src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
src/app/store/technical-records/reducers/technical-record-service.reducer.ts

createdAtDate for adr examiner notes now save as full iso date string.
old format: '2024-02-12'
new format: '2024-02-12T14:48:00.000Z'
[CB2-11103](https://dvsa.atlassian.net/browse/CB2-11103)

feat(cb2-11103): createdAtDate for adr examiner notes now save as full iso date string

---

src/assets/featureToggle.int.json
src/assets/featureToggle.preprod.json
src/assets/featureToggle.prod.json

feat(cb2-10973): feature flags changed to show IVA flow in all envs

---

src/app/forms/models/async-validators.enum.ts
src/app/forms/services/dynamic-form.service.ts
src/app/forms/templates/general/hgv-trl-body.template.ts
src/app/forms/utils/error-message-map.ts
src/app/forms/validators/custom-async-validators.spec.ts
src/app/forms/validators/custom-async-validators.ts

[CB2-11546](https://dvsa.atlassian.net/browse/CB2-11546)

feat(cb2-11546): make 'make' required for HGVs and TRLs which carry dangerous goods

---

src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts

create mocked date to fix failing unit test

fix(cb2-9747): create mocked date to fix failing unit test

---

src/app/services/test-records/test-records.service.ts
src/app/store/test-records/effects/test-records.effects.ts
src/app/store/test-records/selectors/test-records.selectors.ts

[CB2-11930](https://dvsa.atlassian.net/browse/CB2-11930)

feat(cb2-11930): ensure certificate number is sent to backend if it exists on MVSA IVA tests

---

src/app/services/test-records/test-records.service.ts
src/app/store/test-records/effects/test-records.effects.ts
src/app/store/test-records/selectors/test-records.selectors.ts

[CB2-11930](https://dvsa.atlassian.net/browse/CB2-11930)

fix(cb2-11930): ensure certificate number is not erased after created IVA/MVSA test

---

src/app/forms/models/testTypeId.enum.ts

[CB2-12056](https://dvsa.atlassian.net/browse/CB2-12056)

feat(cb2-12056): test codes moved

---

src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.html

Add id for automation testing
[CB2-12304](https://dvsa.atlassian.net/browse/CB2-12304)

feat(cb2-12304): Add id for automation testing
