dvsa/cvs-app-vtm

- src/app/inspection-details/inspection-details.component.scss
- src/app/models/adrDetailsForm.model.ts
- src/app/pipes/FilterRecordPipe.ts
- src/app/pipes/OrderByStatusPipe.ts
- src/app/shell/header/header.component.html
- src/app/shell/header/header.component.scss
- src/app/shell/header/header.component.ts
- src/app/store/state/adrDetailsForm.state.ts
- src/app/technical-record-search/technical-record-search.module.ts
- src/app/technical-record-search/technical-record.service.spec.ts
- src/app/technical-record-search/technical-record.service.ts
- src/app/technical-record-search/test-result.service.spec.ts
- src/app/technical-record/technical-record.component.html
- src/app/technical-record/technical-record.component.scss
CVSB-10517 - Implement UI logic to display proper tech record in the tech record view page
CVSB-10575 - The order in which we display tech records in the tech record history section is not correct
CVSB-10615 - The list of documents is not in the adr details sections is not correct
CVSB-10636 - User can select both statement and product list
CVSB-10733 - User can select both yes and no to "Memo 07/09 (3 month extension)"
CVSB-10734 - User can select both yes and no to "Battery list applicable"
CVSB-10500 - For vehicles with no primary VRM we should display "-" and not ""
> bug fixing + small functionality/design fixes

- src/app/app.component.scss
Added cursor pointer for back button on tecc record view page. We should not have all this problems once we replace accordion from tech rec page and delete the css from app.css
https://jira.dvsacloud.uk/browse/CVSB-13970
> Feature/CVSB-13970 - back button cursor pointer on tech record view page

- src/app/shared/libraries/accordion-item/accordion-item.component.ts
- src/app/technical-record-search/technical-record-search.component.html
- src/app/technical-record/tech-rec-history/tech-rec-history.component.html
- src/app/technical-record/test-history/__snapshots__/test-history.component.spec.ts.snap
- src/app/technical-record/test-history/test-history.component.html
- src/app/test-record/__snapshots__/test-record.component.spec.ts.snap
- src/app/test-record/defects/defects.component.html
- src/app/test-record/emission-details/emission-details.component.html
- src/app/test-record/notes/notes.component.html
- src/app/test-record/seatbelt-installation-check/__snapshots__/seatbelt-installation-check.component.spec.ts.snap
- src/app/test-record/seatbelt-installation-check/seatbelt-installation-check.component.html
- src/app/test-record/test-record.component.ts
- src/app/test-record/test-section/test-section.component.html
- src/app/test-record/vehicle/vehicle.component.html
- src/app/test-record/visit/visit.component.html
- src/global.scss
Bug tickets:
https://jira.dvsacloud.uk/browse/CVSB-15169
https://jira.dvsacloud.uk/browse/CVSB-15184
**Fixed:**
- UTC format to correctly display backend date values 
-  "advisory" defect background to be white with black writing
- "advisory" and "dangerous" defects types to be listed on the same line with the name of the defect
- capitalize just the first letter in a string containing multiple words
- check html ids do not contain white spaces
- bug on display emission details section when test result is not pass
> Feature/CVSB-15169 - [BUGS] found on CVSB-10283

- .github/pull_request_template.md
- .secignore
- package.json
scanrepo was not enabled on the repo as some errors (node_modules files of .scannerwork/) were being thrown when running it due to cached files being pushed early in the project and scannerepo being enabled later.
> fix(scanrepo): enable scanrepo

- .secignore
- package.json
scanrepo was not enabled on the repo as some errors (node_modules files of .scannerwork/) were being thrown when running it due to cached files being pushed early in the project and scannerepo being enabled later.
> fix(scanrepo): reenable scan repo and add it to commit msg hook

- src/app/technical-record-create/__snapshots__/technical-record-create.component.spec.ts.snap
- src/app/technical-record-create/technical-record-create.component.html
- src/app/technical-record-create/technical-record-create.component.spec.ts
- src/app/technical-record-create/technical-record-create.component.ts
Bugfix for: CVSB-10141 - As the DVSA, we want to be able to search for a vehicle before creating it to ensure that it does not already exist
The VRM error message also appears above the VIN field
https://jira.dvsacloud.uk/browse/CVSB-16611
> bugfix(feature/CVSB-16611): PR against 00000 to merge the bugfix

- src/app/technical-record/manufacturer/__snapshots__/manufacturer.component.spec.ts.snap
- src/app/technical-record/manufacturer/edit/__snapshots__/manufacturer-edit.component.spec.ts.snap
- src/app/technical-record/manufacturer/edit/manufacturer-edit.component.html
- src/app/technical-record/manufacturer/edit/manufacturer-edit.component.spec.ts
- src/app/technical-record/manufacturer/edit/manufacturer-edit.component.ts
- src/app/technical-record/manufacturer/manufacturer.component.html
- src/app/technical-record/manufacturer/manufacturer.component.spec.ts
- src/app/technical-record/manufacturer/manufacturer.component.ts
- src/app/technical-record/technical-record.component.html
- src/app/technical-record/technical-record.module.ts
_It allows to select Trailer & create Manufacturer record._
[https://jira.dvsacloud.uk/browse/CVSB-16938](https://jira.dvsacloud.uk/browse/CVSB-16938)
In the screenshot we see that _techRecord_ object is populated for Manufacturer section upon onSaveChanges:
> Feature/cvsb 10172-16938 - add mode to Create/Edit for Manufacturer 

- sonar-project.properties
Re-instates the SonarQube config which fixes the sonarqube stage in the build pipeline
[cb2-2877](https://jira.dvsacloud.uk/browse/CB2-2877)
> fix(cb2-2877): re-instate sonarqube config

- sonar-project.properties
Removes the reference to an additional test report that isn't generated since the project was re-started and the test framework was changed
> fix(cb2-2880): sonarqube build step

- src/app/app.module.ts
- src/app/store/app-store.module.ts
- src/app/store/user/user-state.module.ts
_Refreshing the VTM app loses the user's name in the header of the app_
[CB2-3590](https://jira.dvsacloud.uk/browse/CB2-3590)
> fix(cb2-3590): Sync user state with local storage

- src/app/app.module.ts
- src/app/features/global-error/global-error.service.ts
- src/app/interceptors/delayed-retry/delayed-retry.interceptor.spec.ts
- src/app/interceptors/delayed-retry/delayed-retry.interceptor.ts
- src/app/interceptors/delayed-retry/delayed-retry.module.ts
- src/app/interceptors/interceptor.module.ts
- src/app/store/technical-records/technical-record-service.effects.ts
_The search for a Technical Record using a VIN can take a while to return a result and on occasions this can lead to timeouts. _
[link to ticket CB2-3615](https://jira.dvsacloud.uk/browse/CB2-3615)
- Added new Http Interceptor that retries API requests based on provided configuration.
- New interceptor module and supporting classes to make retry interceptor configurable.
- Dependency on [CB2-3591](https://jira.dvsacloud.uk/browse/3591) to show errors in summary.
> fix(cb2-3615): http request timeout

- src/app/app.component.spec.ts
- src/app/store/technical-records/technical-record-service.effects.spec.ts
Added some extra unit tests for technical-record-service effects introduced in [PR 299](https://github.com/dvsa/cvs-app-vtm/pull/299). Insures the functionality in [CB2-3591](https://jira.dvsacloud.uk/browse/CB2-3591) is implemented.
> Extra unit tests for technical-record-service effects CB2-3591

- src/app/store/spinner/reducers/spinner.reducer.spec.ts
- src/app/store/spinner/reducers/spinner.reducer.ts
- src/app/store/test-records/effects/test-records.effects.spec.ts
- src/app/store/test-records/effects/test-records.effects.ts
_Removing the error message for valid VINs with no test records when searching by VIN_
Also added the spinner when searching for test records
[CB2-3612](https://dvsa.atlassian.net/browse/CB2-3612)
> fix(cb2-3612): remove error message when no tests results found

- src/app/features/tech-record-summary/tech-record-summary.component.html
- src/app/features/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/templates/psv/psv-approval-type.template.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
Refactoring to use a separate dynamic form template for the _type approval_ section created in [#317](https://github.com/dvsa/cvs-app-vtm/pull/317). Following the current direction to use multiple dynamic form templates, as in [#315](https://github.com/dvsa/cvs-app-vtm/pull/315) and [#316](https://github.com/dvsa/cvs-app-vtm/pull/316).
[CB2-3354](https://dvsa.atlassian.net/browse/CB2-3354)
> refactor(cb2-3354): refactoring dynamic template

- package.json
SonarQube (`sonar-scanner`) requires the output of unit test code coverage, and the deployment pipeline doesn't explicitly run the unit tests first.
[CB2-4023](https://dvsa.atlassian.net/browse/CB2-4023)
> fix(cb2-4023): fixes sonarqube code coverage reporting

- sonar-project.properties
SonarQube is currently showing 0% code coverage, this was previously an issue with the lcov.info report file not being produced, this PR resolves the path to that `lcov.info` file as the pipelines were unable to find it as the coverage directory was not the usual `/coverage/lcov.info`.
Jenkins Error:
Report file location:
> fix(cb2-4023): change sonar lcov report path

- src/app/models/vehicle-tech-record.model.ts
Feature to add the semi long trailer type for [techRecord].vehicleConfiguration field
@andrewf-bjss  to confirm this is the correct branch to merge into please.
> CB2-396: added semi long trailer to enum

- src/app/forms/templates/psv/psv-approval-type.template.ts
Pretty self-explanatory.
[CB2-4343](https://dvsa.atlassian.net/browse/CB2-4343)
> bugfix(cb2-4343): Correct Caption Name for Vehicle Approval Type

- src/app/forms/templates/test-records/section-templates/trl-annual.template.ts
[https://dvsa.atlassian.net/browse/CB2-4134](CB2-4134)
> fix(cb2-4134): removes odometer from trailer test results

- src/app/forms/templates/hgv/hgv-max-train-weights.template.ts
Previous PR for this was not correctly reading data from database as it was trying to find maxEecWeight, maxGbWeight, etc... instead of maxTrainEecWeight, maxTrainGbWeight, etc...
**Before:**
**After :**
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4163)
> fix(cb2-4163): make max train weight visible

- src/app/features/search/multiple-search-results/multiple-search-results.component.ts
- src/app/features/search/search.component.spec.ts
- src/app/features/search/search.component.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
- src/app/features/tech-record/tech-record.component.ts
- src/app/services/technical-record/technical-record.service.spec.ts
- src/app/services/technical-record/technical-record.service.ts
- src/app/store/global-error/reducers/global-error-service.reducer.spec.ts
- src/app/store/global-error/reducers/global-error-service.reducer.ts
- src/app/store/technical-records/actions/technical-record-service.actions.spec.ts
- src/app/store/technical-records/actions/technical-record-service.actions.ts
- src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
- src/app/store/technical-records/effects/technical-record-service.effects.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
- src/app/store/test-records/effects/test-records.effects.spec.ts
- src/app/store/test-records/effects/test-records.effects.ts
Enables search for tech records using the VRM.
Cleans up some of the code related to general search.
[CB2-2892](https://dvsa.atlassian.net/browse/CB2-2892)
> feature(CB2-2892): Enable Retrieving Tech Records by VRM

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/templates/general/documents.template.ts
Centralize the `documents` template.
Use it for HGV and TRL record types.
[CB2-4274](https://dvsa.atlassian.net/browse/CB2-4274)
> feat(cb2-4274): Add the Documents Section to HGV and TRL

- src/app/resolvers/test-result/test-result.resolver.spec.ts
- src/app/resolvers/test-result/test-result.resolver.ts
_Test amendment history is not displaying when navigating from tech record view. The resolver checking if the test record exists in store is redundant and means vtm does not make a second request to the api for test history when navigating from tech view_
[CB2-4799](https://dvsa.atlassian.net/browse/CB2-4799)
> fix(cb2-4799): test amendment not displaying

- mock-api/mock-api-server.ts
- src/app/store/test-records/effects/test-records.effects.spec.ts
- src/app/store/test-records/effects/test-records.effects.ts
- src/mocks/hgv-record.mock.ts
- src/mocks/psv-record.mock.ts
- src/mocks/trl-record.mock.ts
_Changing the routing on tech record to `systemNumber` from `vin` broke the mock-api_
_We also don't want to show an error message on tech record view when the vehicle has no test results, fixing that issue as well_
> fix(*): mock-api and error message fix

- src/app/forms/templates/test-records/section-templates/required/required-hidden-section.template.ts
Allows the reason for creation field to be edited, does not add in a popup as that hasn't been confirmed by service design.
[CB2-4068](https://dvsa.atlassian.net/browse/CB2-4068)
> feat(cb2-4068): reason for creation can now be edited

- src/app/forms/components/defects/defects.component.spec.ts
- src/app/forms/components/dynamic-form-group/dynamic-form-group.component.spec.ts
- src/app/forms/components/dynamic-form-group/dynamic-form-group.component.ts
- src/app/forms/services/dynamic-form.types.ts
VTM is currently dispatching 16-17 actions on every keystroke to update state with the latest changes from the form, causing a noticeable drop in speed and efficiency. In order to fix this issue, this PR:
- Ensures the number of actions being dispatched is at maximum one per keystroke
- Adds a debounce time to only dispatch the action if the form has not been updated in the last 500ms
> chore(*): improve performance

- src/app/features/test-records/components/base-test-record/base-test-record.component.ts
- src/app/forms/components/defects/defects.component.ts
- src/app/forms/components/dynamic-form-group/dynamic-form-group.component.spec.ts
- src/app/forms/components/dynamic-form-group/dynamic-form-group.component.ts
- src/app/forms/services/dynamic-form.types.ts
https://github.com/dvsa/cvs-app-vtm/pull/454 had some unintended consequences where the subscription was not updating the object in state. Moving the debounce from the interface to the consumers of the observable fixed the issue. Many actions were still being dispatched since the base-test-record component essentially dispatched actions on change with the `afterViewChecked` lifecycle hook
> fix(*): improve-performance

- src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
Additional comments were not set to required when hidden in all templates, this has been fixed.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4969)
> fix(cb2-4969): brought additional comments for abandoning into line

- src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
Country of registration on the Trailer template was not matching the new layout used in other templates, this has now been fixed alongside the previous issues.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4969)
> fix(cb2-4969): Bought country of registration into line with other templates

- angular.json
- src/app/features/test-records/views/test-record/test-record.component.html
- src/app/features/test-records/views/test-record/test-record.component.ts
- src/app/forms/components/defect/defect.component.html
- src/app/forms/components/defect/defect.component.spec.ts
- src/app/forms/components/defect/defect.component.ts
- src/app/forms/components/defects/defects.component.html
- src/app/forms/components/defects/defects.component.ts
- src/app/forms/components/radio-group/radio-group.component.html
- src/app/forms/components/radio-group/radio-group.component.ts
- src/app/forms/templates/general/defect.template.ts
- src/app/models/defects/location.model.ts
- src/app/store/defects/selectors/defects.selectors.ts
- Add additional selectors for defects that enable filtering based on vehicle type
- Correct the Additional Info location model
- Add `null`s to the defect template to prevent the auto-population bug
- Extend the `defects` component adding the ability to retrieve more info about individual defects to be passed onto the `defect` component and filter results based on the current vehicle type
- Greatly overhaul the `defect` component to:
- Dynamically display all optional fields based on the selected defect
- Replace the static HTML for the optional fields with a loop of a custom dictionary
- Display the "Prohibition Issued" field only when a defect is "Dangerous"
[CB2-4229](https://dvsa.atlassian.net/browse/CB2-4229)
> feat(CB2-4202): Make the Defect Fields Dynamic

- src/app/forms/templates/test-records/master.template.ts
Fixes the templates to allow validation to pass for records for certain test types
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5623)
> fix(cb2-5623): made changes to templates to allow validation to pass

- src/app/forms/components/defect-select/defect-select.component.html
- src/app/forms/components/defect-select/defect-select.component.ts
- src/app/forms/components/defect/defect.component.html
- src/app/forms/components/defect/defect.component.ts
- src/app/forms/components/defects/defects.component.html
- src/app/forms/components/defects/defects.component.ts
- src/app/forms/templates/general/defect.template.ts
- src/app/forms/validators/defects/defect.validators.ts
- Add an "advisory" option to the end of every defect selection.
- Update the defect fields' visibility based on this election.
- Alter the validation so that "Notes" is a required field on "advisory" defects.
[CB2-5613](https://dvsa.atlassian.net/browse/CB2-5613)
> fix(CB2-5613): Enable the Selection of Advisory Defects

- src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts
There is an issue when checking the carried out during test field in the seatbelt section, where "most recent installation check date" is not being updated if the record does not having an "original" date populated as the control doesn't know what value to use for time 
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4814)
> fix(cb2-4814): error with date time

- src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
It turns out that the prohibition field is required for group 11, but forbidden for group 13.
This PR corrects that.
2nd worst ticket I have worked on thus far...
[CB2-4380](https://dvsa.atlassian.net/browse/CB2-4380)
> fix(cb2-4380): add prohibition field to test types 6 and 11

- src/app/features/test-records/amend/views/test-result-summary/test-result-summary.component.html
Fixes a one-letter typo spotted in the EU vehicle category question title
> bug(*): fixes a typo in the test result summary view

- src/app/core/components/spinner/spinner.component.scss
- src/app/forms/models/validators.enum.ts
- src/app/forms/services/dynamic-form.service.ts
- src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group1.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
- src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-vehicle-section.template.ts
- src/app/forms/utils/error-message-map.ts
_Ticket to add field-level validation to the Odometer field whilst recording contingency tests_
- Add max validator to odometer reading to 9999999.
- Fix maxLength args in templates.
- Fix spinner styling to correctly hide background content while spinning.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5906)
> feat(cb2-5906): odometer reading validation

- src/app/services/test-types/test-types.service.ts
- src/app/store/test-records/effects/test-records.effects.ts
- src/app/store/test-types/selectors/test-types.selectors.spec.ts
- src/app/store/test-types/selectors/test-types.selectors.ts
The test type selector method in our test types service is supposed to search the taxonomy tree recursively and return the right one given an ID. But this was bugged and led to the test results summary not displaying the names for certain selections.
This PR fixes that.
[CB2-5732](https://dvsa.atlassian.net/browse/CB2-5732)
> fix(cb2-5732): fix the test type selector method

- src/app/forms/components/dynamic-form-group/dynamic-form-group.component.ts
Following @mcadenas-bjss's observation and some manual testing that I have done, this is the right version of the check.
> fix(cb2-9999): correct the form patching check

- src/app/forms/components/date/date.component.html
- src/app/forms/components/date/date.component.ts
- src/app/forms/components/date/focus-next.directive.spec.ts
- src/app/forms/components/date/focus-next.directive.ts
- src/app/forms/dynamic-forms.module.ts
_Automate the focus event between date segments as the user types numeric values in._
> feat(cb2-5728): auto focus date segments

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
- src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
Changes so we route to correct path after:
- Submitting an edit on a tech record
- Clicking to view a historic tech record
> fix(*): fix routing to do with new historic path

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
When a value in the tech record is amended that is originally `undefined` and the amendment is cancelled, the non-edit view shows the amendments and not the original `undefined` state.
This is an issue with the way dynamic forms are updated/patched using the tech record received from the API and the values that are amended. The complexity of changing the functionality of the dynamic form component has been mitigated by forcing a navigation to the same URL path causing the component to be reloaded - recreating the form with the original tech record found in state.
[Link to ticket number](https://dvsa.atlassian.net/browse/CB2-6192)
> fix(cb2-6192): navigate on cancelling amendment of tech record

- src/app/forms/templates/test-records/create-master.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-vehicle-section.template.ts
- src/app/store/test-records/effects/test-records.effects.spec.ts
Adding in support for a HGV of group 9 as well as removing the preparer from PSV and HGV forms.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5811)
> feat(cb2-5811): group 9 templates

- src/app/forms/templates/test-records/master.template.ts
- src/app/forms/templates/test-records/section-templates/required/required-hidden-specialist-section.template.ts
- src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
_This ticket is to increase this scope to supporting to all test types for amending PSV Specialist Test Types within Group 1 (Test Type IDs 126, 128, 130, 150, 151, 161, 162, 163, 181, 182)_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-5779)
> feat(cb2-5779): added specialist test group 1

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
When a user clicked submit when a form was invalid, the user was switched to the non-edit mode and all changes were lost. 
Now when a form is invalid and the user clicks submit, the user remains on the edit screen and they are scrolled to the top of the page to highlight the errors as per service design
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6229)
> fix(cb2-6229): only toggle edit mode when form is valid

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/templates/general/applicant-details.template.ts
- src/app/forms/templates/general/manufacturer.template.ts
Changes:
- Renames manufacturer form 
- Adds service design (different width input boxes) to the last applicant details section [CB2-5687](https://dvsa.atlassian.net/browse/CB2-5687)
> chore(*): add service design to last applicant

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
Previously when canceling an amendment of a tech record, you were prompted with a popup if you were sure you wanted to cancel. If you then clicked that you didn't want to cancel the amendment, your changes would be lost and the non-edit view would be presented to the user.
The expected behavior of staying in the edit view is now retained if you choose to not want to cancel the amendment when prompted.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6234)
> fix(cb2-6234): clicking cancel confirmation to not take out of edit mode

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
- src/app/features/test-records/components/base-test-record/base-test-record.component.html
- src/app/shared/components/accordion-control/accordion-control.component.html
- src/app/shared/components/accordion-control/accordion-control.component.spec.ts
- src/app/shared/components/accordion-control/accordion-control.component.ts
- src/app/shared/components/accordion/accordion.component.html
- src/app/shared/components/accordion/accordion.component.spec.ts
- src/app/shared/components/accordion/accordion.component.ts
- Fix the accordion icons which were not toggling correctly.
- Handle the edge case where the accordion control would ignore new accordions added after the `ngAfterContentInit()`.
- Simplify and refactor the accordion and accordion control components.
[CB2-6224](https://dvsa.atlassian.net/browse/CB2-6224)
> fix(cb2-6224): fix accordion icons and toggling functionality

- src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
We changed the way tech records routes, this was mixed, this is the fix.
[https://dvsa.atlassian.net/browse/CB2-6253](6253)
> fix(cb2-6253): add in URL fix

- src/app/forms/components/text-input/text-input.component.ts
- src/app/forms/templates/general/applicant-details.template.ts
Quick fix for variable input box width which was not able to compute the `width` property during rendering HTML and so the style was defaulting to `govuk-input` even when width was provided in the template. Changed style to a getter which has resolved the issue.
> fix(*): fix input bar width service design

- src/app/forms/templates/trl/trl-brakes.template.ts
- src/app/models/vehicle-tech-record.model.ts
- src/app/shared/pipes/default-null-or-empty/default-null-or-empty.pipe.ts
When data coming from the API includes `boolean` values that are in `string` format, the `defaultNullOrEmpty` directive shows them as "True" or "False", whereas they should be displayed as "Yes" or "No".
This PR addresses this edge case.
[CB2-6291](https://dvsa.atlassian.net/browse/CB2-6291)
> fix(cb2-6291): fix displaying string booleans

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
Adds more tests to the edit tech record button, mainly todo with router navigation and user journeys when going to cancel an amendment
> chore(*): add more tests for edit tech record button

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
- src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
- src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
- src/app/features/tech-record/tech-record-routing.module.ts
- src/app/features/test-records/amend/views/amended-test-record/amended-test-record.component.spec.ts
- src/app/features/test-records/components/base-test-record/base-test-record.component.spec.ts
- src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
- src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
- src/app/services/technical-record/technical-record.service.spec.ts
- src/app/services/technical-record/technical-record.service.ts
Changes in this PR:
- When navigating back to a current tech record via the tech record history component, the breadcrumbs and URL will no longer have `historic` in them.
- Provisional tech records now have their own unique URL path - previously they would be provided with `historic`
- Now possible to conduct a test against a provisional tech record whereas previously it would navigate you to an invalid path
- Not possible to conduct a test against an archived tech record.
[CB2-6362](https://dvsa.atlassian.net/browse/CB2-6362) & [CB2-6447](https://dvsa.atlassian.net/browse/CB2-6447)
> fix(cb2-6362 & cb2-6447): provide provisional with own path and allow test to be conducted on provisional

- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
- src/app/store/global-error/reducers/global-error-service.reducer.spec.ts
- src/app/store/global-error/reducers/global-error-service.reducer.ts
Changes:
- Removes persistence of errors across pages, errors will now be cleared whenever user navigates through VTM 
- Errors will no longer be displayed on a tech record in non-edit mode that were previously caused by values on the tech record not matching the validations we have on the form.
> fix(*): clear errors on navigation and stop errors in tech record non-edit mode

- src/app/forms/templates/hgv/hgv-tech-record.template.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
- src/app/forms/templates/trl/trl-tech-record.template.ts
- manufactureYear now must be a 4 digit number.
- euroStandard now must be selected.
[CB2-6523](https://dvsa.atlassian.net/browse/CB2-6523)
[CB2-6524](https://dvsa.atlassian.net/browse/CB2-6524)
> fix(cb2-6524 & cb2-6523): amend maufactureyear and eurostandard form validation

- src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
- src/app/forms/templates/hgv/hgv-tech-record.template.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
Fixes validation so only numeric values are valid for seatbelt related fields
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6524)
> fix(cb2-6524): add seats validation

- src/app/forms/templates/hgv/hgv-tech-record.template.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
- src/app/forms/templates/trl/trl-tech-record.template.ts
- Provides alterationMarker as an editable field on PSV, HGV and TRL
- Validates dtpNumber to be 6 char string
- Shows numberOfAxles on HGV record but is disabled for editing
- Makes manufactureYear a `number` and not a `string`
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6509)
> fix(cb2-6509): fix validation on vehicle summary

- src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.ts
So somewhat forgot/didn't know that the `@Input` decorator runs post-constructor time, meaning the `testResult` was undefined at constructor time, meaning the reasons for abandoning defaulted to the vehicle-specific ones over the specialist/TIR ones.
[CB2-6474](https://dvsa.atlassian.net/browse/CB2-6474)
> fix(cb2-6474): fix the reasons for abandoning

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
It turns out that the form event coming from the weights section is not encapsulated by `weights` object like the other sections. This is a quick fix to address that.
[CB2-6642](https://dvsa.atlassian.net/browse/CB2-6642)
> fix(cb2-6642): check the right weights property

- src/app/forms/models/async-validators.enum.ts
- src/app/forms/models/condition.model.ts
- src/app/forms/services/dynamic-form.service.ts
- src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
- src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
- src/app/forms/validators/custom-async-validators.spec.ts
- src/app/forms/validators/custom-async-validators.ts
New custom validator to allow the certificate number for Specialist testTypeIds 150, 151, 181, 182 to be hidden - these testTypeIds are part of Specialist Test Group 1 but the certificate field needs to be displayed for the rest of the testTypeIds in Group 1.
[https://dvsa.atlassian.net/browse/CB2-6092]
> feat(cb2-6092): hide emissions section

- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
Brake code mandatory check gets reset if we change Gross weight values
[Brake code mandatory check gets reset if we change Gross weight values](6650)
> fix(cb2-6650): fix error message not staying visible on brake code

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/custom-sections/tyres/tyres.component.ts
- src/app/forms/custom-sections/weights/weights.component.ts
- src/app/forms/templates/psv/psv-approval-type.template.ts
- src/app/forms/templates/psv/psv-tyres.template.ts
- src/app/forms/templates/psv/psv-weight.template.ts
- src/mocks/psv-record.mock.ts
- Separate the templates and update their validation rules.
[CB2-5694](https://dvsa.atlassian.net/browse/CB2-5694)
> feat(cb2-5694): separate the psv type approval section into its own template

- src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.spec.ts
- src/app/shared/components/button/button.component.html
- src/app/shared/components/button/button.component.spec.ts
- src/app/shared/components/button/button.component.ts
_Button component was not handling router link directives properly._
Fixed by extending RouterLink from component to allow the use of all RouterLink features.
[CB2-6661](https://dvsa.atlassian.net/browse/CB2-6661)
> fix(cb2-6661): adding defect to new test result returns back to technical record

- src/app/services/technical-record/technical-record.service.ts
Previously going to amend a provisional record caused for the record being amended to be the current record. 
This was an issue with the way the `viewableTechRecord` was being populated which is what populates the `editingTechRecord` state value. Now if `'provisional'` is contained within the last 2 parts of the URL, the provisional record will be selected from state.
Before;
After:
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6683)
> fix(cb2-6683): fix amending provisional record

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/components/dynamic-form-group/dynamic-form-group.component.scss
- src/app/forms/templates/psv/psv-tech-record.template.ts
Amend PSV Vehicle Summary section for provisional record
When this ticket originally went through, I didn't have the Figma for non-edit mode. 
This fix is purely aesthetic: https://www.figma.com/file/rnPv9njRc4UkFjjoJRYceO/Working-Draft_VTM?node-id=20604%3A50891&t=KkWZciaeSIDk2WeL-0
[Original Ticket](https://dvsa.atlassian.net/browse/CB2-5695)
> fix(CB2-5695): Amend PSV Vehicle Summary section for provisional record

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Reason for creation wasn't being cleared when you enter/exit amend mode.
[https://dvsa.atlassian.net/browse/CB2-6815](6815)
> fix(cb2-6815): repair reason for creation

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
- src/app/forms/templates/trl/trl-tech-record.template.ts
Adds number of axles field to vehicle summary pages of PSV and TRL and fixes issue where noOfAxles wasn't being updated when an additional axle was added...
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6768)
> fix(cb2-6768): add noOfAxles to psv and trl

- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
The routing in amend mode was broken.
[https://dvsa.atlassian.net/browse/CB2-6824](6824)
> fix(cb2-6768): change the route to not break in amend mode

- src/app/forms/custom-sections/body/body.component.html
- src/app/forms/custom-sections/body/body.component.ts
Tyre search criteria gets cleared after search result displayed
Corrected function code options (A for artic, R for rigid as in data reqs) and removed duplicate form patch function that was interfering with options binding (the if statement was double patching and clearing out the field, it now auto fills as expected)
[[link to ticket number]()](https://dvsa.atlassian.net/browse/CB2-6814)
> bug(CB2-681): Tyre search criteria gets cleared after search result displayed

- src/app/features/tech-record/tech-record-routing.module.ts
Adds fix so that there is a valid tyre search path when amending a provisional record
> fix(*): add route for tyre search when amending provisional

- src/app/core/components/header/header.component.html
- src/app/features/tech-record/components/tyres-search/tyres-search.component.html
- src/app/features/tech-record/components/tyres-search/tyres-search.component.spec.ts
- src/app/features/tech-record/components/tyres-search/tyres-search.component.ts
- src/app/services/reference-data/reference-data.service.ts
- src/app/store/reference-data/actions/reference-data.actions.spec.ts
- src/app/store/reference-data/actions/reference-data.actions.ts
- src/app/store/reference-data/reducers/reference-data.reducer.spec.ts
- src/app/store/reference-data/reducers/reference-data.reducer.ts
- src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
- src/app/store/reference-data/selectors/reference-data.selectors.ts
Tyre search criteria gets cleared after search result displayed
Retain search criteria field pop on refresh and paginate, (filter and term not being uniform broke some tests)
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6814)
> fix(CB2-6814): Tyre search criteria gets cleared after search result displayed

- src/app/resolvers/contingency-test/contingency-test.resolver.ts
_noOfWheels driven is required when creating a test. If undefined in tech record, default it to null._
[CB2-6872](https://dvsa.atlassian.net/browse/CB2-6872)
> fix(cb2-6872): default noOfWheelsDriven to null if undefined

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Axle spacing bug fix
[https://dvsa.atlassian.net/browse/CB2-6881](6881)
> fix(cb2-6881): repair add axle to not work with PSVs

- src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts
_Adds validation to ensure seatbelts fitted doesn't exceed 99_
[CB2-6915](https://dvsa.atlassian.net/browse/CB2-6915)
> fix(cb2-6915): add max validator to seatbelts fitted

- src/app/models/test-results/test-result.model.ts
- src/app/resolvers/contingency-test/contingency-test.resolver.ts
_Allows EU vehicle category to be null when sent in payload_
[CB2-6932](https://dvsa.atlassian.net/browse/CB2-6932)
> fix(cb2-6932): eu vehicle category can now be null

- src/app/forms/templates/test-records/create-master.template.ts
- src/app/forms/templates/test-records/section-templates/emissions/desk-based-emissions-section.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group1.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group12and14.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group15and16.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group3And4And8.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group5And13.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group6And11.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group9And10.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group2.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group3And4.template.ts
- src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group5.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-psv-hgv-vehicle-section-group2.template.ts
Remove Odometer count and units (DBT HGV/TRL group 2). Unhide emissions section in Review mode
Hide odo in hgv group 1 2 3, show emissions in review psv hgv group 2, delete extra title in contingency tests
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6934)
> bug(CB2-6934):  Remove Odometer count and units (DBT HGV/TRL group 2). Unhide emissions section in Review mode

- src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
> fix(cb2-0000): show trailer id in vehicle header

- src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
- src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
- src/app/forms/models/testTypeId.enum.ts
- src/app/forms/templates/test-records/create-master.template.ts
- src/app/forms/templates/test-records/master.template.ts
- src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1And4-HGV-TRL.template.ts
- src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3-HGV-TRL.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
- src/app/store/test-records/effects/test-records.effects.spec.ts
- src/app/store/test-records/effects/test-records.effects.ts
_test type if was both in group 3 and 4 causing some bugs and the wrong template being entered_
- also makes sure the keys in master templates are valid keys from the TEST_TYPES object (or `default`)
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6550)
> feat(cb2-6550): move groups 3 and 4 HGV and TRL desk based

- src/app/forms/templates/test-records/master.template.ts
_The existing amend templates are causing the test code not to show up. Until these are reviewed and the backend changes are made to be able to amend this test, commenting these out in order to not impact sprint goal tickets_
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6545)
> feat(cb2-6545): remove amend

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/templates/hgv/hgv-dimensions.template.ts
- src/app/forms/templates/hgv/hgv-weight.template.ts
- src/app/forms/templates/trl/trl-dimensions.template.ts
- src/app/forms/templates/trl/trl-weight.template.ts
The two arrays can be stored incorrectly in the database and be out of sync. This needs repaired on load of the tech record. This also addresses https://dvsa.atlassian.net/browse/CB2-6881
[https://dvsa.atlassian.net/browse/CB2-6981](6981)
> fix(cb2-6981): match axle spacing and axle arrays on load

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
- src/app/features/tech-record/components/test-record-create-button/test-record-create-button.component.html
- src/app/features/tech-record/components/test-record-create-button/test-record-create-button.component.spec.ts
- src/app/features/tech-record/components/test-record-create-button/test-record-create-button.component.ts
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
- src/app/features/tech-record/tech-record.module.ts
Changes:
- Button to create a test is now no longer visible when editing a tech record
- Refactored code so that create test button is it's own component
Non-edit mode:
Edit Mode:
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6967)
> fix(cb2-6967): only create test in non-edit mode when viewing tech record

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/templates/hgv/hgv-dimensions.template.ts
- src/app/forms/templates/trl/trl-dimensions.template.ts
If you submitted after adding a blank spacing, and never clicked on the box it sent the default value of '' but that is not a number. Null is allowed.
[https://dvsa.atlassian.net/browse/CB2-6881](6881)
> fix(cb2-6881): fix axle spacing issues with blank submissions

- src/app/forms/components/autocomplete/autocomplete.component.scss
- src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
- src/app/forms/templates/test-records/section-templates/visit/contingency-visit-section.template.ts
- src/app/forms/templates/test-records/section-templates/visit/visit-section.template.ts
- Update the autocomplete component, enabling it to extend beyond 30 rem.
- Update the dynamic form field to pass on the width into the autocomplete.
[CB2-6989](https://dvsa.atlassian.net/browse/CB2-6989)
> feature(cb2-6989): allow the autocomplete to be fully resizable

- src/app/services/test-records/test-records.service.ts
- src/app/store/test-records/effects/test-records.effects.spec.ts
- src/app/store/test-records/effects/test-records.effects.ts
The logged-in user's **username** is used for **Created by**, rather than **name**.
[CB2-7042](https://dvsa.atlassian.net/browse/CB2-7042)
Amending a test result has the user's **name** in **Created by**.
> Use name rather than username for createdBy field

- src/app/store/test-records/reducers/test-records.reducer.ts
Can't change test test type for desk based test because the calculate result returns `void` which "deletes" the test type in the resolver, meaning it would default to the existing record in state. 
Instead of returning `void` the calculate result should return `testType` unchanged.
> Note:
We probably need to look into the impact of the `defectsHiddenSection` on this function since it relies on the presence or absence of `defects` as a key in the test type to calculate the result. If defects is empty array, it sets the result to a pass, so we need to investigate if things are still working properly.
> fix(cb2-6999): fix changing test type on desk-based tests

- src/app/store/test-types/selectors/test-types.selectors.ts
_PR to rewrite filterTestTypes to ensure that MSVA tests display appropriately - and future proof filters if both code and description exist in the vehicleClass, the taxonomy is already present_
[CB2-7005](https://dvsa.atlassian.net/browse/CB2-7005)
> feat(cb2-7005): light vehicle hierarchy

- src/app/services/user-service/user-service.spec.ts
- src/app/store/user/user-state.module.ts
The logged in users userEmail property was not being persisted to state correctly and would be lost during a users session.
> CB2-6054 Fix userEmail disappearing

- src/app/features/search/single-search-result/single-search-result.component.ts
_Fix to have HGV make and model show up in search result_
[CB2-7100](https://dvsa.atlassian.net/browse/CB2-7100)
_Proof of fix_
> fix(cb2-7100): fixed hgv make and model not appearing in search

- src/app/forms/templates/psv/psv-tech-record.template.ts
_PR to fix seatbelt installation approval date's format_
[CB2-7090](https://dvsa.atlassian.net/browse/CB2-7090)
_Proof of fix_
> fix(cb2-7090): seatbelt installation approval date format

- src/app/features/tech-record/tech-record-routing.module.ts
_Add a route for test records from provisional tech record_
[CB2-7078](https://dvsa.atlassian.net/browse/CB2-7078)
> fix(cb2-7078): fix view test record from provisional tech record

- src/app/forms/components/autocomplete/autocomplete.component.scss
https://dvsa.atlassian.net/browse/CB2-7173
I have added display flex to the internal-wrapper class so that when amending a vehicle technical record a PSV vehicle the prefix appears next to the dropdown rather than above it.
> fix(cb-7173): brake code prefix appears alongside dropdown

- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-light-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-light-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
Currently the EU Vehicle Category field is disabled when creating/amending a test for a vehicle. This restriction needs to be changed so the user can add or amend the EU Vehicle Category.
[CB2-7221](https://dvsa.atlassian.net/browse/CB2-7221)
> Allow EU Vehicle Category to be editable in a test

- src/app/services/reference-data/reference-data.service.spec.ts
- src/app/services/reference-data/reference-data.service.ts
_VTM can detect that there are multiple entries for the Tester Details, but does not display them correctly_
[CB2-7192](https://dvsa.atlassian.net/browse/CB2-7192)
> fix(cb2-7192): fix how reference data labels are mapped

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/models/body-type-enum.ts
- Create body-type maps for each vehicle-type
- Update tech record summary to use the right body-type map based on vehicle-type
[CB2-397](https://dvsa.atlassian.net/browse/CB2-397)
> feat(cb2-397): add new vehicle body types

- src/app/forms/validators/custom-async-validators.ts
_When creating a test and picking a user from tester details field. The email is not being set because of the new USER reference data model. The email now come as the resourceKey (previously thought to be the staff ID)._
[CB2-7285](https://dvsa.atlassian.net/browse/CB2-7285)
> fix(cb2-7285): remap resourceKey as email for tester details

- src/app/forms/templates/hgv/hgv-dimensions.template.ts
- src/app/forms/templates/hgv/hgv-tech-record.template.ts
- src/app/forms/templates/hgv/hgv-weight.template.ts
- src/app/forms/templates/trl/trl-dimensions.template.ts
- src/app/forms/templates/trl/trl-tech-record.template.ts
- src/app/forms/templates/trl/trl-weight.template.ts
Front end defaults for numeric fields need to be null
[Link](https://dvsa.atlassian.net/browse/CB2-7405)
> fix(cb2-7405): Front end defaults for numeric fields need to be null

- src/app/forms/templates/psv/psv-body.template.ts
Psv required validation on dtp because bodytype is disabled
https://dvsa.atlassian.net/browse/CB2-5712
https://dvsa.atlassian.net/browse/CB2-7398
> fix(cb2-5712): psv required validation on dtp because bodytype is disabled

- .github/workflows/pr-label-and-assign.yml
- .github/workflows/pr-labels.yml
Because adding labels manually can be tedious. Also means people are more inclined to format their PR titles. And adding the assignee as well
> feat(*): add create auto labelling and assignee action

- src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.html
- src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
- src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.html
- src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
- src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.html
- src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
- src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
- src/app/features/tech-record/components/tech-record-history/tech-record-history.component.spec.ts
- src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
- src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
- src/app/features/tech-record/tech-record.component.html
- src/app/features/tech-record/tech-record.component.ts
- src/app/store/technical-records/effects/technical-record-service.effects.ts
- Centralize the logic that verifies all tech record summary forms are valid which was duplicated across the Vehicle Tech Record Component and the Hydrate Component. The validation logic being outside of the summary component was causing bugs as it was using `selectedTechRecord` instead of `editableTechRecord`.
- Simplify the naming conventions in common tech record components
[CB2-7456](https://dvsa.atlassian.net/browse/CB2-7456)
> refactor(cb2-7456): big tech records refactor

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
[CB2-7489](https://dvsa.atlassian.net/browse/CB2-7489)
> fix(cb2-7489): get the vehicle type from the calculated tech record

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
- Use `techRecordCalculated` when calculating custom sections.
- Make custom sections optional for vehicles with type LGV, CAR, SMALL TRL & MOTORCYCLE do not break.
- Extend the vehicle type field just enough to house "small trailer".
[CB2-7489](https://dvsa.atlassian.net/browse/CB2-7489)
> fix(cb2-7489): bug fix for changing vehicle type

- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
- src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
- src/app/forms/models/testTypeId.enum.ts
- src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3.template.ts
- src/app/models/body-type-enum.ts
- Add new test type code.
- Remove breaking form validators.
- Correct body type codes.
- Update the vehicle header to support small trailers.
[CB2-7027](https://dvsa.atlassian.net/browse/CB2-7027)
> fix(cb2-7027): enable adding test type group 3 for small trailers

- src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
- src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
- src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
- src/app/features/tech-record/create/create-tech-record.component.ts
- src/app/forms/utils/error-message-map.ts
- When creating a tech record, the user could input a manual Z number as a VRM by including a space. This is now fixed.
- When amending existing Z numbers, the submit logic would trigger even though there were validation errors on the page. This is now fixed.
[CB2-7522](https://dvsa.atlassian.net/browse/CB2-7522)
> fix(cb2-7522): fix the vrm and z number validation

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/services/axles/axles.service.ts
_As listed in the title, creating a skeleton record for a TRL or HGV, sometimes results in the Technical Record page appearing empty like this:_
[CB2-7565](https://dvsa.atlassian.net/browse/CB2-7565)
> fix(cb2-7565): display skeleton TRLs and HGVs

- src/app/api/document-retrieval/api/document-retrieval.service.ts
- src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
- src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
- src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
- src/app/forms/custom-sections/letters/letters.component.html
- src/app/forms/custom-sections/letters/letters.component.spec.ts
- src/app/forms/custom-sections/letters/letters.component.ts
- src/app/forms/custom-sections/plates/plates.component.html
- src/app/forms/custom-sections/plates/plates.component.spec.ts
- src/app/forms/custom-sections/plates/plates.component.ts
- src/app/forms/templates/psv/psv-brakes.template.ts
- src/app/services/documents/documents.service.spec.ts
- src/app/services/documents/documents.service.ts
- src/app/services/technical-record/technical-record.service.ts
- src/app/shared/components/test-certificate/test-certificate.component.html
- src/app/shared/components/test-certificate/test-certificate.component.ts
- src/app/shared/directives/retrieve-document/retrieve-document.directive.spec.ts
- src/app/shared/directives/retrieve-document/retrieve-document.directive.ts
- src/app/shared/shared.module.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
- Create a directive that handles document downloads.
- Encapsulate blob generation logic inside a service.
- Update the certificates, plates and letters components to use this new directive.
- Add a new generic method into the document retrieval service that will be used by the directive.
- Correct the anchor link on generate plate component.
- Fix the `generatePlateSuccess` action to set `loading` to ` false`.
- Set the default for parking brakes to `false`.
Important note:
There is a last TODO that depends on [CB2-7471](https://dvsa.atlassian.net/browse/CB2-7471) and [CB2-7048](https://dvsa.atlassian.net/browse/CB2-7048). The TODO is to verify that letters can be retrieved from the `document-retrieval` endpoint and update the letters component if required. …
> feat(cb2-7479): create a directive to handle document downloads

- src/app/forms/custom-sections/letters/letters.component.html
_Fix for letters section attempting to render and fetch values that don't exist_
[CB2-7626](https://dvsa.atlassian.net/browse/CB2-7626)
> fix(cb2-7626): fix letters breaking templates

- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7610)
> fix(cb2-7610): initialise parkingBrakeMrk to false

- src/app/forms/custom-sections/letters/letters.component.html
_PR to add a fallback for if a trailer does not have a letter, preventing VTM from throwing errors and hanging_
[CB2-7632](https://dvsa.atlassian.net/browse/CB2-7632)
> fix(cb2-7632): added check for if trailer has letter

- src/app/forms/validators/custom-async-validators.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7640)
> fix(cb2-7640): default eec weight to null on hgv and trl

- src/app/api/vehicle/model/techRecord.ts
- src/app/forms/custom-sections/dimensions/dimensions.component.html
- src/app/forms/templates/hgv/hgv-dimensions.template.ts
- src/app/models/vehicle-tech-record.model.ts
- src/mocks/hgv-record.mock.ts
Cannot amend Tech Record with frontVehicleTo5thWheelCouplingMax or Min
Global find and replace of AxleTo5thWheelCoupling -> VehicleTo5thWheelCoupling
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7666)
> fix(cb2-7666): Cannot amend Tech Record with frontVehicleTo5thWheelCouplingMax or Min

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- Hide the audit section when `isEditing` is toggled on.
[CB2-6641](https://dvsa.atlassian.net/browse/CB2-6641)
> fix(cb2-6641): do not display the audit section when editing tech records

- src/app/features/tech-record/create/create-tech-record.component.ts
- src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
- Add the small trailer type to the creation page dropdown.
- Add vehicle configuration to small trailers' template as it is required by the record completeness.
[CB2-7727](https://dvsa.atlassian.net/browse/CB2-7727)
> fix(cb2-7727): allow creating small trailers

- src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
Currently after doing a single tech record create, it navigates to the batch results page, not the single result page as it has been
> fix(cb2-7021): fix on tech record create summary

- src/app/forms/components/select/select.component.html
- src/app/forms/components/select/select.component.spec.ts
By default, the select element converts its values to string. By using `ngValue` the type is preserved.
[CB2-7833](https://dvsa.atlassian.net/browse/CB2-7833)
> fix(cb2-7833): preserve value type of the select element

- src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
- src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
- src/app/forms/templates/test-records/create-master.template.ts
- src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1-PSV.template.ts
- src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts
- src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3.template.ts
- src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-PSV.template.ts
- src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-lgv-template.ts
test codes now appear in the header along with the name when viewing or amending a test.
[CB2-7812](https://dvsa.atlassian.net/browse/CB2-7812)
> fix(cb2 7812): adds TestCode to the test result header

- src/app/forms/custom-sections/tyres/tyres.component.html
- src/app/forms/custom-sections/weights/weights.component.html
**Add Axle from tyres and Add Axles from weights both have ids missing**
Add ids for add axle buttons in tyres and weights
[CB2-7834](https://dvsa.atlassian.net/browse/CB2-7834)
> fix(cb2-7834): added ids for add axle buttons on tyres and weights

- src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
[CB2-7913](https://dvsa.atlassian.net/browse/CB2-7913)
> fix(cb2-7913): hide certificate link on cancelled tests

- src/app/forms/templates/car/car-tech-record.template.ts
- src/app/forms/templates/lgv/lgv-tech-record.template.ts
- src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
adds vehicle configuration 'Other' to light vehicles
[CB2-7914](https://dvsa.atlassian.net/browse/CB2-7914)
> fix(cb2-7914): adds vehicle configuration 'Other' to light vehicles

- src/app/forms/templates/test-records/master.template.ts
Adding back the custom defect in the amend specialist test for car
[CB2-7926](https://dvsa.atlassian.net/browse/CB2-7926)
> fix(cb2-7926): adds custom defect in amend specialist test for car

- package-lock.json
- package.json
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
This adds on changes and makes it only run on inital load. The store now only pipes and changes the editing record when it is not falsy.
[https://dvsa.atlassian.net/browse/CB2-7932](7932)
> fix(cb2-7932): change state systems to run only on first change

- src/app/shared/components/accordion-control/accordion-control.component.ts
Quick fix to revert changes made for batch updating that no longer applies - and breaks the accordion when creating a test record
[CB2-7972](https://dvsa.atlassian.net/browse/CB2-7972)
> fix(cb2-7972): add toggle to content children

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
_This is not a nice fix. But we need quick fix._
Reverts #979 and fixes the issue it was aiming to solve without breaking changing vehicle type.
> fix(cb2-7966): changing vehicle type

- src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
- src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
- src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
_PR to fix the subscribe method in generate plates by making the subscription close_
[CB2-7976](https://dvsa.atlassian.net/browse/CB2-7976)
[CB2-7979](https://dvsa.atlassian.net/browse/CB2-7979)
> fix(cb2-7976, 7979): fix generate plate subscribe event

- src/app/forms/components/switchable-input/switchable-input.component.html
- src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Tested for PSV, HGV, and trailers.
[CB2-7997](https://dvsa.atlassian.net/browse/CB2-7997)
> fix(cb2-7997): fixes the axle tyre details getting values from existing tyre fields

- src/app/api/test-results/model/completeTestResultsVehicleClass.ts
- src/app/api/vehicle/model/techRecordVehicleClass.ts
- src/app/models/vehicle-class.model.ts
Fix: CB2-8052:
Cannot create vehicles with class: 
1. PSV of unknown size
2. Not Known
these classes shouldn't be in VTM. removed them so they are not selectable.
> fix(cb2-8052):Unable to create vehicles with classes:  PSV of Unknown size or Not Know

- src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
CB2-7951: changed the autocomplete to a select so that the options for EU vehicle category display correctly.
> feature CB2-7951: Unable to identify a small trailer as an O2 EU category

- cypress/e2e/testResults/TRL/tests.cy.ts
Update cypress test data to match changes for [CB2-7951](https://dvsa.atlassian.net/browse/CB2-7951)
CVS-Unable to identify a small trailer as an O2 EU category
> test(cb2-7951): update cypress data to match new trailer rules

- src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
- src/app/features/tech-record/create-batch-trl/components/batch-trl-details/batch-trl-details.component.ts
- src/app/features/tech-record/create/create-tech-record.component.ts
- src/app/forms/directives/app-no-space.directive.spec.ts
- src/app/forms/directives/app-no-space.directive.ts
- src/app/forms/directives/app-trim-whitespace.directive.spec.ts
- src/app/forms/directives/app-trim-whitespace.directive.ts
_Users could originally bypass the whitespace directives by pressing Enter on the VIN field, which wouldn't trigger the focusout in the directives_
[CB2-7965](https://dvsa.atlassian.net/browse/CB2-7965)
> fix(cb2-7965): improve directives and add alphanumeric validators

- src/app/features/tech-record/create-batch-trl/create-batch-trl-routing.module.ts
- src/app/forms/custom-sections/tyres/tyres.component.ts
PR to add the tyre search component to the batch routing, and tweaks the tyre component routing to accommodate for this.
[CB2-8107](https://dvsa.atlassian.net/browse/CB2-8107)
> fix(cb2-8107): fix tyre search routing for batch create

- cypress/tsconfig.json
- tsconfig.json
Multiple people are getting errors in VS code because it is detecting cypress types in `.spec` files rather than jest. The tests run fine, however this hinders autocomplete behaviour and erroneously displays errors in the IDE.
Followed the fix on https://github.com/cypress-io/cypress/issues/22059
> chore(cb2-0000): update ts config to handle cypress and jest types

- src/app/forms/templates/test-records/section-templates/emissions/desk-based-emissions-section.template.ts
- src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
- src/app/models/test-types/emissions.enum.ts
_Adds Euro 5 to the emissions standard enum, removes Euro VI, and standardises the options for emissions standard by using the enum_
[CB2-7927](https://dvsa.atlassian.net/browse/CB2-7927)
> feat(cb2-7927): Euro 5

- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
- src/app/forms/components/checkbox-group/checkbox-group.component.html
- src/app/forms/components/checkbox/checkbox.component.html
1. Display information while creating tech record
2. Checkbox labels are clickable
[CB2-8165](https://dvsa.atlassian.net/browse/CB2-8165)
> fix(cb2-8165): fill in details in create vehicle

- cypress/e2e/techRecord/HGV/hgv.cy.ts
- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
- src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
- src/app/forms/components/checkbox-group/checkbox-group.component.html
- src/app/forms/components/checkbox/checkbox.component.html
Navigates back to create tech record if refreshed on the details page or the tyre search page
[CB2-8161](https://dvsa.atlassian.net/browse/CB2-8161)
> fix(cb2-8161): navigates back nicely on browser refresh

- src/app/forms/templates/test-records/section-templates/required/required-hidden-section-hgv-trl.template.ts
Added a default value of null for the numberOfWheelsDriven field so that historic Tech Records which lack this field now supply it before they are sent back to the test service thus fulfilling the validation requirements for the field.
[CB2-8249](https://dvsa.atlassian.net/browse/CB2-8249)
> fix(cb2-8249): numberOfWheelsDriven default value

- src/app/features/tech-record/create-batch/components/select-vehicle-type/select-vehicle-type.component.ts
[CB2-8510](https://dvsa.atlassian.net/browse/CB2-8510)
> fix(cb2-8510): added validator to tes1tes2 based on vehicletype being trl

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-details/batch-vehicle-details.component.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.html
- src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.spec.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.html
- src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.spec.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.ts
- src/app/features/tech-record/create-batch/components/select-vehicle-type/select-vehicle-type.component.ts
- src/app/features/tech-record/tech-record.component.html
- src/app/services/batch-technical-record/batch-technical-record.service.ts
- src/app/shared/pipes/format-vehicle-type/format-vehicle-type.pipe.ts
- src/app/store/technical-records/actions/batch-create.actions.ts
- src/app/store/technical-records/reducers/batch-create.reducer.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
- src/app/store/technical-records/selectors/batch-create.selectors.ts
1. For the main bug - Using takeUntil in EditTechRecordButtonComponent to unsubscribe from multiple observables
2. Updated the content displayed when no vehicle is found
3. Added the vehicle type to the store - to avoid digging it up from current editingtechrecord
4. Changes to select the current or provisional record for update (only psv and hgv)
[CB2-8358](https://dvsa.atlassian.net/browse/CB2-8358)
> fix(cb2-8358): content change plus vehicle type refactor

- src/app/forms/custom-sections/body/body.component.ts
- src/app/models/body-type-enum.ts
- Restores the `skeletal` body type for HGVs and TRLs
- Reviewed all body type codes against documentation
- Fixes an issue where the body type codes were assumed to be the same across vehicle types
[CB2-8590](https://dvsa.atlassian.net/browse/CB2-8590)
> fix(cb2-8590): restores skeletal body type for hgv and trl

- src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
The technical record service reducer no longer overwrites the grossLadenWeight or grossKerbWeight if a null or undefined value is provided by the calling components.
[CB2-8321](https://dvsa.atlassian.net/browse/CB2-8321)
> fix(cb2-8321): Technical record service reducer brake forces

- src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
Fixes an issue where IVA Test Results are failing to be processed downstream because the data-type of the numerical field `noOfAxles` is being sent as a string rather than a number.
The issue is unfortunately due to the value being stored as a string when the Small Trailer was created in VTM, which means ALL tests conducted for that trailer will exhibit this behaviour until their technical records are corrected.
[CB2-8163](https://dvsa.atlassian.net/browse/CB2-8163)
> fix(cb2-8613): fixes noOfAxles data-type issue with small trailer test results

- src/app/forms/custom-sections/tyres/tyres.component.html
- src/app/forms/templates/hgv/hgv-tyres.template.ts
- src/app/forms/templates/trl/trl-tyres.template.ts
The HGV & TRL Tyre Use Code field has been changed to be a more appropriate width
[CB2-8598](https://dvsa.atlassian.net/browse/CB2-8598)
> fix(cb2-8598): changed the size of the tyre use code field

- src/app/forms/components/field-error-message/field-error-message.component.html
- src/app/forms/components/field-error-message/field-error-message.component.ts
- src/app/forms/components/text-input/text-input.component.html
- src/app/forms/custom-sections/tyres/tyres.component.html
- src/app/forms/templates/hgv/hgv-tyres.template.ts
- src/app/forms/templates/trl/trl-tyres.template.ts
Removed the error message width input as the error message field will always inherit the width of its parent. This change prevents text input controls from making their in-line error messages fit the width of the input field rather than the parent container.
[CB2-8598](https://dvsa.atlassian.net/browse/CB2-8598)
Example of prior issue:
Example of updated error message:
> Fix/cb2-8598 - Error message widths

- src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.ts
CB2-8677: 
Due to changes made to the decode pipe it was dispatching GET's for a resource type of REASONS_FOR_ABANDONING. 
The if statement looks for this type and then gets the current vehicles type and uses that to search for the correct reasons for abandoning.
> Fix: cb2 8677: 404 received for some Reasons For Abandoning on saved abandoned test records

- src/app/features/search/search.component.ts
- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.spec.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.ts
- src/app/features/tech-record/create-batch/components/select-vehicle-type/select-vehicle-type.component.ts
- src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
- src/app/features/tech-record/create/create-tech-record.component.ts
- src/app/features/test-records/create/views/create-test-type/create-test-type.component.ts
- src/app/services/technical-record/technical-record.service.ts
- src/app/shared/components/accordion-control/accordion-control.component.spec.ts
- src/app/shared/components/accordion-control/accordion-control.component.ts
- src/app/shared/components/accordion/accordion.component.html
- src/app/shared/components/accordion/accordion.component.spec.ts
- src/app/shared/components/accordion/accordion.component.ts
- src/app/store/technical-records/actions/technical-record-service.actions.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
- src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
- src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Save the state of whether a section is expanded to not, and keep it open after navigation from tyre search, vin/vrm change, batch vehicles, etc.
[CB2-8099](https://dvsa.atlassian.net/browse/CB2-8099)
> feat(cb2-8099): save state for accordion sections

- .github/workflows/tag-merge-conflicts.yml
Adds a github action to dynamically add and remove a merge conflict tag to PRs that need rebasing.
You can see it working on this PR for instance https://github.com/dvsa/cvs-app-vtm/pull/971.
Note:
Sometimes the `mergeable` status is `null`. Github says the "best" thing is to wait and retry don't feel like it's worth adding that logic at this time. Could see how much of an impact it is.
> chore(*): add merge conflict tag action

- src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
- When editing some records, the browser runs out of memory due to an infinite call
> fix(*): browser runs out of memory when editing some records

- src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
CB2- 8144: removes a console log and fixes an issue with errors not showing when no search results returned
> feat(cb2-8144): ability to search reference data

- src/app/forms/custom-sections/body/body.component.html
- src/app/forms/templates/general/hgv-trl-body.template.ts
- src/app/forms/templates/psv/psv-body.template.ts
PSV: Conversion reference number - allow for letter input
Added to PSV, HGV and TRL as Miranda stated that users only really use it for HGVs
[CB2-8706](https://dvsa.atlassian.net/browse/CB2-8706)
> feat(cb2-8706): allows uppercase letters and numbers

- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
The PSV Brake Code Prefix is calculated based on the vehicle laden weight and is shown correctly when amending, but isn't updated or shown correctly when just viewing the record.
[CB2-8968](https://dvsa.atlassian.net/browse/CB2-8968)
> fix(cb2-8968): fixes display of psv brake code prefix

- src/app/services/technical-record/technical-record.service.spec.ts
- src/app/services/technical-record/technical-record.service.ts
CB2-8667
currently if you fill in the details for the single axle a vehicle starts with on psv, trl and hgv the number of axles stays null. adding this to the updateEditingTechRecord method in the tech record service will add the number of axles when you input a value into one of the axle fields.
> Fix/cb2-8667: calculate noOfAxles

- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
Removes the use of alerts from the vehicle technical record component and replaces them with the global error service, bringing it in line with the rest of the application.
[CB2-8777](https://dvsa.atlassian.net/browse/CB2-8777)
> feat(cb2-8777): Vehicle technical record errors

- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
Adds the updated brakeCode to the root of the `techRecord`, as well as within the `brakes` object.
Related to the previous fix: [CB2-8968](https://dvsa.atlassian.net/browse/CB2-8968)
> fix(cb2-8968): adds psv brakeCode fix to root of the techRecord

- src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
- src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
- src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.spec.ts
- src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.ts
- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.spec.ts
- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
- src/app/models/vehicle-tech-record.model.ts
- src/app/services/axles/axles.service.ts
- src/app/services/technical-record-http/technical-record-http.service.spec.ts
- src/app/services/technical-record-http/technical-record-http.service.ts
- src/app/services/technical-record/technical-record.service.ts
- src/app/store/technical-records/actions/technical-record-service.actions.ts
- src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
- src/app/store/technical-records/effects/technical-record-service.effects.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
Updating hidden in vta on small trl removes number of axles.
Update tech record action now uses `systemNumber` and `createdTimestamp` instead of whole record to dispatch action. This ensures callers of the action go trough `updateEditingTechRecord` method in technical record service.
Moved logic to determine whether to create a new provisional record into the summary component.
[CB2-8806](https://dvsa.atlassian.net/browse/CB2-8806)
> fix(cb2-8806): updating hidden in vta on small trl removes number of axles

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
fix psv record brake rendering issue.
- `*ngSwitchCase` needs to be the top-level conditional e.g. :
This does not work:
```html
<ng-container *ngIf="true">
<div *ngSwitchCase="'string'"> Some field </div>
</ng-container>
```
But this does:
```html
<ng-container *ngSwitchCase="'string'">
<div *ngIf="true"> Some field </div>
</ng-container>
```
- Also made `techRecordCalculated` potentially undefined as it is `undefined` at constructor time.
[CB2-9080](https://dvsa.atlassian.net/browse/CB2-9080)
> fix(cb2-9080): psv record brake rendering issue

- makefile
- src/app/features/tech-record/create/create-tech-record.component.html
- src/app/features/tech-record/create/create-tech-record.component.ts
- src/app/forms/validators/custom-validators.ts
receive an error message if trying to create a new Technical Record with an O, I or Q in the VIN: ‘VIN should not contain O, I and Q’ Provide a hint for the VIN, letting users know it should be 17 characters long: ‘VIN should usually be 17 characters long.’
[CB2-8591](https://dvsa.atlassian.net/browse/CB2-8591)
> CB2-8591: validation on vin

- src/app/forms/components/checkbox-group/checkbox-group.component.html
- src/app/forms/components/number-input/number-input.component.html
- Fixes the required tag not showing up for upper and lower deck on PSV 
- Fixes the tag rendering in the wrong location for vehicle subclass on LGV
[CB2-8709](https://dvsa.atlassian.net/browse/CB2-8709)
> fix(cb2-8709): Fix label rendering issues

- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
- src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
- src/app/forms/custom-sections/weights/weights.component.ts
This is to auto calculate the gross laden weight based on the manufacture year, total passengers and gross kerb weight
[CB2-8714](https://dvsa.atlassian.net/browse/CB2-8714)
> Feature(CB2-8714): Auto calculate PSV laden weight

- src/app/forms/custom-sections/body/body.component.html
- src/app/forms/templates/general/hgv-trl-body.template.ts
- src/app/forms/templates/psv/psv-body.template.ts
Allow existing space and trim space when entering in the field.
[CB2-9119](https://dvsa.atlassian.net/browse/CB2-9119)
> fix(cb2-9119): allow space in conversion ref no

- src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
multiple error messages while operation processes
adds a take(1) to the nestedRouteParams pipe so only the first set are taken and the dispatch is only fired off once. 
[CB2-9118](https://dvsa.atlassian.net/browse/CB2-9118)
> fix(cb2-9118): multiple error messages while operation processes

- src/app/forms/validators/custom-validators.ts
Fixes the email validation regex to allow domain names with multiple periods (e.g. `.co.uk`)
[CB2-9195](https://dvsa.atlassian.net/browse/CB2-9195)
> fix(cb2-9195): fixes email validation for multiple-period domain addresses

- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
Fix the bug when create a provisional Tech record and observe that ‘Provisional’ and ‘Archive' are overlapped.
[CB2-9199](https://dvsa.atlassian.net/browse/CB2-9199)
> fix(cb2-9199): fix the Overlapping CSS in Record type bug

- src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Fixed an issue where current VIN records were not displaying VIN warnings correctly on amendment
[CB2-9046](https://dvsa.atlassian.net/browse/CB2-9046)
> fix(cb2-9046): current tech record VIN warnings

- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
- src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
CB2-9269
remove vehicle type check from show test button the new list of tests needs it to show on provisionals for all types
[CB2-9269](https://dvsa.atlassian.net/browse/CB2-9269)
> fix(cb2-9269): iva test types missing for lgv and psv provisional tech records

- src/app/app-routing.module.ts
- src/app/features/tech-record/tech-record-routing.module.ts
- src/app/features/test-records/amend/amend-test-records-routing.module.ts
- src/app/features/test-records/create/create-test-records-routing.module.ts
- src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
- src/app/resolvers/contingency-test/contingency-test.resolver.ts
- src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.spec.ts
- src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.ts
- src/app/resolvers/tech-record-view/tech-record-view.resolver.spec.ts
- src/app/resolvers/tech-record-view/tech-record-view.resolver.ts
- src/app/resolvers/test-result/test-result.resolver.spec.ts
- src/app/resolvers/test-result/test-result.resolver.ts
- src/app/resolvers/test-stations/test-stations.resolver.spec.ts
- src/app/resolvers/test-stations/test-stations.resolver.ts
- src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.spec.ts
- src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.ts
- src/app/resolvers/title/title.resolver.spec.ts
- src/app/resolvers/title/title.resolver.ts
IMPORTANT: 
The resolver class are being deprecated in the following angular version. All of the resolvers have been replaced by the functional route resolver " ResolveFn".
[CB2-9639](https://dvsa.atlassian.net/browse/CB2-9639)
> feat(cb2-9639): replace deprecated Resolver class

- src/app/forms/components/autocomplete/autocomplete.component.scss
[CB2-9679](https://dvsa.atlassian.net/browse/CB2-9679)
> fix(cb2-9679): add font-family to autocomplete options

- src/app/forms/templates/car/car-tech-record.template.ts
- src/app/forms/templates/hgv/hgv-tech-record.template.ts
- src/app/forms/templates/lgv/lgv-tech-record.template.ts
- src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
- src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-light-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-light-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group4-lgv.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/group-3-light-vehicle-section.template.ts
- src/app/forms/templates/trl/trl-tech-record.template.ts
- src/app/models/test-results/test-result.model.ts
- src/app/models/vehicle-tech-record.model.ts
- src/app/resolvers/tech-record-validate/tech-record-validate.resolver.spec.ts
- src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
- src/app/store/technical-records/effects/technical-record-service.effects.ts
- src/app/store/test-records/effects/test-records.effects.spec.ts
- src/mocks/mock-test-result.ts
- src/mocks/trl-record.mock.ts
Implemented the enums available from the types package within VTM allowing only valid options for PSV and HGV to be selected.
[CB2-9595](https://dvsa.atlassian.net/browse/CB2-9595)
> feat(cb2-9595): Update EU Vehicle Category options

- package-lock.json
- package.json
- src/app/forms/templates/car/car-tech-record.template.ts
- src/app/forms/templates/hgv/hgv-tech-record.template.ts
- src/app/forms/templates/lgv/lgv-tech-record.template.ts
- src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
- src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
- src/app/forms/templates/trl/trl-tech-record.template.ts
- src/app/models/body-type-enum.ts
- src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
- src/app/store/technical-records/effects/technical-record-service.effects.ts
- src/mocks/hgv-record.mock.ts
- src/mocks/psv-record.mock.ts
- src/mocks/trl-record.mock.ts
CB2-9601: uses the types package for the vehicle configuration and nulls vehicle configuration if you change a hgv to psv or psv to hgv
> feat(cb2-9601): update vehicle configuration options

- src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
- src/app/features/tech-record/tech-record-routing.module.ts
- src/app/forms/templates/car/car-tech-record.template.ts
- src/app/forms/templates/hgv/hgv-tech-record.template.ts
- src/app/forms/templates/lgv/lgv-tech-record.template.ts
- src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
- src/app/forms/templates/psv/psv-tech-record.template.ts
- src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
- src/app/forms/templates/trl/trl-tech-record.template.ts
CB2-9937:
The addition of the lodash isEmpty function broke the summary of changes page. This PR reverts that change and changes the orders of the resolvers on the route to summary changes, this was because on a refresh the page was loading as a blank page, rather than navigating back as it used to. 
> fix(cb2-9937): review screen is broken

- src/app/forms/templates/general/adr.template.ts
Fix the bug when the ADR body type includes 'tank', battery list could still showing.
[CB2-9744](https://dvsa.atlassian.net/browse/CB2-9744)
> fix(cb2-9744): fix battery list display improperly

- src/app/features/tech-record/tech-record-routing.module.ts
- src/app/forms/custom-sections/tyres/tyres.component.ts
- src/app/resolvers/tech-record-data/tech-record-data.resolver.ts
This was an issue due to the changes with adding additional validation to tyres and weights. Originally we were making a network request EVERY TIME we added an axle to fetch the specific reference data - and would have need to do so in order to run validation for tyre weights. This ran into cold starts for lambdas and the inherent overhead of making several, albeit smaller, network requests. To 10x the speed of this we now moved the prefetching of reference data to a resolver to guarantee is availability when on the tech-record page which now uses the cached version. 
This worked, but a a later patch to the validation also required tyre reference as well as load index which wasn't being pulled in when amending as this route was missing the resolver. This wouldn't be noticed if you had …
> fix(cb2-10174): ensure prefetched data is provided for all dependent routes

- src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.ts
- src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
- src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
- src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
- src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
- src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
- src/app/features/tech-record/create/create-tech-record.component.ts
- src/app/forms/custom-sections/adr-examiner-notes-history/adr-examiner-notes-history.component.ts
- src/app/forms/custom-sections/approval-type/approval-type.component.ts
- src/app/forms/custom-sections/plates/plates.component.spec.ts
- src/app/forms/custom-sections/plates/plates.component.ts
- src/app/forms/custom-sections/tyres/tyres.component.spec.ts
- src/app/forms/custom-sections/tyres/tyres.component.ts
- src/app/models/vehicle-tech-record.model.ts
- src/app/services/axles/axles.service.ts
- src/mocks/psv-record.mock.ts
Generally the aim of this PR is to get the codebase to have a better source of truth for types, with better inference - all derived from the types package.
Changes:
1. Changes use of unions of TechRecordType to use more succinct syntax
2. Adds VehicleOtherThan utility type to exclude vehicle types from TechRecordType, this also replaces the NotTrailer type with this more general utility type, i.e. VehicleOtherThan<'trl'>
3. Adds Empty utility type to convert another type into the same type but with nullable fields
4. Adds Axles type which is derived from the techRecord_axles property of the V3 model and infers the specific properties of that axle based on the generic passed in, e.g. Axles<'psv'> returns an array of PSVAxles, where each item can have weights_kerbWeight. By default this …
> fix(cb2-8121): general improvements to the type system

- src/app/forms/custom-sections/plates/plates.component.spec.ts
- src/app/forms/custom-sections/plates/plates.component.ts
Plates were not being correctly checked due to a nested some and the way returns work around this. The tyre fitment codes could be left blank. 
[CB2-10433](https://dvsa.atlassian.net/browse/CB2-10433)
> fix(cb2-10433): repair tyre checks on plate validation

- src/app/forms/templates/general/adr.template.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
The reference number should be displayed when the user selects option 'yes' in the battery applicable field.
[CB2-10441](https://dvsa.atlassian.net/browse/CB2-10441)
> fix(cb2-10441): fix reference number incorrectly display

- src/app/forms/models/validators.enum.ts
- src/app/forms/services/dynamic-form.service.ts
- src/app/forms/templates/test-records/create-master.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/contingency-m1-iva-vehicle-section.template.ts
- src/app/forms/utils/error-message-map.ts
- src/app/forms/validators/custom-validators.spec.ts
- src/app/forms/validators/custom-validators.ts
Makes Odometer Reading/Units optional on IVA tests for all vehicle types except Motorcycles by creating a new template specifically for those test types. Also fixes a typo with a validator.
[CB2-10531](https://dvsa.atlassian.net/browse/CB2-10531)
> feat(cb2-10129): Odometer reading marked as optional on IVA

- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
fix listStatementApplicable not be set null
[CB2-10555](https://dvsa.atlassian.net/browse/CB2-10555)
> fix(cb2-10555): fix listStatementApplicable not be set null

- package-lock.json
- package.json
- src/app/forms/templates/general/adr.template.ts
changes units on the label to tonnes and will allow up to 2 decimal places. Preserves max number as 99999999 based on the previous max length of string. 
Types package PR requires merging and v3 bumping before this will submit as change of data type
> feat(cb2-10521): change adr brake endurance weight unit of measurement to tonnes on a technical record

- src/app/forms/components/view-list-item/view-list-item.component.html
- src/app/forms/custom-sections/adr-tank-details-initial-inspection-view/adr-tank-details-initial-inspection-view.component.html
- src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-view/adr-tank-details-subsequent-inspections-view.component.html
- src/app/forms/services/dynamic-form.types.ts
- src/app/forms/templates/general/adr-summary.template.ts
- src/app/forms/templates/general/adr.template.ts
Uncomments code we had previously for the custom view modes of TC2 and TC3 inspections of ADR vehicles with an ADR vehicle type containing the words 'tank' or 'battery'.
[CB2-10591](https://dvsa.atlassian.net/browse/CB2-10591)
> fix(cb2-10591): uncomment custom views for TC2 and TC3 inspections

- src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.html
- src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.scss
- src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.spec.ts
- src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.ts
- src/app/forms/models/validators.enum.ts
- src/app/forms/services/dynamic-form.service.ts
- src/app/forms/templates/general/adr.template.ts
- src/app/forms/utils/error-message-map.ts
- src/app/forms/validators/adr/adr.validators.spec.ts
- src/app/forms/validators/adr/adr.validators.ts
- src/app/forms/validators/custom-validators.ts
- Refactors the tank statement un numbers edit component - moving validation logic back to the template.
- Removes the old validator in favour of an inline custom one for both UN numbers and the reference number
- Adds functionality to the global error service to display multiple separate errors from a single validator - this was needs to show multiple warnings of controls of form array exceeding the 1500 character limit.
[CB2-10930](https://dvsa.atlassian.net/browse/CB2-10930)
> feat(cb2-10930): refactor un subsequent inspections component

- src/app/forms/custom-sections/tyres/tyres.component.html
Increases max width of fitment code select dropdown in the tyres component so it no longer is cut-off on larger screens.
[CB2-11013](https://dvsa.atlassian.net/browse/CB2-11013)
> fix(cb2-11013): prevent fitment code being cut-off on larger viewports

- src/app/services/technical-record/technical-record.service.ts
when performing a cherished transfer and you add the same VRM that is already on the vehicle in the current VRM field you get an error, if you type anything in the third mark it was disappearing, this change makes the error persist. 
> fix(cb2-10560): shows the you must provide a new vrm error if you add a third mark

- src/app/store/technical-records/effects/technical-record-service.effects.ts
Renames applicationId to techRecord_applicationId so its saved correctly in db
[CB2-9198](https://dvsa.atlassian.net/browse/CB2-9198)
> fix(cb2-9198): correctly name application id key so its saved in the db

- src/app/models/test-types/test-type.model.ts
- src/app/shared/components/test-certificate/test-certificate.component.html
- src/app/shared/components/test-certificate/test-certificate.component.scss
- src/app/shared/components/test-certificate/test-certificate.component.spec.ts
- src/app/shared/components/test-certificate/test-certificate.component.ts
- src/app/shared/directives/retrieve-document/retrieve-document.directive.ts
- src/app/store/test-records/selectors/test-records.selectors.spec.ts
- src/app/store/test-records/selectors/test-records.selectors.ts
- src/mocks/custom-defect.mock.ts
The new IVA/MSVA tests that use the required standards taxonomy will be able to retrieve an IVA30/MSVA30 certificate on the Test Record History page.
[CB2-9649](https://dvsa.atlassian.net/browse/CB2-9649)
> feat(cb2-9649): allow new failed iva/msva tests to fetch certs

- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group4-lgv.template.ts
- src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
- src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
- src/app/resolvers/contingency-test/contingency-test.resolver.ts
Updates previous pr.
Adds make, model and body type to the payload for all vehicles even if they don't collect that data. Changes return on those from undefined to null.
[CB2-10685](https://dvsa.atlassian.net/browse/CB2-10685)
> fix(cb2-10685): add make model and body type to payload on *all* vehicles

- src/app/forms/templates/general/adr.template.ts
Adds hint text for 3 month extension ADR field.
[CB2-10286](https://dvsa.atlassian.net/browse/CB2-10286)
> feat(cb2-10286): add hint text to 3 month extension

- package-lock.json
- package.json
- src/app/forms/custom-sections/adr-examiner-notes-history-view/adr-examiner-notes-history-view.component.spec.ts
- src/app/forms/templates/general/adr-summary.template.ts
- src/app/forms/templates/general/adr.template.ts
- src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Introduces a mark to determine whether a vehicle is used for international journeys or not.
[CB2-10740](https://dvsa.atlassian.net/browse/CB2-10740)
> feat/CB2-10740 - Mark if a vehicle is used for international journeys on VTM

- src/app/services/test-records/test-records.service.ts
- src/app/store/test-records/effects/test-records.effects.ts
- src/app/store/test-records/selectors/test-records.selectors.ts
[CB2-11930](https://dvsa.atlassian.net/browse/CB2-11930)
> feat(cb2-11930): ensure certificate number is sent to backend if it exists on MVSA IVA tests

- src/app/forms/templates/general/adr-summary.template.ts
- src/app/forms/templates/general/adr.template.ts
[CB2-11908](https://dvsa.atlassian.net/browse/CB2-11908)
> fix(cb2-11908): remove duplicate label from additional examiner notes history

- src/app/forms/models/testTypeId.enum.ts
[CB2-12056](https://dvsa.atlassian.net/browse/CB2-12056)
> feat(cb2-12056): test codes moved

- .snyk
- src/app/models/test-results/test-result.model.ts
- src/app/resolvers/contingency-test/contingency-test.resolver.ts
- src/app/services/test-records/test-records.service.ts
Set body model of PSV to null if its an empty string so it passes backend validation.
[CB2-12009](https://dvsa.atlassian.net/browse/CB2-12009)
> fix(cb2-12009): default psv body model to null if its an empty string
